- postajob/templatetags/postajob_tags.py
- templates/postajob/dseo/view_job.html
- templates/postajob/myjobs/view_job.html
This addresses the issue of notifying a user that there could be a delay between when the job link appears and when a job is actually available at that link. 
I moved the early bail out for the template tag so that we aren't needlessly doing queries on a job that hasn't even been approved. 
The issue of how best to represent job links has been deferred to a separate ticket (linked to in pd-899).
> [PD-899] Add help text to job view

- postajob/models.py
- templates/myjobs/email_inactive.html
- templates/postajob/invoice_email.html
- templates/postajob/request_email.html
One email has a link to a view that I'm not introducing to microsites, so it remains secure.my.jobs.
The inactivity email seemed like it would benefit from Terms and Privacy links, so I added them. The postajob emails did not, so I didn't.
> Add "powered by my.jobs" to templates

- postajob/forms.py
I think we fixed the underlying issue behind PD-821 at some point in the past, as I don't see it happening now. I did find an issue with purchased jobs not appearing in solr while testing, so I'm fixing it here.
> Ensure paid=True on free purchased products [PD-821]

- mysearches/forms.py
- mysearches/migrations/0003_partner_saved_search_default_sort_by_to_date.py
Creating a Partner Saved Search will now have sort_by = Date
Added a data migration to easily update our db on production. (sets all partner saved searches sort_by = Date)
> PRM Saved Search - force sort order to date (newest first)

- mypartners/forms.py
- templates/includes/error-highlight.html
- templates/mypartners/includes/pss_card.html
- A partner saved search that hasn't been sent says "Never" for "Last sent" instead of "None"
- opted out emails are disabled with help text provided:
- Unlike the last PR I submitted with the same title, you can save the form.
> [PD-920] Disable opted-out emails on saved search form

- import_jobs.py
If no jobs from the buid exist in solr, that trying to index from SEOXML will fail.
> Fix for task update solr

- postajob/urls.py
> Remove decorator from normal job form view since companies posting to their own site don't require a site package [PD-940]

- mysearches/tests/test_forms.py
- mysearches/views.py
- templates/mysearches/email_base.html
- templates/mysearches/saved_search_disable.html
* Addition of unsubscribe and deactivation links
* Removal of saved search deletion link when a partner saved search is deactivated
> [PD-930] Updated partner saved search emails to include deactivation and unsubscribe links

- mypartners/views.py
- mysearches/views.py
- postajob/tests/test_views.py
- postajob/urls.py
- postajob/views.py
- seo/models.py
- templates/includes/inactive-user.html
- templates/mydashboard/mydashboard.html
- templates/mypartners/partner_searches.html
- templates/mypartners/prm.html
- templates/mysearches/saved_search_main.html
- templates/warning_page.html
- universal/decorators.py
**NOTE: I'm holding off writing unit tests for this until I take care of *some* of the circular imports that we have within our model modules**
I've introduced the `warn_when` decorator factory and from that created the `warn_when_inactive` and `warn_when_no_packages` to be used in mypartners and postajob, respectively. The factory is used by passing a feature name, message text, link (optional) and link_text (optional). 
* This code touches numerous views, each of which is already wrapped by another decorator. As such, the hardest part about reviewing this ticket will be ensuring that the proper behavior is exhibited for different kinds of users (anonymous, company user, admin, etc). 
* As I mostly changed *how* these items were implemented, I didn't introduce any new unit tests. One of …
> [PD-721][PD-834] Wrote new decorator to display warning messages for disabled features

- mysearches/tests/test_views.py
- mysearches/views.py
- templates/mysearches/saved_search_disable.html
- templates/mysearches/saved_search_row.html
I added information about the partner who created the saved search since those can't be deleted by the use. I also linked to the partner page.
Screenshot:
Before, when clicking the delete all saved searches link in the confirmation email, you'd still see a delete all link, which would delete partner saved searches as well. I originally hid this, but realized it would prevent users from deleting all saved searches. After first trying to separate the content on this page by saved search type as suggested, I went with a delete modal instead, a la partner library. I didn't bother listing the partner saved searches that wouldn't be deleted explicitly since clicking delete redirects to the saved search overview anyway.
In short, disabling a single partner saved search hides the delete button …
> [PD-930, PD-946] Updated disable saved search and saved search overview pages

- postajob/urls.py
- universal/decorators.py
- If a canonical company isn't set, 404. (instead of 500 caused by Attribute error because canonical company wasn't properly set)
- I also ensured that anonymous users don't see a 500 error and are correctly redirected to the login page instead.
> [PD-834][PD-951] Updated a few decorators

- mysearches/tests/test_models.py
- templates/mysearches/email_table_include.html
Jason's suggestion, "In that case, change the line to read:
This email includes the top N jobs. There may be more on the source site."
Currently it reads:
Showing the top N jobs. - View All Jobs
The suggested text was making "View all Jobs" and the text on the right wrap.
Discuss.
> my.jobs - saved search - x of more than z jobs, x=z [PD-943]

- myreports/decorators.py
- myreports/tests.py
- myreports/tests/test_views.py
- myreports/urls.py
- myreports/views.py
- postajob/decorators.py
- postajob/urls.py
- templates/myreports/reports_overview.html
- universal/decorators.py
* I fixed the logic of my `warn_when` decorators to be less confusing
* I added anonymous user redirect behavior to the base decorator
* I moved app-specific decorators to the appropriate apps while keeping the really generic ones in universal.helpers
* updated url name to match scheme used in other apps
* ~switched to using user_passes_test since:~~
* ~~@galitskyd  was interested in using the decorator to begin with~~
* ~~we need the redirect behavior for anonymous login~~
* used a custom version of my decorator
* we want the redirect behavior for anonymous logins still
* we want a logged in user to 404, not redirect to the main screen
* created a dummy edit report response so that the overview renders properly
* started writing unit tests
> [PD-961, PD-985] MyReports Updates

- mypartners/tests/test_views.py
- mypartners/views.py
- templates/mysearches/view_full_feed.html
* see ticket for screenshots
* added relevant unit test
* creates a copy of the existing search with "Copy of" appended to the name and email emptied.
> [PD-997] Implemented Duplicating a Partner Saved Search

- mypartners/models.py
- mypartners/views.py
Previously, we were joining saved search emails and regular emails. This re-splits them. To test, you can go to "Manage Record" in the record overview (The old PRM one, not the new reports link) and check that the drop down shows the Partner Saved Search Email option.
> [PD-765, PD-1028] Split emails and partner saved search emails in contact record view.

- seo/views/search_views.py
Since we can't sort custom facets until we have all of them anyway, we've switched to loading all of the facets at once. This makes homepage do the same.
> All custom facets should be loaded on job listing homepage [PD-1032]

- myreports/tests/test_views.py
- myreports/views.py
- re-enables test that checks request type
- 404 if csrfmiddlewaretoken is some how missing from post request and django doesn't catch it
- updates tests to use post instead of get
> Change get requests to posts.

- myjobs/admin.py
There's no reason to edit email logs in the admin.
As stated in the ticket description, making this read-only reduced the size of the request from 3.3MB to 746 bytes.
> Make EmailLog read-only [PD-1023]

- mypartners/models.py
Fixes error caused by contactrecord not having a state field.
> Ignoring the state field in contact record

- mydashboard/tests/test_views.py
- mypartners/views.py
- mysearches/helpers.py
- mysearches/tests/test_helpers.py
- mysearches/views.py
* made sure the jobs_per_email field was passed to the function that parses feeds
* made sure that said value isn't ignored in that function
I have a unit test written for this, but I am apparently passing the wrong arguments to parse_feed. Will push when I've figured it out.
> [PD-1030] Proper jobs-per-email count when viewing a saved search

- myjobs/tests/test_views.py
- mypartners/models.py
- myreports/tests/test_views.py
* Extended TestClient so that you can specify a path and/or data at object creation.
* Refactored myreports unit tests using these improvements.
Basically, if you need to do multiple tests that hit the same view (but with different parameters), you can simply create a client with that path:
```python
client = TestClient(path='/foo/bar')
```
Now, when you call `post` or `get`, you don't have to pass the path every time:
```python
self.client.post()
```
If you do this, you can no longer pass a raw dict as data, and must name it explicitly:
```python
self.client.post(data={'foo': 'bar'})
```
If you don't pass in a path to the constructor (or manually pass a path when you call `get` or `post`, `TestClient` will act exactly is it always has (hence why older tests are still passing).
> [PD-1051, PD-1052] Filtering by City in myreports

- myjobs/templatetags/common_tags.py
- myjobs/views.py
Before, the number of queries made by the top bar grew linearly proportional to the number of companies the logged in user belonged to. This is now constant. For example, with 23 companies, 50 queries were being made, where as with this code, that was reduced to 27. Other queries seem to be tied to middleware and a few other things, which I expect can be tackled as a separate issue.
> [PD-791] Reduce number of queries topbar makes

- mypartners/tests/test_views.py
- mypartners/views.py
- mysearches/models.py
- templates/mysearches/view_full_feed.html
The number of new jobs is shown under "Jobs per Email" as long as it is different from what the member chose. In this picture, we tried to do 100 jobs per email but only 44 were new. In the event that there were 100 new jobs, the 100 would still be displayed but there would be no parenthesized number next to it.
Right now the number in the header and the number of new jobs are the same. I don't think that's a given, but I'm not sure.
> Add fields to partner saved search detail page [PD-1027]

- myreports/views.py
* Earlier implementation discarded many-to-many fields when exporting to json
* I was also able to reduce response times from ~4 seconds to < 1 second on average.
* Response size is huge for contact records due to the fact that notes are in HTML. Stripping the HTML reduced size from ~10MB to ~4MB, but increased response time to ~3 seconds due to the extra processing required.
* If we later decide that size is an issue (I'm not sure it would be, considering it's data export, which we should expect to be large in these cases), I think MessagePack is a better alternative to conditionally truncating data. Initial experiments showed that I could get sizes down from ~10MB to ~600KB
> [PD-1110] M2M and FK support for reports

- mysearches/helpers.py
- mysearches/models.py
We shouldn't be adding days_ago to partner saved search feeds. We should also use the largest span of time available to us, either the last sent date or a value calculated based on today or the selected interval.
> Ensures partner saved searches backfill properly [ST-1029]

- social_links/models.py
The files are getting uploaded to the correct locations and default_storage is smart enough to correct the links when clicked in the admin, but this slash is missing when we prepend our cloudfront url.
> Icon paths should be prefaced with a slash [PD-230]

- mypartners/forms.py
- mypartners/helpers.py
- mypartners/migrations/0009_auto__add_field_partner_data_source__add_field_contact_library.py
- mypartners/migrations/0009_auto__add_field_partner_source__add_field_contact_library.py
- mypartners/migrations/0010_update_partner_data_source.py
- mypartners/models.py
- templates/mypartners/includes/partner_card.html
The source field appears on the new/edit partner forms. In the event that a partner was added from the library, the source is automatically populated with the data source for that entry in the library. It can later be edited if, as Hal suggested, the partner was met at a con of some type and was later located in our library.
Updating the form to be more pleasing will be done in PD-1163.
> Add source to Partner model [PD-1162]

- tasks.py
- templates/mypartners/partner_library.html
Updated the URL in the PRM Resource Library template file and the comment in tasks.py. In tasks.py, the source used to retrieve the data did NOT change.
> Change the URL for the Disability and Veterans Resource Dir. PD-1186

- seo/monitoring.py
ETL monitoring is producing false positives because the `state.tasks_by_type` function uses the name defined in the `@task(name=...`  rather than the name of the function.  Also added to monitoring the priority_etl_to_solr tasks.
> Fix for ETL monitoring problems.

- myreports/views.py
Without this, reporting is broken in quality control ever so slightly
> Remove report name from response.

- mypartners/helpers.py
Somewhere along the line (I think when I added tags search to contact records) I must have changed the query parameter. Rather than try and track down that change, I just made the change in PRM.
> Added s to tags.

- cdn_files/src-nlx-org/robots.txt
- static/robots.txt
- templates/robots.txt
Strips most of the robots.txt disallow rules from robots.txt for my.jobs and S3. Once merged, the S3 robots file will be pushed to the root of src-nlx-org folder. It previously wasn't in any version control.
> [PD-1276] Update robots.txt files

- myreports/helpers.py
- myreports/tests/test_helpers.py
I've created a feature branch for this so that I can keep these changes together without having to worry about being out of sync between master and quality-control (eg, numerous hotfixes).
- Performance improvements are minimal, but I'm happier with this implementation as it doesn't require intermediate variables
- Added unit tests to validate functionality
- You'll note that this doesn't work for json output. Reason for that is that Json objects aren't ordered. I plan to address this at a later date with a different ticket (perhaps not part of this refactoring, though). Luckily, I use the serialized Python to do CSV export, so not much is lost by omitting this.
In short, it's written in a less imperative and more functional style.
> [PD-1273] Cleaned up the value and order_by specific bits of serialization

- mypartners/models.py
- myreports/helpers.py
- myreports/views.py
- static/my.jobs.163-21.css
- static/reporting.163-20.js
Reduces query time (compared to production) from ~20 seconds to ~4.
@galitskyd  - This basically just removes the `count` option from API calls. Feel free to wait until #1469 is merged and you've re-synced with quality control (which is why the changes seem so extensive).
> Faster reports

- static/my.jobs.163-29.css
- templates/base.html
.placeholder styling for reporting was adding 5px margin to the right of IE8 fields because of placeholder.js.
Fixed this:
> [PD-1326] PRM Forms IE8 alignment fix

- static/my.jobs.163-29.css
- templates/mypartners/includes/partner_card.html
- templates/mypartners/includes/partner_sidebar.html
Way back when we went from "Disabled" to "Disability" we forgot to change the class associated which broke the function that handles what is/isn't checked. Only affected modern browsers when the user loaded OFCCP page with a URL containing special_interest=disability.  But made IE8 and 9 unable to filter the OFCCP page by disability.
Fix: Changed class disabled to disability
> [PD-1331] OFCCP disability button unchecks on page load

- static/my.jobs.ie.163-29.css
- static/partner-reports.163-29.js
- templates/base.html
- templates/mypartners/overview.html
- templates/mypartners/partner_reports.html
fill_piehole function was selecting an iframe and trying to do jQuery functions on it which was cause permission denied errors. The iframe is only rendered on IE8 because google charts uses SVGs but IE8 doesn't support SVGs so their fallback is VML inside said iframe.
Before:
After:
> [PD-1327] Google charts errors on IE8

- myemails/migrations/0004_auto__del_emailcrontask__add_emailtask.py
- myemails/models.py
- myemails/tests/test_models.py
Depends on #1495.
It's a little fuzzy what the ticket was asking for, so I opted to allow all current event types to be scheduled (ValueEvents will be scheduled immediately).
As this is based off of #1495, only the final commit is relevant to this PR.
This could use a good review to make sure I'm not being stupid.
> Allow both event types to be queued [PD-763]

- myreports/helpers.py
- myreports/views.py
Just a few aesthetic improvements requested in the last month or so that didn't fit within the scope of other tickets.
- `datetime`s are now pretty printed instead of in UTC ISO format
- report name mangling* only happens on report download
This is ready to merge as soon as it's reviewed, but I'll keep adding things to it if it doesn't get merged. If you want less code to review, review it sooner. Don't say I didn't warn you.
* firefox doesn't recognize files with spaces in their name
> Misc. Reporting Tweaks

- static/reporting.164-19.js
- templates/myreports/reports.html
When viewing a Contact Report. If a contact has multiple locations, for example: Zionsville, IN; Carmel, IN; Fishers, IN; Austin, TX. In the table it would show up as IN, IN, IN, TX instead of IN, TX.
> [PD-1370] Contact View shows duplicate States

- myreports/helpers.py
None doesn't have a split method, hence the error. This guarantees that None's are strings instead.
> [PD-1379] Moved None pruning to prevent errors on split.

- seo/breadbox.py
- seo/tests/test_breadbox.py
Rather than replacing the location slug text, I find out where the location slug starts and ends and replace that (by converting the location and location slug to lists).
I contemplated using string.find for this, but thought it would result in a similar issue to what we have now. Now we strip all occurrences of a substring. Find would strip only the first, but could produce a false positive. The alternative might be to match substrings wrapped with slashes, but I wasn't sure if that would be reliable, hence why the current method.
> Tried a different way of replacing a location slug.

- static/reporting.164-20.js
- templates/myreports/reports.html
This makes it so that the tags filter on reporting only filters on contact record, rather than all taggable models in a company. NOT a hotfix.
> update tags filtering for reporting

- mypartners/views.py
- templates/mypartners/view_record.html
Basically, the view record page is determined by the page the record was on in the results, not the id of the record. 
I also made sure the proper verbiage was shown when editing vs viewing a record. This also enables the default text for records without tags.
> [PD-1372] Editing a contact record now goes back to the correct record.

- myblocks/models.py
- static/filter_carousel.js
- static/pager.164-21.js
- templates/def.ui.dotjobs.css
- templates/includes/more_less_links.html
- templates/seo_base.html
The issue is that there is no url for featured companies. The proper fix would involve touching pager.js, seo/urls/search_urls.py, seo/views/search_views.py, seo/helpers.py, and seo/filters.py at a bare minimum (I stopped digging once I realized there were this many things to change). 
As this template is only used by one company, I decided on a work around instead, which takes advantage of the fact that the second result set is already loaded. Thus, if a request comes for more companies, those companies are simply loaded. The implication of this work around is that there may be at a maximum, 20 featured companies, until a proper fix is implemented.
> [ST-1258] more button work around for job listing

- myreports/helpers.py
- myreports/models.py
- myreports/tests/test_views.py
- myreports/views.py
- static/my.jobs.165-01.css
- static/reporting.165-01.js
- templates/base.html
- templates/myreports/includes/report-archive.html
- templates/myreports/includes/report-sidebar.html
- templates/myreports/reports.html
- Added new column for regenerate and updated JS to handle new rules
- Edit regenerate functionality to always regenerate (as opposed to checking to see if the file already exists and ignore the request) and delete the old report file if it already exists.
Sidebar:
Archive:
> [PD-1335] Reports - add regeneration as 4th column in report lists

- myreports/models.py
- myreports/tests/test_views.py
Didn't notice before because contactrecord report doesn't rely on json. The fix was to not pass values to the serialize function when regenerating. In other words, json represents all pristine records and should only be modified on export (which I thought I was doing but obviously wasnt).
> [PD-1415] Fixed regenerate.

- myreports/tests/test_views.py
- myreports/views.py
I based this off of #1579 since that PR also changes unit tests. You can either  merge that, then this, or merge this and close that.
The only changes relevant to this PR are [here](https://github.com/DirectEmployers/MyJobs/pull/1576/files#diff-eb9601953df6f5b354db064401d8015cR253) and [here](https://github.com/DirectEmployers/MyJobs/pull/1576/files#diff-ebd3cabe61d5dc9f762eb5c7c5138120R289)
Before:
After:
~~Still need to write a test to ensure that on the download page,  blacklisted columns don't show up, but I wanted this up to let it be known that this is being worked on.~~
Writing tests for this now will cause a merge conflict, so I'll write them once #1574 is merged.
> [PD-1420] Black-listed colmns so they dont show up in reports.

- seo/breadbox.py
- seo/tests/test_breadbox.py
The location slug may already have been removed from the path, so we shouldn't check against the path for membership before finding out where to try and remove said location slug.
Extended unit test to expand to this case. If you run the tests on master without the changes to the view, you'll see a failure similar to what's currently exhibited on production.
> [PD-1431] Membership should be checked against slugs, not path

- mypartners/views.py
- myreports/views.py
- seo/migrations/0018_member_to_prm_acess.py
- seo/models.py
- universal/decorators.py
- `has_access` decorator which takes a feature name and checks all permission requirements for that feature before displaying the view, otherwise 404ing. 
- data migration that sets all companies' `prm_access` field to whatever their `member` attribute is. 
Basically, the has_access factory maintains a dictionary of feature -> conditions which are checked before showing the  view. `company_has_access` is still around because postajob is using it and I didn't want to rock the boat that much.
> [PD-1142] has_access decorator + data migration

- registration/tests/test_views.py
- registration/views.py
- templates/registration/myjobs/activate.html
Basically, when a user accepts an invitation, they are given a temporary password, but never asked to change it. This corrects that. As for the hackish nature of how I accomplish that, please refer to the associated tickets. It's more of a stop-gap measure, given how much work *really* fixing account activation would be.
> [PD-1442][PD-1440][PD-1443] Makes sure password change is required after invitation accepted

- templates/mypartners/partner_library.html
Re-added ```</i>``` so DOM doesn't italic every element that comes after on Partner Library page. (the entire page pretty much)
> [PD-1543] Partner Library Italics fix

- tasks.py
This should show the full exception that causes failures in the admin, not just the retry.
> Improve task failure logging in admin

- mypartners/tests/test_views.py
The original issue is that the N date format is a django only thing, so I was just Frankensteining the date together. After 3 or 4 failures to do so, I decided to just use a template renderer, which should (and does) render the date exactly as it would be in the template.
> Fixed date issue for mypartners tests once and for all.

- mysearches/helpers.py
- seo/views/search_views.py
For RSS feeds we use Breadbox to come up with title and a description. To figure out the title Breadbox would check the first job in a list and see if the title_slug_value (q parameter) would be equal to the title_slug. If it wasn't the Breadbox would then iterate through the rest of the list to find sometime that was equal.
Problem with that though is that the jobs list being sent to the Breadbox wasn't being sliced properly so in very generic searches like 'sales' breadbox would try to iterate over 620k jobs... Not any more.
> [PD-1631] saved search - Can't create saved searches on network sites with a 'q' parameter

- seo/admin.py
- seo/migrations/0019_auto__del_field_sitetag_is_site_family.py
- seo/migrations/0019_auto__del_field_sitetag_parent__del_field_sitetag_is_site_family.py
- seo/models.py
removed is_site_family boolean from seo->models and admin. also generated migration for the change.
note: whitespace was apparently being removed by default of Atom. messed with the configs and these polluted commits shouldn't be happening any longer... fingers crossed.
> Removal of is_site_family boolean <PD-1606>

- mypartners/forms.py
- mypartners/models.py
- myprofile/models.py
- postajob/models.py
Adds help text to the address forms in profile, post a job, and PRM contacts. Also relabels "Address Label" as "Address Name" and moves it to the bottom of the form to avoid confusion that is occuring with users putting address line 1 in the address label field.
> Add help text and reorder form fields for address forms. PD-1488

- .gitignore
- default_settings.py
- functional_tests/test_mypartners.py
- myjobs/__init__.py
- seo/tests/setup.py
- seo/tests/solr_settings.py
- seo/tests/test_import_jobs.py
- seo/tests/test_sitemap.py
- seo/tests/test_views.py
Some tests were attempting to override HAYSTACK_CONNECTIONS but haystack was still using django settings. In some cases the tests were still passing, leading to the ability to break staging.
HAYSTACK_CONNECTIONS is a dictionary and haystack takes a reference to the dictionary in django settings when it loads.
Test were replacing the dictionary in settings entirely. Haystack was referencing the old dictionary and therefore did not see the new dictionary.
**New:** I put code in `myjobs/__init__.py` to make sure that if we are testing, we permanently stomp the HAYSTACK_CONNECTIONS. We don't ever need a connection to a "real" solr instance in tests, anymore than we need a connection to a real database.
As an additional test I set my local dev_settings.py to point HAYSTACK to a completely …
> Fix solr test  [PD-1644]

- mysearches/models.py
- mysearches/tests/test_models.py
- tasks.py
Tests pass.
This effectively prevents site issues from causing saved searches from becoming disabled. As we no longer care if the page loads, we can close our eyes and hope for the best.
> Remove the disabling/fixing of saved searches <PD-1680>

- myreports/views.py
- static/reporting.167-20.js
- templates/myreports/reports.html
-  the changes to reports/views.py prevent index errors when a report has 0 results
- the changes to static/reporting.js prevent adding of empty values to filter parameters and fix the key used for tags in contact reports
- the template file was just updated to reflect the new filename for reporting.js.
> [PD-1514] Fixed javascript for field parsing in reports.

- mypartners/helpers.py
Not a fan, but it was the fastest way to fix this that worked. Will re-evaluate this functionality and improve tests in PD-1704.
> [PD-1701] Removing attachments no longer causes validation errors.

- myjobs/autoserialize.py
- myjobs/child_dashboard.py
- myjobs/tests/test_autoserialize.py
- myjobs/tests/test_child_dashboard.py
- myjobs/urls.py
Set up for allowing browsers to use either JSON XHR or JSONP. This is a generic mechanism allowing our views to focus on providing data.
Stub in a method which will, in the future, do provide secure information for child sites. The hope is that this new method will replace most of the existing jsonp endpoints.
This is an opt in decorator so existing code should not be affected.
> Opt in to content negotiation with a decorator. [PD-1621]

- mypartners/forms.py
- mypartners/helpers.py
- mypartners/models.py
- mypartners/tests/factories.py
- mypartners/tests/test_helpers.py
- mypartners/tests/test_models.py
- mypartners/tests/test_views.py
- mypartners/widgets.py
The original code (including the quickfix that I worked on yesterday) are erroneous in that for uploaded file removal, the change isn't actually logged. This corrects that by logging the ID of the deleted file on removal, and the filename on insertion. 
I'd have liked to have been consistent, but there are just enough special things that we are doing that enforcing some kind of consistency would have ballooned the complexity of this ticket. For instance, since we represent the attachments to remove as a multiple choice list and the files to add as a multiple file field, their representations are inherently going to be different.
> [PD-1704, PD-1706, PD-1707, PD-1708] Refactor and write tests for form delta functionality

- myreports/tests/test_views.py
Basically, if you set PROJECT to "dseo" and then try to run tests, myreports (at the very least) fails. This at least fixes that for myreports.
> Made sure myreports tests run properly even if local config misconfigured.

- middleware.py
- seo/admin.py
- seo/migrations/0024_auto__remove_configuration_not_found_override.py
- seo/migrations/0025_auto__add_qparameter__add_queryredirect__add_mocparameter__add_locatio.py
- seo/migrations/0025_auto__add_queryredirect__add_queryparameter.py
- seo/models.py
- seo/tests/setup.py
- seo/tests/test_middleware.py
- seo/tests/test_views.py
Adds a QueryRedirect model to allow redirects when the original destination does not 404, query strings optional.
Tests pass.
> Create a QueryRedirect model and the middleware to use it [PD-1715]

- myjobs/child_dashboard.py
- myjobs/cross_site_verify.py
- myjobs/tests/test_child_dashboard.py
- myjobs/tests/test_cross_site_verify.py
Add a decorator that will allow child sites to call secure parent sites to show blocks that should be secure.
Integrate with stubbed child dashboard call.
> Child site checking  [PD-1610]

- seo/admin.py
This duplicates Django's Redirect admin, which we don't test.
Tests pass.
> Add searching and filtering of query redirects [PD-1773]

- seo/helpers.py
- seo/tests/test_views.py
- seo/views/search_views.py
* Company filtering used incorrect method for determining if company exists
* Company filtering now checks the model itself for existence and not a separate function
* Company filtering was returning 404 for companies that had jobs (but did not exist in DB)
* Company filtering now only returns a 404 if company does not exist in DB and has no jobs
* Function call had ambiguous name
* Added comment to function call to prevent future misunderstandings
_Tests updated to verify new logic._
> [PD-1780] Update company search filter logic

- mypartners/migrations/0023_auto__add_outreachworkflowstate.py
- mypartners/models.py
These states will represent the status of email processing. It was determined to not use the existing Status table, as these statuses are of a different kind. See @haliscooper or @fezick  for a run down of how they are different. This is not exposed to the admin intentionally, and the same argument for a lack of tests apply. Tests for this model are bound to be made once the different pieces actually need to talk to each other.
> [PD-1761] Outreach email workflow states

- mypartners/forms.py
- mypartners/models.py
- mysearches/forms.py
- mysearches/tests/test_forms.py
Attempting to use any third-party tools (sphinx, pytest, or even [this code snippet](https://gist.github.com/aspidites/c9ee5e4e4c0ad5dacaa8) results in a circular import error. This PR attempts to do the minimum amount of work possible to resolve the circular import without disrupting the rest of the ecosystem or resorting to hacks.
- I moved `PartnerEmailChoices` from `mypartners.forms` to `mysearches.forms` as `partner_email_choices`
-- it is only used in mysearches.forms
-- I needed to use the User model, which is already imported in `mysearches.forms`, but not `mypartners.forms`
- I moved the logic in `mypartners.models` which attaches a user to a contact on save
-- Unless I misunderstand why we were doing so, we only care if a user with an email exists when modifying contact, as the …
> [PD-1791] Resolve some circular imports

- seo/urls/search_urls.py
- seo/views/search_views.py
- templates/seo/dashboard/blocks/blocks_base.html
- templates/seo/dashboard/blocks/blocks_overview.html
- templates/seo/dashboard/blocks/includes/header.html
- templates/seo/dashboard/dashboard_base.html
Dashboard overview page that features the Page object.
Displays any Page objects associated by company's SeoSites. 
Ex: phillip66.jobs -> phillip66 (company) -> all phillip66.jobs sites (not just canonical site) Pages
For each page there is a preview button and edit button. If there are no pages a message is displayed accordingly.
No real functionality, no buttons or links go anywhere.
> [PD-1667] blocks admin - overview/dashboard page

- seo/admin.py
- seo/migrations/0026_auto__add_field_configuration_doc_type__add_field_configuration_langua.py
- seo/models.py
- templates/seo_base.html
Adds a configurable DOCTYPE and language for seo_base in (site) Configuration model.
DOCTYPE:
* HTML 4.01 Transitional*
* HTML 5
Languages:
* Chinese
* Danish
* English*
* French
* German
* Hindi
* Italian
* Japanese
* Korean
* Portuguese
* Russian
* Spanish
(* is the default choice)
> [PD-1787] [PD-1788] configuration - language specification and doctype specification

- mypartners/migrations/0022_auto__add_field_partner_archived_on__add_field_contactrecord_archived_.py
- mypartners/models.py
- mypartners/tests/test_models.py
- mypartners/tests/test_views.py
I've overridden the manager on these models so the default is to grab non-archived rows. This should take care of every pre-existing use of these particular models, with the exception of saved searches tied to an archived contact/partner. I have an open query on that in the ticket but that shouldn't block review.
I don't think there's a good way of determining if a given partner or communication record is a duplicate of an existing one so I have not implemented anything resembling @aspidites' Contact unarchiving.
Tests pass.
> Add soft delete to partners and communication records [PD-1775][PD-1776]

- mypartners/models.py
If you attempt to filter by tag in reporting, you'll see a 500 error in response (though, it's done via ajax, so nothing may be visually wrong). This corrects that.
> [PD-1814] Added custom manager back to tag so that reports works.

- dseo_urls.py
- myjobs/child_dashboard.py
- seo/cache.py
- seo/context_processors.py
- seo/tests/test_context_processor.py
- static/dashboard.100-10.js
- static/secure-block.168-30.js
- templates/seo_base.html
* Put child dashboard endpoint on microsites in addition to secure.
* Plumb in the rest of the client code for calling the correct microsite.
* Lots of hand testing in a browser to make sure `@cross_site_verify` is doing the right thing in context.
This appears to correctly accept/reject all the situations I can throw at it. I don't have access to ie8 for testing and I haven't covered adding a referer querystring for ie8.
__Note:__ If we haven't discussed it enough, Django's CSRF middleware is incompatible with what we are doing here. Our `@cross_site_verify`, assuming we have correctly implemented it, is sufficient to protect against CSRF according to the OWASP cheat sheet.
> Call child dashboard from microsites [PD-1625]

- myjobs/cross_site_verify.py
- myjobs/tests/test_cross_site_verify.py
Once we started testing IE8 we discovered that there was no need for trusting a referer in a query string as originally expected in PD-1610.
This should result in a more secure CSRF mechanism since we don't deliberately leave a foothold for foreign JavaScript to manipulate our mechanism.
> [PD-1797] Remove qsreferer handling from cross site verify.

- mypartners/models.py
- mypartners/tests/test_models.py
- myreports/tests/test_views.py
Before:
After:
Note that communication records always refers to records which aren't of type "job".
> [PD-1815] Fixed the HTML view for Contact Record Reports

- mypartners/models.py
- mypartners/tests/test_models.py
- mypartners/tests/test_views.py
- mypartners/views.py
This moves the logic in the previously overridden delete methods to a new archive method and modifies the delete view to instead call this new method.
We now filter out contacts/communication records as appropriate when any parent/grandparent contacts/partners have been archived.
> Add docs and improvements to how things are archived [PD-1793]

- seo/breadbox.py
- seo/helpers.py
- seo/tests/setup.py
- seo/tests/test_helpers.py
- seo/tests/test_views.py
Companies listed in jobs may or may not exist in our database. When the company header function is called with a company slug that does not exist in our DB, try to pull the title from the job. If that fails, return the company slug as a last resort
1. Added handling to attempt to match company slug to a given job and to default to provided company slug if job is unavailable.
2. Created new tests for function to retrieve company title
3. Created new test base class (pulled from test_views.FallbackTestCase) that contains a configured site and a job.
> [PD-1782] Fix None Returns for Company Titles

- dseo_urls.py
- myblocks/tests/factories.py
- myjobs/urls.py
- postajob/tests/test_views.py
- seo/admin.py
- universal/decorators.py
- universal/helpers.py
In order to set posting_access on a company without first needing to get write access to the database, I need to enable it in admin. This will also prevent member services from needing developer intervention in order to set up postajob access in the future. 
Update; Added a regression test for login redirects and made all postajob tests use seo settings.
> [PD-1808][PD-1812] Added posting_access to admin and updated how we redirect to login

- mypartners/tests/test_views.py
- myreports/tests/test_views.py
This new test verifies that archived things are filtered out when creating a report.
Writing the tests to verify this took longer than verifying by hand due to factory boy oddities.
> Add test for reporting archive filtering [PD-1778]

- seo/helpers.py
- seo/views/search_views.py
Simply rename get_company_data to get_company_thumbnail as the former name is misleading.
> Rename function for retrieving company thumbnail

- mypartners/tests/factories.py
- mypartners/tests/test_views.py
- myreports/tests/test_views.py
Fixing all factories is a bigger beast than I thought, so I'll leave it at an app-by-app basis as issues crop up.
This can still result in odd relationships as demonstrated here but this is an issue that can be fixed through correct use of the factory.
```
assert Partner.objects.count() == 1
contact = Contact.objects.get(pk=...)
record = ContactRecordFactory(contact=contact)
assert Partner.objects.count() == 2
assert contact.partner != record.partner
```
> Improve mypartners factories [PD-1863]

- myreports/views.py
Results:
If you go to production now and try to create a CSV for a communication record report, you'll see that the "archived on" field is present, when it shouldn't be. This corrects that. I basically promoted that column to the common blacklist.
> [PD-1869] Added archived_on to the global blacklist for reporting.

- myjobs/migrations/0007_create_admin_roles.py
- myjobs/models.py
- myjobs/tests/factories.py
- myjobs/tests/test_data_migrations.py
- myjobs/tests/test_models.py
*This depends on #1823 , which in turn depends on #1820.*
This makes it so that creating a new activity automatically adds that activity to the "Role Admin" role. In my tests, it takes ~5 seconds to add a new activity to ~30,000 "Role Admin" roles (in 4 queries).
~~The actual differences are [here](https://github.com/DirectEmployers/MyJobs/compare/activity-migration...pd-1850?expand=1)~~
*update:* I changed Role Admin -> Admin. I didn't create another migration since this hasn't hit production, and I didn't want to run two nearly identical data migrations with the second undoing the work of the first.
The other migration wouldn't work on QC because the max packet size there is 4M vs 16M locally. With @mklauber 's guidance, I decided to batch the bulk create at 450 rows.
> [PD-1850] Automatically add activities to Admin roles.

- mypartners/migrations/0027_auto__chg_field_outreachemaildomain_domain__add_unique_outreachemaildo.py
- mypartners/models.py
@haliscooper  discovered that `URLField`s require a scheme to be passed in (eg. "http://"), which is unacceptable. Changed this back to a char field with 200 char max.
> [PD-1748] Changed domain back to a charfield.

- registration/forms.py
- static/my.jobs.169-26.css
- templates/base.html
In reviewing #1835, I made a few comments which I didn't think needed to hold back that PR. This PR addresses those points. Namely:
- On the registration form, the placeholder's seemed redundant. According to @lemniscate613 
- On saved searches, despite each job listing having its own link, there was no hover effects to indicate that, which to me felt like clicking anywhere in the table would go to the same link
There isn't a ticket for this as it very well be that no one else finds these points troublesome.
> Registration redesign tweak

- mysearches/migrations/0013_auto__del_field_savedsearch_last_modified__add_field_partnersavedsearc.py
MySearches migration was set to rename a column rather than delete/add it on another table.
> Change broken mysearches migration

- redirect/tests/test_views.py
- redirect_settings.py
Test on QC:
Test on redirect-middleware (not sure why this is a 301 but it resolves in a browser):
Once any issues are dealt with and we decide on the final change set, I'll open PRs for staging/master.
Tests  pass with the exception of those involving imports.
> Stop using seo/secure middleware for redirect [PD-1560]

- seo/models.py
- seo/tests/test_models.py
A previous PR added the admin role to all existing companies (but didn't assign them). This one makes sure that newly created companies have the admin role.
@JLMcLaugh , should this be a hotfix to prevent the week between where admin roles are automatically created and new companies are made without this being in place?
Alternatively, we can fake that migration backward and re-run it to catch up any stragglers (faking all the way forward after that).
> [PD-1906] Admin role for new companies

- mydashboard/views.py
- myemails/models.py
- myjobs/templatetags/common_tags.py
- myjobs/tests/factories.py
- myjobs/tests/test_views.py
- postajob/tests/test_views.py
- postajob/urls.py
- postajob/views.py
- seo/models.py
- seo/tests/test_models.py
- templates/mydashboard/profile.html
- universal/helpers.py
I am not intending here to completely remove the CompanyUser model, but rather make its inclusion redundant.
With the introduction of roles, there is no need for a company user table, as a user can be tied to a company merely by seeing if that user is assigned a role which belongs to the company in question. That said, as the activities system isn't deployed, it would be unwise to simply remove any use of the company user model. Instead, what this PR does is ensure that when debugging is enabled, roles are checked and when debugging is disabled, the original behavior which relies upon company users is preserved.
This is based off of #1854. The core changes are [here](https://github.com/DirectEmployers/MyJobs/compare/pd-1906...pd-1913?expand=1).
- There are a few things done with …
> [PD-1913, PD-1914] Deprecate the use of CompanyUser

- registration/migrations/0003_auto__chg_field_activationprofile_sent.py
- registration/models.py
While looking into upgrading Django, I ran into a wall. SOP is to either delete the migrations directory or rename it to south_migrations and then let Django recreate its own initial migrations. It will see that nothing has been changed when running migrations and mark them as already applied.
That's all well and good but ActivationProfile.sent has both auto_now_add and a default value. This causes Django's migration generation to fail because that's invalid.
If we're ever going to upgrade, it looks like we'll need to fix it in South first.
> Remove invalid options from ActivationProfile.sent [PD-1548]

- myemails/models.py
- myjobs/templatetags/common_tags.py
- mypartners/migrations/0029_auto__chg_field_outreachemailaddress_email__add_unique_outreachemailad.py
- mypartners/models.py
- mypartners/tests/test_views.py
- mypartners/views.py
- myreports/decorators.py
- templates/mypartners/nonuseroutreach/outreach_inbox_management.html
When originally designed, the Outreach Email Address model was created to store an email address (feelgoodinc@gmail.com). Instead, we need to only store a prefix (feelgoodinc) and append '@my.jobs' or whichever domain we decide on to the end of that prefix. 
This PR covers the migration to fix the model as well as the custom handling to ensure values entered into the model field do not contain special characters.
* Change email field to CharField on Outreach Email Address model
* Add custom regex validator to ensure we are receiving usable input
* Update forms to display proper guidance for inputs
This PR follows PD-1757. To view the changes specific to this PR, compare here: http://git.io/v8sBf
> [PD-1912] modify outreach email handling

- myprofile/tests/test_views.py
- templates/myprofile/modules/summary.html
We only allow one summary but the template had been copy/pasted from another module. As such, we weren't grabbing the id and module type of the object being edited.
Tests failed locally but that may be due to me having to extricate myself from a Django 1.8 upgrade before doing this.
> Fix summary template for myprofile [PD-1947]

- myjobs/views.py
- templates/includes/topbar-new.html
- templates/includes/topbar.html
This is a hotfix for QC, not production.
> hide user management link in topbar for staff only, same for API endpoints

- myblocks/admin.py
- myblocks/migrations/0013_auto__add_allowedblockpaths__add_path.py
- myblocks/models.py
- myblocks/tests/test_secure_blocks.py
- myblocks/views.py
Admin listing screen with one block set up:
Edit screen. Add screen will be this but with blank values. You can add as many or as few allowed paths as desired. The one pictured would be allowed anywhere as I wanted to support a gradual transition and chose the default of "no paths" to be "allow".
Rerunning tests after most recent commit.
> Add allowed paths to secure blocks [PD-1613]

- deploy/settings.myjobs_staging.py
Rationale - QC is our testbed for new features, staging is meant to mirror production. This will also ensure that features implemented in QC don't badly interact with production.
> Roles should be enabled on QC but not Stating.

- myjobs/decorators.py
- myjobs/models.py
- myjobs/templatetags/common_tags.py
- myjobs/tests/setup.py
- myjobs/tests/test_activities.py
- myjobs/tests/test_decorators.py
- myjobs/tests/test_models.py
- myjobs/tests/test_views.py
- mypartners/tests/test_activities.py
- myreports/tests/setup.py
- myreports/tests/test_activities.py
- seo/models.py
- seo/tests/test_models.py
- templates/includes/topbar-new.html
- templates/includes/topbar.html
- Added a few more convenience methods and refactored
- user management was missing from mobile views
- user management only shows up when role are enabled
- prm only shows up when prm is enabled
- if no features are enabled, Employers is disabled all together
- wrote tests for new template tag that I needed to support this
- wrote tests for new convenience methods
One complaint that I've heard often is that PRs aren't reviewed because people are either not familiar with the code or the amount of changes is daunting. I've annotated all my changes as an experiment to see if it hinders or improves the process. Please give feedback (negative or positive, but always constructive) with respect to this aspect. Note that the annotations are cleaner if you read them inline under "File changes"' …
> Fix Topbar with respect to Roles

- transform.py
The validFrom date of one of the jobs falls during the daylight savings
time changeover.  django by default does not guess one way or the other,
so we have to explcitly do so beforehand.
> Fix for ADT-252.

- myjobs/decorators.py
- myjobs/models.py
- myjobs/templatetags/common_tags.py
- myjobs/tests/setup.py
- myjobs/tests/test_activities.py
- myjobs/tests/test_decorators.py
- myjobs/tests/test_models.py
- myjobs/tests/test_views.py
- myjobs/views.py
- mypartners/tests/test_activities.py
- myreports/tests/setup.py
- myreports/tests/test_activities.py
- myreports/views.py
- seo/models.py
- seo/tests/test_models.py
- templates/includes/topbar-new.html
- templates/includes/topbar.html
`staff_member_required` redirects to django admin, which is only desireable on seo. As such, I switched those occurrences in myjobs to my restrict_to_staff decorator. I also wrapped the rest of the unreleased reporting api's in the staff decorator.
This builds on top of #1900, so the only real changes are [these](https://github.com/DirectEmployers/MyJobs/compare/fix-topbar...update-staff-check?expand=1).
> Update staff check

- gulp/src/reporting/spec/reportEngineSpec.js
Now that we know Jenkins will fail a build on a bad gulp result, remove this test.
> Remove build killer test now that Jenkins works.

- myjobs/models.py
- myjobs/tests/test_models.py
- templates/registration/invitation_email.html
To allow for invites to be sent from anywhere in a simple fashion, I added a `send_invite` method to `User`.
-  call `./manage.py shell`
- import `User` from `myjobs.models` and `Company` from `seo.models`
- assign a user and a compnay for which that user has a role (or assign a role to that user from that company
- call `user.send_invite` with an arbitrary email address (that you own), the company retrieved above, and either `True` if `settings.ROLES_ENABLED` is set to `False` or a valid role name
- You should receive an invitation email, and that user should now exist, assigned the appropriate role (or as a company user if roles aren't enabled)
- [PD-1972](https://directemployersfoundation.atlassian.net/browse/PD-1972) At the moment, the `Invitation` model is tied to saved search due to …
> [PD-1974] Wrote helper method to invite a user.

- gulp/gulpfile.js
This was causing gulp to not fail on certain webpack specific errors.
> Fix so build fails on webpack errors.

- mypartners/models.py
- mypartners/tests/test_activities.py
- mypartners/tests/test_views.py
- mypartners/views.py
Run tests. They pass.
If you want to test the old behavior, you'll have to copy the `test_attachments_attach` test from mypartners/tests/test_views.py to QC and run it. It should fail because there are no PRMAttachments.
> Stop trying to shadow the "partner" property [PD-1976]

- seo/migrations/0030_unicode_custom_pages.py
- seo/tests/setup.py
- seo/tests/test_views.py
**HOTFIX**
This converts the CustomPage table in mysql to utf-8 so that unicode can be added to the content of custom pages. 
There is no backward migration because we shouldn't have a reason to convert the table back to swedish_ci (I vaguely remember @JLMcLaugh telling me to not worry about a backward migration the last time I had to do this). 
I've included screenshots in the jira ticket for the curious.
> [PD-2018] Unicode on custom pages

- mysearches/models.py
- postajob/models.py
**bugfix**
We have 19 cyclic imports. A common workaround that we have used (that I don't like) is to use local imports within a function. I used that work around here because a) qc is broken right **now**, so I wanted this fixed sooner than later, and b) we already do similar within the same module for the same reason (using stuff from import_jobs). @mklauber had mentioned refactoring import_jobs.py, tasks.py, and xmlparse.py to take care cyclic imports in a more satisfactory way.
> fixed cyclic imports

- doc/source/conf.py
- doc/source/developers/postajob/00_quickstart.rst
- doc/source/developers/postajob/overview.rst
- doc/source/developers/styleguides/documentation.rst
- doc/source/developers/styleguides/javascript.rst
- doc/source/developers/styleguides/programming.rst
- doc/source/faq.rst
- moved quickstart into it's own document for consistency, named 00_* to enforce order in toc since we use globs
- re-added import of settings as things broke for me otherwise
- removed contents from all pages as the current theme already adds navigation to sections on the left sidebar
> Documentation cleanup

- mysearches/tests/local/careers.html
- mysearches/tests/local/jobs.html
- templates/seo_base.html
Basically we were loading extra data that wasn't being used. No new tests because this is a template-only change. The only way I can think of to test what this is doing is to render every template and ensure that the json file is only used on the military template, but that seems pointless and would necessitate that any new template would require an update of that test.
> Removed military stuff from non-military pages.

- postajob/forms.py
- postajob/tests/test_views.py
Basically, my last fix allowed no locations to be added, when instead it should have enforced that at least one location was required. I'm confused as one of the tests seems to be doing that already....
> [PD-939] Fixed regression with job form

- myjobs/models.py
- mysearches/forms.py
- mysearches/tests/test_models.py
- registration/forms.py
- registration/models.py
- registration/tests/test_models.py
- registration/tests/test_views.py
- seo/models.py
- templates/registration/invitation_email.html
At the moment, we send send specific invitation emails depending on whether or not the invitation is associated with a saved search or a group. This PR abstracts that functionality from the template and moves it to the backend, in addition to allowing for a custom reason to be provided in the email. 
- `registration.models.Invitation.send` now takes an optional `reason` parameter
- `myjobs.models.User.send_invite` now takes an optional `reason` parameter
- `registration.models.Invitation` no longer automatically sends an email on creation
- Conditional messages inside of the invitation email template has been moved to the `send` method.
- New tests to cover each of these different template use cases. Note that I didn't give the tests a custom failure message as the default was more …
> [PD-1856] Custom invitation reasons

- templates/seo/military.html
A previous pr removed this static file from seo_base. Apparently it was never in the military template. I'm not sure where it's supposed to go, so I assume this is sufficient. 
@tdphillips, mind double checking my use of `{% static %}`. Never used it before, so I'm not 100% I've gotten the syntax correct.
> [PD-2017] Added military_family-loc.json to military template.

- dk2/dockerdev.sh
- myjobs/cross_site_verify.py
- seo/cache.py
- seo/context_processors.py
- templates/seo_base.html
This is a small PR.
I had not intended on lumping the changes to Docker with the changes to secure blocks, but it happened that way.
Fixed/Add functions restartsecure and restartmicrosites. These functions will stop and remove any running containers for either and subsequently restart their respective container.
Modified the logic for determining the url of the parent site to no longer affix/remove the qc/staging prefix, but rather modify https/http based on the environment. This is due to the fact that QC and Staging do not use HTTPS.
I also added the exception/authentication error from cross site verify to the response. I may remove this in a later PR, but it will help as I attempt to get cross site verify running on QC.
> Misc Changes to Docker, Secure Blocks

- myjobs/cross_site_verify.py
- seo/cache.py
As I was working through the issues with making the QC servers communicate, I realized that qc.secure.my.jobs is a SeoSite of its own rather than just using the regular secure.my.jobs SeoSite. Due to this, I modified my logic to use the main (secure.my.jobs) SeoSite when doing cross-site verification. This is so that production database refreshes will not constantly break parent-child relationships in cross site logic.
> Another prefix tweak for saved search lists

- gulp/README.md
- gulp/npm-shrinkwrap.json
- gulp/package.json
`npm shrinkwrap` takes a snapshot of a working node_modules directory tree and assures that the same package versions will be used in production and other developers' machines.
My reading of the npm docs suggests that no changes are needed in deployment. Just the presence of the `npm-shrinkwrap.json` file is enough to change the behavior of `npm install`. With the file present it will simply reproduce the shrinkwrap.
If you are a developer and need to change the dependencies see the new `README.md` file in `gulp/`.
I suggest that we walk though all the current React apps.
Diffs within `npm-shrinkwrap.json` should help us gauge the impact of future JS dependency changes.
> [PD-2051]  Pin NPM Dependencies

- static/custom.css
- static/topbar.directseo.165-10.css
- static/topbar.myjobs.165-10.css
- templates/includes/topbar-new.html
Overview
=========
New projects (like Manage Users) use Bootstrap 3, but this broke the toolbar on mobile.
This PR fixes the "[hamburger](https://en.wikipedia.org/wiki/Hamburger_button)" button:
And the expanded view:
Review
=========
* Run `gulp build`
* Visit https://local/manage-users
* Make browser smaller
Home
=========
It's tiny.
> [PD-2010, PD-2011, PD-2012] Fix topbar-new mobile issues, which uses Bootstrap3

- templates/home_page/CS_TEST_home_page_listing.html
- templates/job_listing.html
I am creating a new home page template for the purposes of testing and developing secure blocks widgets. This template will not be tied to any existing configurations, but will be a copy of the home_page_listing.html home page. This allows testing of secure blocks widgets without including non-functional hooks on existing templates.
The new template contains hooks for both saved_search_list and saved_search, but only saved_search_list exists in QC. To verify that the list hook works, change the template in my.jobs configuration to use CS_TEST_home_page_listing.html .. If you have not done so already, do the steps below as well
NOTE: This currently only works for Docker environments due to limitations of cross-site functionality on regular localhost. Outside of docker, if you can setup …
> Create Home Page Template for Cross Site

- gulp/src/manageusers/main.jsx
- gulp/src/nonuseroutreach/components/Container.jsx
The dynamic companyName feature worked, but JSLint was pitching a fit:
```
"companyName" is not defined
```
> fix jslint error, companyName is coming in from the base template

- myjobs/api.py
- myjobs/tests/test_api.py
With a bit of hand-testing, I determined that some Django magic happens earlier in request processing which unquotes the thing we're unquoting. That results in "%2523" getting unquoted all the way to "#" rather than stopping at "%23". Since octothorpes have meaning as far as urls go, this is bad.
> Stop double-unquoting [PD-2060]

- gulp/gulpfile.js
The bootstrap-react package was trying to load its own version of react and caused an error.
> Fix bug with webpack and bootstrap-react

- myjobs/tests/test_manage_users.py
- myjobs/views.py
The /manage-users/api/roles/ API returns, among other things, available and assigned activities. For each, the front-end needs the name and description, but it also needs app_access. This enables us to break up the activities by app for use in the accordion:
Run tests:
`dkm test myjobs.tests.test_manage_users`
Visit locally:
https://secure.my.jobs/manage-users/#/role/add?action=Add
> Return app_access in /manage-users/api/roles/ API

- mypartners/tests/test_views.py
- requirements.txt
requests doesn't use urllib. Newer versions can handle SNI just fine.
> Upgrade requests

- myjobs/tests/test_manage_users.py
- myjobs/views.py
This PR fixes a bug where, if a user belonged to multiple companies, all of their roles would display in various points in the UI. For example:
Run Django tests: `dkm test myjobs.tests.test_manage_users`
Build JS and start server:
`
dkgg build
dk runsecure
`
> Constrain roles by current company

- myjobs/views.py
Previously, if you successfully edited a preexisting user, it would tell you such. This PR redirects you back to the users page.
> User Management - redirect to users page

- myjobs/models.py
- myjobs/views.py
This PR fixes a bug present with adding/editing a user with multiple roles.
When a user has multiple roles this if statement should catch it and update the user accordingly: https://github.com/DirectEmployers/MyJobs/blob/d20c487862ebce381284a15c58a754a6f35aa870/myjobs/models.py#L768 However, I was overwriting the `role_name` variable and making into a string. The program flow never got past this if statement.
This PR depends on https://github.com/DirectEmployers/MyJobs/pull/2038
As such, this PR only has one unique change: https://github.com/DirectEmployers/MyJobs/commit/bd4c4703b1afa231a3c87b41621c3de0da7409f5
> User Management - update invite_user() to handle multiple roles

- myjobs/admin.py
- myjobs/models.py
- myjobs/tests/test_views.py
This search would normally be empty.
9001. Steps to test:
15. Open admin
300. Click "Users"
2. Search for a secondary email
65535. ...
1337. Profit
> Allow filtering users on secondary email [PD-2053]

- deploy/settings.myjobs_staging.py
The settings files on staging were overriding the default settings and disabling roles.
> Enabled roles on myjobs staging

- gulp/npm-shrinkwrap.json
- gulp/package.json
Add lodash as an available dependency.
Use lodash 3.x "compat" as this supports ancient browsers including IE8. Lodash 4.0 is IE9+.
Also, less was included in shrinkwrap but somehow got merged out of package.json. So I'm restoring it.
> [PD-2101] Add lodash

- myjobs/models.py
- templates/registration/invitation_email.html
This adds a link to the invitation email to PRM when a user gets sufficient privileges to at least click that link.
This email template that I worked so hard to remove  conditional logic from is starting to regress back to its original form, which makes me sad.
> [PD-2122] Add a link to PRM in invitation email [hotfix]

- templates/includes/topbar-new.html
- templates/includes/topbar.html
We were hiding the User Management link in the toolbar, but now that it's live this restriction is no longer needed.
The other hotfix for this issue didn't include all instances of the restriction: https://github.com/DirectEmployers/MyJobs/pull/2067
> Hotfix remove staff restriction in toolbar for user management link

- registration/tests/test_models.py
- registration/tests/test_views.py
- templates/registration/invitation_email.html
This is NOT identical or equivalent to what I opened against QC. This hard-codes a link to PRM. If a user is assigned to a role that doesn't include the "read partner" activity, this link will blow up in their face, resulting in a 403.
> [PD-2122] Hard coded link to PRM in invitation email [hotfix]

- gulp/src/common/ui/Loading.jsx
- gulp/src/common/ui/SearchInput.js
- gulp/src/reporting/DynamicReportApp.js
- gulp/src/reporting/WizardRouter.jsx
- gulp/src/reporting/main.js
- gulp/src/reporting/reportEngine.js
- gulp/src/reporting/spec/reportEngineSpec.js
- gulp/src/reporting/wizard/LinkRow.js
- gulp/src/reporting/wizard/WizardPageDataTypes.js
- gulp/src/reporting/wizard/WizardPageFilter.js
- gulp/src/reporting/wizard/WizardPagePresentationTypes.js
- gulp/src/reporting/wizard/WizardPageReportTypes.js
- gulp/src/reporting/wizard/WizardPageReportingTypes.js
- myjobs/api.py
- myreports/urls.py
- templates/myreports/dynamicreports.html
Replace the ad-hoc routing with no history support in DynamicReportApp with react-router.
This PR may be easier to review commit by commit. The commit "Refactor reporting wizard" touches a lot of files. The other commits are small.
The refactor does a couple of things:
* Make each page responsible for loading its own data.
* Adds the Router.
* ReportEngine's interface for notifying a react component of newly created reports moved to ReportFinder. This simplified routing.
> [PD-2086]  History support

- mysearches/models.py
When being invited for saved searches, You'll now get a link for that saved search:
Similar case for PRM, but that's been merged already.
> [PD-1972] Context-Specific Link

- gulp/src/reporting/wizard/WizardPageFilter.js
- myreports/presentation/__init__.py
- myreports/presentation/base.py
- myreports/presentation/csv.py
- myreports/presentation/disposition.py
- myreports/presentation/jsonpass.py
- myreports/presentation/xlsx.py
- myreports/tests/setup.py
- myreports/tests/test_models.py
- myreports/tests/test_presentations.py
- myreports/tests/test_views.py
- myreports/views.py
- requirements.txt
~~Guidance: see comments inline.~~ Thanks.
Here are some starting points:
* `myreports/presentation/base.py` has documentation.
* Note the library being used to write Excel spreadsheets. `requirements.txt`
* Previously report names were unused by the API. This will be addressed in PD-1952. With this change the backend uses the name field and the UI sets a hard coded name. `WizardPageFilter.js`
> [PD-1384]  presentation layer

- myjobs/models.py
- myjobs/tests/test_models.py
- myjobs/views.py
- seo/admin.py
- seo/forms/admin_forms.py
- seo/models.py
- seo/tests/test_models.py
This PR adds an "Admin Email" widget to the company admin, which should only exist for companies who haven't invited anyone to be an Admin. 
Because of the way that invitations are laid out at the moment, there is no way to actually prove that the invitation being referred to was due to someone being invited as an Admin. However:
- saved searches cant be cdreated without PRM access
- PRM access can't be granted without role permissions
- Role permissions can only be granted by an admin
That's roughly the logic/assumption this is working on. If the above ever turns out not to be consistently the case, we'd need to add another field to a model somewhere to discern how various invitations are being created.
To test, just go to django admin, and click on a company. It should be the case that …
> [PD-2135] Initial Invitations

- templates/registration/invitation_email.html
link_text has a \<p\> tag, so this needs to be moved outside of the other \<p\> tags.
> paragraph inside a paragraph is not what we want.

- doc/source/developers/index.rst
This was generating a warning, which is of course treated as an error.
> Added deployment checklist to toc.

- templates/seo_base.html
I originally had the site object inserted directly into the URL instead of the domain of the site object. This corrects that.
> Fix object reference

- templates/base-react.html
- templates/base.html
This was never exactly right, but this line was probably failing harmlessly or after the secure.my.jobs-specific beacon was sent. Now, it looks like there are exceptions that keep that from happening, and GA is not tracking the secure.my.jobs beacon.
The next step should be moving from ga.js to analytics.js.
> Call correct _trackPageview method on secureMyJobs tracker [PD-2184]

- default_settings.py
We should actually route this task.  Otherwise, it goes into the ether, and is never run.
> ST-2279 Expire Jobs Successfully.

- .gitignore
- default_settings.py
- myjobs/admin.py
- mypartners/admin.py
- requirements.txt
- seo/admin.py
- seo/forms/admin_forms.py
- seo/lookups.py
- seo/models.py
Same as the Last time I posted this a week ago, except that I've limited results to 10 and use istartswith instead of icontains.
See #2107 for more details.
Test by seeing that the forms which had `ForeignKeyAutoCompleteField`s do in fact still autocomplete.
> [PD-2167] Remove django_extensions 

- .gitignore
- default_settings.py
- dseo_urls.py
- myjobs/admin.py
- myjobs/forms.py
- myjobs_urls.py
- mypartners/admin.py
- requirements.txt
- seo/admin.py
- seo/forms/admin_forms.py
- seo/lookups.py
The widgets in django_extensions and django-ajax-selects are different enough that replacing one with the other was disruptive to staff's work flow. Once this is reverted, I'm closing the ticket as wontfix.
> [PD-2167] Re-introduce Django-Extensions

- myjobs/cross_site_verify.py
In my most recent PR, I attempted to remove specific handling for QC/Staging from the secure blocks logic.
Well.. I missed a spot.
This is the removal of the -REST- of the logic.
> Removal of test prefix trim

- default_settings.py
- deploy/settings.jenkins-single-test.py
- deploy/settings.jenkins.py
- deploy/settings.myjobs_qc.py
- doc/source/faq.rst
- mydashboard/views.py
- myemails/models.py
- myjobs/decorators.py
- myjobs/models.py
- myjobs/templatetags/common_tags.py
- myjobs/tests/setup.py
- myjobs/tests/test_models.py
- mypartners/tests/test_api.py
- mypartners/views.py
- seo/models.py
- seo/tests/test_models.py
- universal/decorators.py
This ticket gets rid of the need to constantly check for "ROLES_ENABLED". It only looks this big because I kept it in sync with my other work which removes the need for CompanyUser in postajob.
[Here's the real difference](https://github.com/DirectEmployers/MyJobs/compare/pd-2116...remove-roles-enabled?expand=1)
I also went ahead and fixed a bug caused by my last pr which would cause an error if you hit a mydashboard view while not logged in. We don't actually use the app, but I figured the behavior might happen elsewhere. Thanks @tdphillips
> Remove roles enabled

- gulp/npm-shrinkwrap.json
- gulp/package.json
- gulp/src/common/myjobs-api.js
- gulp/src/manageusers/Role.jsx
- gulp/src/manageusers/User.jsx
- gulp/src/manageusers/main.jsx
- gulp/src/reporting/api.js
- gulp/src/reporting/main.js
* Create a common API class useful from any app.
* Use it from Manage Users and Reporting.
* Remove use of `/* global $ */` in Manage Users.
We depend on a common behavior in jQuery implemented by it's param function starting in jQuery 1.4.
http://api.jquery.com/jquery.param/
This affects sending arrays and objects as form data. jQuery renames array keys to `field[]` and object keys to `field[key]`.
Using this I can use the same code for all browsers.
> [PD-2212]  Remove jQuery from User Management

- seo/admin.py
- seo/models.py
Not much to say really. Removed the unicode representation of site packages since we apparently only want that formatting for the seosite admin itself, not every time we are showing seosites.
> [PD-2224] Undid unicode representation of seo sites.

- myblocks/models.py
- myjobs/views.py
- templates/includes/topbar-new.html
- templates/includes/topbar.html
- templates/myblocks/blocks/secure_blocks/tools.html
The microsite name/url displayed in the topbar was entirely based off of a cookie. The reason for this was to display a link back to the microsite that a user was last microsite visited, even if they are on a different microsite at the time of the display.
The new logic first determines if they are on a valid Microsite. If they are, a context variable will be added for the link/text. If not, the topbar will use the cookie.
This PR affects topbar, tools widget (secure blocks topbar) and react topbar. Each should be tested.
- Navigate to a microsite  (ex. newhampshire.jobs)
- Navigate to another microsite (ex. vermont.jobs)
- Verify that the topbar displays the name of the microsite you are CURRENTLY on, not the previous
- Navigate to secure.my.jobs
- Verify that the topbar displays the …
> [PD-2230] Fix Microsites Name Display for Topbar

- seo/forms/admin_forms.py
- seo/models.py
- seo/tests/test_models.py
Visit /admin for a company. If that company doesn't have anyone assigned the "Admin" role, you should see an "Admin email" field that you can use to assign that role. If an admin already exists, you should instead see a message saying that the company already has an admin.
> [PD-2259] Tell staff that an admin is assigned rather than that invitations were sent

- myblocks/views.py
- myjobs/views.py
- mypartners/views.py
- myreports/decorators.py
- myreports/views.py
- mysearches/views.py
- seo/views/search_views.py
- universal/decorators.py
While messing with postajob I noticed we had some mockups that David did some time before he left that were exposed. This PR restricts them to staff.
To test, visit `/dashboard` while logged into  a local running microsite. If you demote yourself from staff to normal user, you should get 404s. As staff, you should see the mockups. An example of this in production is at http://www.my.jobs/dashboard
What you should *not* see, unless you are staff:
> [PD_2252] Moved restrict_to_staff to universal and hid a few mockup views.

- registration/tests/test_views.py
- registration/views.py
Log out of your account
Go to /accounts/password/reset/
Note the redirect :sob: 
Do the same thing
Note the lack of a redirect :boom: 
Log out of your account
Walk away for some amount of time greater than three seconds
Come back
Go to /accounts/password/reset/
Note the lack of a redirect :boom:
> Add timeout to loggedout cookie [PD-2283]

- seo/breadbox.py
- seo/tests/test_breadbox.py
The unit test and original Jira ticket explain it pretty well. Basically, we were adding an href that was missing a '/'. This PR makes sure it's there.
> [PD-2258] Added missing slash to facet url

- myjobs/templatetags/common_tags.py
If you remove yourself from all companies and refresh (secure.my.jobs), you'll see an empty menu item. This caused by an empty <li> element being rendered for the Employers menu (since you won't have one, it's not populated with submenus). Nothing is 'broken' because of it, but it's still annoying to look at. This PR removes that annoyance.
> Made it so that we weren't rendering empty menu items

- doc/source/developers/postajob/setup.rst
- myjobs/migrations/0017_invoice_activities.py
- postajob/templatetags/postajob_tags.py
- postajob/views.py
- templates/postajob/includes/postajob_navigation.html
Addressed @fezick's feedback during QC, and wrapped a few other views which weren't part of the 6 use cases. Intentionally left undocumented as they didn't seem important, so keeping them undocumented may give more flexibility with respect to removing them*. In particular:
- there were a couple of invoice specific views that weren't wrapped
- the view for reordering groupings wasn't wrapped
- a couple of views had 'admin' equivalents which further obscure the definition of "company" at any given time
- being a use for multiple companies who have purchased products won't cause duplicate entries in the purchased jobs page
* Though, it's not end user documentation.
> [PD-2237] Postajob corrections after feedback

- myblocks/models.py
- myblocks/tests/test_models.py
We were caching rendered login pages, including the csrf tokens on them. This is why everyone who was checking the page at the same time had the same token.
Per a conversation with @fezick, we're removing caching until we determine what we actually want to do.
If you wish to manually verify:
Using a microsite with a login block (this can be done in production):
Log in.
Log out.
Try logging back in -> error.
Using this branch:
Create a login page.
Mess with settings as necessary to mimic a microsite.
You're now able to log in and out to your heart's content.
> Remove caching from views using myblocks [PD-2268]

- doc/source/developers/postajob/setup.rst
- postajob/helpers.py
- postajob/tests/test_models.py
This just adds two convenience functions to facilitate setting up postajobs for a company. There is no management command, and I will not be integrating this into django admin. You should be able to call either function with appropriate parameters and get expected results (see docstrings for what's expected).
*update* I updated the setup guide as well with both reference to these new functions as well as a couple of minor things.
> [PD-2290] Automate postajob

- postajob/helpers.py
- postajob/tests/test_models.py
When creating the login block, i wasn't assigning a default template. Admin seems to do some funkiness to accomplish this. I didn't look at how it was done there, but did go ahead and make sure the default template was assigned when generating login blocks as a result of ruining `enable_marketplace`. 
~~Tomorrow morning I'll write a regression test to ensure that the command creates a login block with  a proper template.~~ (Done)
> Assign a template when creating a login block.

- templates/base-react.html
- templates/myjobs/request_company_access.html
I forgot that I was using the react-base template for the company access request page (so that I could have access to bootstrap 3). Thus, attempting to visit qc.secure.my.jobs/request-company-access results in a blank page. This fixes that.
On this branch, you should see that visiting /request-company-access actually shows up now. I also added a proper header and breadcrumb div. Furthermore, the real react apps should still function (/reports/view/dynamicreporting, /manage-users, /prm/view/nonuseroutreach). No tests written  as it's all template work.
> [PD-2147] Re-enabled content block for request company access request page.

- default_settings.py
- dseo_urls.py
- myjobs_urls.py
- postajob/forms.py
- postajob/urls.py
- postajob/views.py
- seo/lookups.py
- templates/base-react.html
- templates/myjobs/request_company_access.html
- templates/postajob/enable_feature.html
For most applications, it's easy enough to simply make sure the application is added to the list of enabled app-level access in the company admin. For postajob, things are a bit more involved. In the past, I've written a pair of functions meant to automate the simplest case for enabling posting or marketplace. This work takes it another level by exposing the functionality of those functions as forms. They can be found at /posting/enable and /posting/admin/enable, respectively. They aren't centrally located or in the admin as to make them less tempting to abuse. Once there is a staff-facing SPA, they'll probably be incorporated (in function, not form...no pun intended).
> [PD-2314] Feature Enable Forms

- seo/forms/admin_forms.py
If you view a business unit in the django admin, you'll see that the import field probably has two sites listed. If you do the same with this branch, you'll see that all sites are listed, which is desired behavior.
It's really a single line change, but my editor went ahead and stripped trailing whitespace.
> [PD-2315] Changed the FSM endpoint so that all sites are visible.

- myreports/datasources/comm_records.py
The fact that items are  truncated is a known issue I'm intentionally ignoring.
> [PD-2326] Made contact type choices human-readable

- templates/mypartners/includes/partner_sidebar.html
This form is used on both the initial PRM view that allows you to search your current partners as well as the view that allows searching for new OFCCP partners.
> Autofocus on keyword field of partner search forms [PD-1487]

- gulp/src/common/states.js
- gulp/src/reporting/SetUpReport.jsx
- gulp/src/reporting/wizard/WizardFilterCityState.jsx
- state is before city
- state is now a select rather than a search input
- states are now displayed in long form, rather than their abbreviation
- all states are shown, rather than only those that have records associated with them [1]
- You can't quickly select an option by partially typing it's name as you can with native selects. Not addressed as it affects all select components, not just this one.
- If you switch between reports, the state selection (and perhaps city, not sure) are persistent. That's how it worked before, so I didn't change it.
[1] Filtering by available states would have been much more work, as it would have required a callback for when such a change should occur, the triggering of that callback on load in addition to when city is changed, and a few other things.
> [PD-2330] Updated the City State Component

- myjobs/tests/test_manage_users.py
- myjobs/views.py
Without this, creating a user with an email address that already exists would override preexisting roles (which we want for edit, but not create). 
Long term, we'll probably want to disallow creating an existing user, but for now, this avoids the UI changes a proper solution would have required.
To test, add yourself as a user to a company you are already a member of with a role that you don't already have. You should see that you have that role in addition to the admin role you already had. On QC, you'll notice that you've then locked yourself out of a company instead.
> [PD-2323] Only add roles, no kill-and-fill.

- postajob/views.py
While QCing this issue, @fezick  noticed that a page that should have been 404ing was 403ing instead. That corrects that.
- head to /posting/admin : you should see a 404 if the company doesn't have marketplace access
- head to /posting/admin/enable : fill out the form with whatever you want
- head to /posting/admin again : you should see a 403, unless you're an admin for the company, in which case you should see an unrestricted page
> [PD-2346] Made sure app access was being checked first.

- gulp/src/common/ui/CheckBox.jsx
- gulp/src/common/ui/Datetime.jsx
- gulp/src/common/ui/SearchInput.js
- gulp/src/common/ui/TextField.jsx
- gulp/src/common/ui/Textarea.jsx
- gulp/src/manageusers/Role.jsx
- gulp/src/nonuseroutreach/components/EmailInput.jsx
- static/reporting.js
This used to be part of the -- now closed -- PR https://github.com/DirectEmployers/MyJobs/pull/2253
When determining if a form element should focus automatically on page load, we were using both booleans and strings. This PR makes them all bools. Why? This is how form data is returned to us by `django-remote-forms`.
> [PD-2328] Make autofocus consistent

- myreports/tests/setup.py
What the title says. No regression tests because it was never determined to be a regression. That is, I asked if duplicate column configurations should be allowed, but never received a concrete response, so left that functionality as is. Thus, if duplicates are allowed, then it's not a bug and is simply human error.
> [PD-2360] Removed duplicate config column for comm record reports.

- myreports/tests/setup.py
AJ noted while reviewing another of my tickets that the Partners report was missing the location filter.
- Run `./manage.py reset_dynamic_data`
- Visit /reports/view/dynamicoverview
- Select "Partners Report" from the second select box. 
- You should see A City and State filter named "Contact Location"
> [PD-2343] Added location to partner Report

- myreports/tests/setup.py
- myreports/tests/test_models.py
Reordered columns in each report to match the following (per @fezick's feedback): 
Communication Records Report
-     Report Name
-     Start Date
-     End Date
-     State
-     City
-     Tags
-     Communication Type
-     Partners
-     Contacts
Partner Report
-     Report Name
-     Start Date
-     End Date
-     Tags
-     URL
-     Partner Source
Contacts Report
-     Report Name
-     Start Date
-     End Date
-     State
-     City
-     Tags
-     Partners
> [PD-2344] Reordered Report Filter Columns

- gulp/src/common/ui/tags/TagSelect.jsx
I added a line to cancel the highlight of a tag, when you remove that tag, per the ticket.
> PD-2322 - Cancel the tag highlight on removal

- myreports/tests/setup.py
Exactly what it says. This is on the report generation page, not export.
@darrint there are a couple of tickets dedicated to fixing export names (column and values). For columns, what's the best place to change that? For values, I think you mentioned needing to come up with some other way to handle that, like some kind of format parameter or something.
> [PD-2352] Changed Data Source to Source

- myjobs/decorators.py
- myjobs/models.py
- myjobs/templatetags/common_tags.py
- myjobs/tests/test_models.py
- postajob/helpers.py
- postajob/views.py
Up until now, the `User.can` method had been checking for app access, but not responding differently based on it. The reason for this was that we had, up until postajob, been using can in conjunction with requires, which checked for app level access automatically. Furthermore, until recently, the return types in either case (insufficient app access or missing activities) was the same. This PR, does a number of things to correct this:
- I added a custom manager/queryset so that you can check for required access on an activity queryset directly (not essential, but convenient).
- attempting to call `User.can` with a company with insufficient app-level access now raises an exception (Http404)
- due to the above, the explicit 404 introduced by an earlier commit is no longer necessary
- can now …
> [PD-2362] Updated the way can works.

- gulp/src/reporting/ExportReport.jsx
Found that @aspidites dragging bug was not specific to him but due to a bug I introduced. This change protects us from any mutations done in the reorder component and better follows React's state management practices.
1. Export a report.
2. Drag fields up and down. Make sure to drag a field to the first position.
There shouldn't be any direct mutation of entities given to React state. They should be copied and replaced.
> [PD-2369] Eliminate mutation on fields list in ExportReport.

- myjobs/tests/setup.py
When I first wrote this bit of functionality, I was hoping to raise more meaningful errors when the method was called improperly. Ironically, it had the opposite effect, masking useful errors during development.
Thanks to @tdphillips  for reminding me how bad of an idea this is. Sorry to @koonsies for dev making life more difficult.
> Stop Masking Errors

- doc/Makefile
git subtree split only copies committed files.  So we need to commit everything that is generated before we commit it, not just the .nojekyll file.
> Update makefile to push all needed files.

- gulp/npm-shrinkwrap.json
- gulp/package.json
Without these shrinkwrap entries the build and many dev tasks won't work.
> Add shrinkwrap info for react-bootstrap-table.

- myjobs/tests/test_helpers.py
- myreports/datasources/comm_records.py
- myreports/datasources/contacts.py
- universal/helpers.py
Basically, I wrote a generic function which folds over an object to grab an attribute or a default if such an attribute does not exist. See the documentation for usage examples. Testing this will require having access to broken data, or breaking your data. I had a recent DB dump that I grabbed from Jenkins, which included such broken data. Once it's on QC, testing will be a matter of running a communication record for DirectEmployers Association and noting that there is now output, where before, all we had were column names.
> [PD-2383] Reporting doesn't hate Null foreign keys anymore

- gulp/src/reporting/ExportReport.jsx
- myreports/datasources/comm_records.py
- myreports/tests/setup.py
- myreports/views.py
What's changed:
-     ~~filtering by communication type now filters properly, which was the cause for the communication reports with 0 results~~ Reverted this since Darrin did the same in his PR already
-     the notes field of the communication record report is now plain text and has normalized whitespace – much smaller report downloads now.
-     regression from implementing human readable sorting where the sort by box wasn't being loaded when initially visiting the export page
-     another regression which caused column order to not be retained on export
- Date is now called "Date of Communication" in the communication record report
> Miscellaneous Reporting Fixes

- gulp/src/myprofile/main.jsx
Another simple fix.
If a date field is empty, it defaults to today. I was checking the wrong thing, so it was always "empty" and therefor always defaulting to today (and overwriting data).
> [PD-1971] fix bug

- gulp/src/myprofile/main.jsx
Before, trying to save or delete a profile unit would send you back to the regular django profile unit overview instead of the react-based one. This corrects that.
> Made sure redirects go to react urls instead of old profile units.

- gulp/src/nonuseroutreach/components/Content.jsx
- gulp/src/nonuseroutreach/components/Menu.jsx
- gulp/src/reporting/DynamicReportApp.jsx
Here, I was worried about making the sidebar not look awkward on mobile. 
- Order of content and nav is still different, but that wasn't my focus here. If someone can offer pointers on how best to fix that, I'll gladly include those changes, but otherwise I'm not concerned here. 
- I also didn't move the Menu component to a common component because I wasn't sure if anything that was done in reporting should carry over. If we decide that reporting is a special snow flake, I think we could move the sidebar from nonuseroutreach up a level.
- I didn't mess with profile units because it was using bootstrap 2 which doesn't really do responsive so well, as I understand it. It'd be easy enough to update to bootstrap 3 using the react template, but I suspect that the design of the page in general …
> Fixed sidebar width.

- gulp/src/reporting/SetUpReport.jsx
I verified this in all window widths that I could, including down to my browser's minimum of 475px. I'm open to suggestions if that is not adequate.
> Add max length to report name and enforce it on clone [PD-2370]

- gulp/src/reporting/DynamicReportApp.jsx
- gulp/src/reporting/MultiSelectFilter.jsx
- gulp/src/reporting/SetUpReport.jsx
- gulp/src/reporting/reportEngine.js
- gulp/src/reporting/spec/reportEngineSpec.js
- myreports/datasources/comm_records.py
* Create a Contacts or Communication Record report
* Filter by some field.
* Notice how the partners/contacts update as you make changes.
* Try to break it with history navigation and cloning.
* If any filter changes, the fields "subscribed" to the filter change notification call help again.
* Two pane selects update the filter repeatedly when [de]selecting many items at once. That's why the debounce is there.
> [PD-2351] Add "live" filtering to the partner and contact fields

- gulp/src/common/ui/DateField.jsx
- gulp/src/reporting/SetUpReport.jsx
- gulp/src/reporting/wizard/WizardFilterDateRange.jsx
* adds DateField to reporting
* enables the DateField to display errors as props from above ( https://github.com/DirectEmployers/MyJobs/pull/2311/files#diff-c5b207334a4c11ac32df04a2b0ba657cR177 ) which enables validation like...
* adds a new validation to confirm end date is after begin date ( https://github.com/DirectEmployers/MyJobs/pull/2311/files#diff-d50ed71fb5078e252db0450db9459aedR54 ).
I'll create another ticket to update export so it takes this date range into account.
I *can* create another ticket to improve the implementation of this component, if that's important. For example, enable free-text editing (and not just selecting the date fromt he popup).
Which opens:
Which opens:
> [PD-2294] Add DateField component to Reporting

- gulp/src/reporting/ReportList.jsx
- myjobs/templatetags/common_tags.py
- myreports/tests/test_views.py
- myreports/urls.py
- myreports/views.py
- templates/myreports/includes/report-sidebar.html
- templates/myreports/reports.html
- Dynamic Reporting is no longer in the beta menu
- Dynamic Reporting is no longer restricted to staff
- Switching between Dynamic and Classic reporting can be done via a button on the right-hand side
- Dynamic (Beta) reporting is the default.
- As such, the "Reporting" topbar submenu will remember which reporting you last went to.
- Classic Reporting no longer says "beta"
> [PD-2392, PD-2393] Implemented report version switching.

- gulp/npm-shrinkwrap.json
- gulp/package.json
- gulp/src/reporting/SetUpReport.jsx
`stopPropagation()` wasn't working because React doesn't use native events. We use this and `preventDefault()` a few other places, but I'd prefer to fix those on an as-need basis as I'm not entirely sure what other implications are to be had by using this method. 
This is using react-native-listener.
Reference fo this implementation: https://medium.com/@ericclemmons/react-event-preventdefault-78c28c950e46#.lq0ypqvz4
Running a report should now only happen if you click the run button or it's selected and you press enter.
> Started using native events for report.

- gulp/src/reporting/DynamicReportApp.jsx
- myreports/urls.py
- templates/myreports/includes/report_overview.html
Apparently that trailing slash breaks the export screen for classic reporting? This also removes a place where beta was noted in dynamic reporting.
> [PD-2398 PD-2392] Unbroke old reporting and removed beta from another spot.

- gulp/src/reporting/SetUpReport.jsx
- myreports/datasources/comm_records.py
- myreports/datasources/contacts.py
- myreports/datasources/partners.py
When running a report, you should now see that, after scrolling up (which happens automatically), the report filters have been reset. In addition, the state filter in contact and partners should show full state names instead of abbreviations.
> [PD-2399] Reset Report on Run

- myjobs/decorators.py
- myjobs/models.py
- myjobs/templatetags/common_tags.py
- myjobs/tests/test_decorators.py
- static/custom.css
- static/topbar.js
- the back arrow on the top bar for react apps is now full height like it is in non-react apps
- mouse exiting the window doesn't cause the mobile menu to automatically close anymore
- PRM and Reporting don't show up in the Employer menu if the current company doesn't have app-level access
- Reintroduced MissingAppLevelAccess to better test when that kind of response is getting. Operationally, it's just Http404, but determining that such is the case should be easier to do now when inspecting newrelic if something happens in production.
> [PD-2402] Miscellaneous topbar fixes.

- dk2/dev/Dockerfile
- gulp/package.json
- gulp/webpack.config.js
- HTTPS is no longer assumed to be enabled by default unless you're using docker
- you can enable it by doing DEVSERVER_HTTPS=1 npm run devserver*
- you can explicitly disable by doing DEVSERVER_HTTPS= npm run devserver
- port and host are configurable, defaulting to 0.0.0.0:8080
* technically, any truthy value works.
> Made some options of dev server configurable.

- gulp/npm-shrinkwrap.json
- gulp/package.json
- gulp/src/common/ui/ClickOutCompat.jsx
- gulp/src/common/ui/DateField.jsx
- gulp/src/reporting/ReportList.jsx
- gulp/webpack.config.js
Fixes:
* Components importing React Sortable wouldn't load on ie8 at all, at least under dev server.
* ClickOutCompat was needed and not being used in DateField.
* ReportList context menu couldn't be closed on ie8.
> Fix IE8 Reporting Bugs

- doc/source/developers/docker/use.rst
During my installation we discovered that you need to add your user account to the `docker` group. 
It was also my experience that the symlink breaks things, as the `dk rebuilddev` command copies the settings already.
Finally, the reverse proxy stayed up before I setup MySQL and Solr, so I documented that.
> Improve Docker Documentation

- myjobs/templatetags/common_tags.py
If the version cookie isn't set, you'll be directed to the classic reporting experience when you click on reporting in the navigation.
> [PD-2430] Classic is now default.

- mypartners/helpers.py
- tasks.py
- templates/mypartners/partner_library.html
- urls mentioned at the top of the Partner Library are updated
- HTTP calls made to OFCCP have been updated with proper headers to comply with new way pages are being served
To test, you can run the ./manage.py update_partner_library command. Before this PR, you'd get some failed HTTP requests. Now you should see something about successfully importing/skipping partners and contacts.
> [PD-2433] Updated method for grabbing partners from OFCCP.

- mypartners/admin.py
- mypartners/helpers.py
- mypartners/migrations/0032_auto__add_partnerlibrarysource.py
- mypartners/migrations/0033_library_sources.py
- mypartners/models.py
- mypartners/tests/test_views.py
- mypartners/views.py
- tasks.py
- templates/mypartners/partner_library.html
This ~~just just~~mostly moves partner library sources from the server to the database. Now updates should have a much faster turn around and not require hotfixes. 
*update:* This also exposes the source to the django admin, which has different edit permissions based on your email address (I think roles may be cleaner, but that's outside of scope for this):
- developers (@apps.directemployers.org) can edit anything
- staff (@directemployers.org) can edit the search url and name
- everyone else is read only
I also made the links on the Partner Library depend on these database values rather than being hard-coded in the template.
After running migrations for mypartners, `./manage.py update_partner_library` should function as it did before. Additionally, you should see a new "Partner LIbrary …
> [PD-2434] Partner Library Source

- myreports/datasources/comm_records.py
- myreports/datasources/contacts.py
- myreports/tests/test_comm_records_datasource.py
- myreports/tests/test_contacts_datasource.py
I have modified the filter_query_set function of both the communication records handler and the contacts handler. The following logic applies to both.
If one of the following fields receives an empty list, return no results:
contact, partner
If the tags object receives an empty list, return all untagged items of that category
If either of these receives a None, or the parameter is not passed in, do not filter on that field.
I have also modified/added tests to properly "poke" these scenarios. Without a UI, this is kind of hard to hand test.
> [PD-2405] Add Empty List Handling to Reporting

- automation/forms.py
- automation/source_codes.py
- automation/tests/csv/bad/bad_header.csv
- automation/tests/csv/bad/no_manipulations.csv
- automation/tests/csv/good/different_types.csv
- automation/tests/csv/good/one_row.csv
- automation/tests/test_source_codes.py
- automation/views.py
Testing:
- Head to the DestinationManipulation admin
- Search for something
- Select some rows If you select duplicate (view_source, action_type) pairs, undefined things will happen on reimport.
- In the dropdown, select "Save selected as CSV" and hit "Go"
- Modify if you wish.
- Head to /ajax/source-codes locally and fill out everything.
- "Buids" is comma-separated. These do not have to match the buids in the spreadsheet - if they don't match, the values in the spreadsheet will be copied to the provided buids. If not provided, we update rows based on the buids from the csv.
- Submit and verify that stuff happened in the DestinationManipulation admin
> Allow the upload of exported csv files [PD-2379]

- registration/templatetags/password_reset_tags.py
- registration/tests/test_models.py
This is #2362, but done right. Still feel slightly icky about it, but it doesn't seem to break a gang of tests like my last PR did. 
Basically:
- `getattr`, when not passed a third argument, will raise an exception when the attribute in question doesn't exist. The third argument will be returned as a default.
- If secure.my.jobs doesn't exist as an SeoSite (eg, while testing), then an exception is thrown
- as I'm using a string for a default value in that case (rather than making a database call on the fly), `getattr` would fail on line 31, so I made it return the seosite (a string by this point) as the default arugment
Example invocations:
The call `get_current_seosite(attr='domain', str_func='title')`:
- on www.myjobs would return the equivalent of …
> [PD-2442] Send Activation from console

- static/custom.css
Whoever merges this gets their choice of Chicken Tortilla or Steak Burger variety soup from Progresso.  Progresso® - Because it's Still Edible.
Per [this ticket](https://directemployersfoundation.atlassian.net/browse/PD-2445), there was a weird margin on the left side of Select menus.  I've fixed that without causing weird list action elsewhere.
> PD-2445 Minor style change to fix UL padding in menus and text.

- myjobs/models.py
- myjobs/tests/test_views.py
- myjobs/views.py
If you create a contact related to a user and then "delete" that contact, you can then not delete the user. The reason is that we actually archive the contact instead of deleting it, so when User.delete is searching for related fields, it ignores archived contacts, and thus doesn't work since there are still contacts technically referring to it. This ticket sets those relationships to null manually so that delete will work as expected.
> [PD-2448] Allow user deletion

- automation/forms.py
This generates the following SQL if I search for buids 1 and 2
```
SELECT `redirect_redirect`.`guid`, `redirect_redirect`.`buid`, `redirect_redirect`.`uid`, `redirect_redirect`.`url`, `redirect_redirect`.`new_date`, `redirect_redirect`.`expired_date`, `redirect_redirect`.`job_location`, `redirect_redirect`.`job_title`, `redirect_redirect`.`company_name` 
FROM `redirect_redirect`
WHERE `redirect_redirect`.`buid` IN (1, 2)
ORDER BY `redirect_redirect`.`guid` ASC LIMIT 1
```
> Stop grabbing the entire redirect count [PD-2444]

- templates/def.ui.microsite.mobile.css
- templates/includes/add_this.html
- templates/myblocks/blocks/share.html
- templates/stylesheet.css
Had no way to test this as addThis doesn't seem to run locally. Manually inspecting the page, removing hte anchor tag, and applying the styles inline seems to work though (styles verified by @fezick ).
The myblocks base template doesn't seem to load either of the stylesheets, so I'm not convinced the share widget has ever worked. IF it comes up broken later, we at least have this as a reference.
> [PD-2465] Added styling and removed g+ icon.

- mypartners/models.py
- mypartners/tests/test_models.py
- myreports/tests/test_views.py
We were assuming that contact name was enough to uniquely identify a row in contact reports, which led to double-counting when we were showing counts for each individual contact. This uses a combination of Partner, Contact, and contact email to uniquely identify rows and get the correct counts.
> Fix counts of referral and communication records in reporting  pd 2388

- myjobs/forms.py
- myjobs/tests/test_forms.py
Fixed a typo in the access request approval form. Will be difficult to test locally without manually expiring a request. I do have a regression test that does just that, though.
> [PD-2470] Fixed expiry check.

- templates/home_page/home_page_billboard.html
- templates/home_page/home_page_listing.html
- templates/home_page/home_page_my_jobs.html
- templates/home_page/home_page_static.html
- templates/home_page/home_page_static_header_footer.html
- templates/job_detail.html
- templates/job_listing.html
- templates/search_results.html
Copied from Jira ticket:
> Search pages (no results functionality included on page)
`<script id="detrack" defer src="https://d2e48ltfsb5exy.cloudfront.net/t/t.js?i=0,2"></script>`
Results pages (can include a search)
`<script id="detrack" defer src="https://d2e48ltfsb5exy.cloudfront.net/t/t.js?i=0,3"></script>`
Job view pages
`<script id="detrack" defer src="https://d2e48ltfsb5exy.cloudfront.net/t/t.js?i=0,1"></script>`
static pages
`<script id="detrack" defer src="https://d2e48ltfsb5exy.cloudfront.net/t/t.js?i=0"></script> `
If a template had a what/where box, but didn't iterate through jobs, I used the first. Otherwise, if it had a what/where box and did iterate through jobs, I used the second. I added the third to the search results template, and added the fourth to the two templates …
> [PD-2440] Added detrack to various page templates

- templates/seo_base.html
When more than one filter is selected during a search, a "nofollow" meta tag is added to prevent Google crawlers from bombarding the website.
This logic was the same before, but would be applied after three filters were selected rather than after two.
Behold my grand PR.
> [PD-1683] Add "nofollow" flag when more than one filter applied

- gulp/src/nonuseroutreach/components/NonUserOutreachApp.jsx
Apparently `<Grid />` means `<div class="container"`, which is of course a very bad idea in the middle of a layout that's already started. I didn't simply remove it since there can only be one root node in a react component (eg. two rows side by side is a no go, but two rows wrapped in a div is fine).
> [PD-2485] Stopped using grid as it's adding container which we don't want.

- myblocks/models.py
- seo/views/search_views.py
- templates/myblocks/myblocks_base.html
This is the ACTUAL PR for 1683. The previous PR was actually PD-2478 in disguise!
Basically, this PR causes the filter counts to properly reflect multiple filters on the facet_slugs category. Now, after more than one facet_slug filter is applied, the robots "nofollow" meta tag will be properly applied
Navigate to the following links and check the source for the following line..
`<meta name="robots" content="nofollow">`
http://ANYSTATE.jobs/operator-jobs/new-jobs/   (should NOT have the above tag)
http://ANYSTATE.jobs/manager-jobs/operator-jobs/new-jobs/  (should have nofollow)
http://ANYSTATE.jobs/business-jobs/manager-jobs/operator-jobs/new-jobs/  (should have nofollow)
> [PD-1683] Make "nofollow" count facet slugs properly

- tasks.py
The check_solr_count task is creating a lot of 1 item queues with the results that clutter up our rabbitMQ interface.  We don't use the results, so it shouldn't bother to store them.
> Clean up our RabbitMQ admin

- gulp/src/nonuseroutreach/components/InboxManagementPage.jsx
- gulp/src/nonuseroutreach/components/Menu.jsx
- gulp/src/nonuseroutreach/components/NonUserOutreachApp.jsx
- gulp/src/nonuseroutreach/components/OutreachRecordPage.jsx
This implements loading indicators for NUO.
This testing procedure is a little flaky but it does allow you to see the indicator after a few tries.
1. In chrome, open the debugger and go to the networking tab.
2. Go to throttling and create a new profile. "High Latency".
3. Set upload and download to 30000 and the latency to 2000. Save it.
4. Restart the debugger and refresh the page.
5. Go to networking again and select the high latency profile.
6. Refresh the page again. (just in case) It should be slower.
7. Flip frequently between the pages using the buttons in the sidebar.
Note that loading the spinner image is affected by the network latency as well as the XHR requests so it may not show up right away.
> [PD-2457] Loading Indicators in NUO

- seo/admin.py
- seo/migrations/0032_auto__add_field_configuration_template_version.py
- seo/models.py
- seo/views/search_views.py
- templates/v2/job_listing.html
This ticket involves creating the logic for switching between versions of templates. The basic idea is that versions of templates can be added to the choices tuple on the configuration model. The first value of that tuple will be the path of the template subdirectory containing the new version of templates.
For instance, 
```
TEMPLATE_VERSION_CHOICES = (
('v1', 'Version 1'),
('v2', 'Version 2'),
)
```
If a configuration has a template set of v2, the path to put the templates would be
` templates/v2/<path_to_template> `
The exception are v1 templates, which refer back to the base templates directory.
You may notice the tiny, worthless template added to /v2/job_listing.html. That template exists solely to test that the switching does work when a configuration is set to use version 2 …
> [PD-2463] add support for new templates

- myjobs/models.py
- myjobs/tests/setup.py
- myjobs/tests/test_api.py
- myjobs/tests/test_manage_users.py
- myjobs/views.py
We were ensuring that we didn't remove the admin role from the last admin user when editing roles, but not when deleting all company roles from a user. This adds a check to myjobs.api_delete_user.
> Forbid deletion of all roles from last company admin user [PD-2491]

- registration/forms.py
- registration/tests/test_forms.py
* Set `failed_login_count` on a user to at least 6.
* Set `password_expiration` on a company for which that user has roles.
* Try to login. You should see a validation message explaining what to do.
> [PD-2498] Tell locked out users how to fix their problem

- mypartners/tests/test_api.py
- mypartners/urls.py
- mypartners/views.py
Most of this can be tested in your browser. /prm/api/partner/ and /prm/api/partner/X/ accept GET requests.
We discussed allowing POST requests for /prm/api/partner/ but it was trivial to add support for both.
> Add API for searching for, retrieving, and creating partners [PD-2509]

- myjobs/tests/test_admin.py
- redirect/admin.py
Back when I made it possible to export destination manipulations as CSV, I forgot to include the view source name. This corrects that.
> Added veiw source name to csv output.

- doc/source/developers/styleguides/programming.rst
Google Code has gone the way of the dodo so we should probably stop pointing at it.
> Update Google Styleguide links

- mypartners/urls.py
- mypartners/views.py
Merge conflicts ahoy.
A few queries.
1 - This is basically identical to the other endpoints but much simpler. Tests?
2 - Does this make sense? NUO-specific stuff is under /prm/api/nonuseroutreach/ while generic PRM stuff is under /prm/api/
Future work - I would like to condense the apis using an as-yet-to-be-determined REST framework. There are deadlines, however. ¯\\\_(ツ)\_/¯
> Add Outreach Workflow State API [PD-2520]

- myjobs/tests/test_views.py
- registration/forms.py
If you want to test:
Try logging into a fake account. On base qc, you get no indication that something went wrong aside from an error in your dev console. On this branch, you get a form error.
> Don't throw a 500 when trying to log into an account that doesn't exist [PD-2512]

- doc/source/developers/mypartners/nonuseroutreach.rst
- mypartners/tests/test_api.py
- mypartners/views.py
The conversion API was written under different requirements than the current version of NUO and needed to be updated.
This PR covers
- Handling multple contacts
- Handling only one location per contact (but requiring that location)
- Modifying save functionality to prevent orphan objects
- Removing "approval status" fields
To test, use the data object below to hit the API with a post request.
You may notice that the "tags" fields are all empty. You can enter a tag via a PK or a string, but due to unique constraints and not knowing what PKs exist in your environment, I left these blank. Feel free to add additional. On that note, tags is changing very soon, so ignore the 500 error you get when you make a duplicate tag.
URL: https://secure.my.jobs/prm/api/nonuseroutreach/records/convert
``` …
```
> [Pd 2529] Updates to Conversion API

- gulp/src/nonuseroutreach/actions/navigation-actions.js
As the title says. I realized that my filter logic was case sensitive, which isn't what we're likely looking for in filtering.
> Add case insensitive regex to filter logic

- postajob/tests/test_views.py
- templates/postajob/form.html
- templates/postajob/package_list.html
- templates/postajob/purchasedjobs_admin_overview.html
- templates/postajob/purchasedjobs_overview.html
- templates/postajob/view_invoice.html
- templates/postajob/view_job.html
- templates/posting-stylesheet.173-18.css
Anywhere there's a card that contains the text "Product Details", we now show the product cost.
> Show product cost in a bunch of spots [ST-2907]

- mypartners/tests/test_api.py
- mypartners/views.py
The original overhaul of the conversion API lacked a bit of usability that is needed for proper use by the front end.
1) Contacts could no longer be properly added via PK
2) Notes were not properly appended for existing contacts on an add
3) Contacts, Partners, Comm. Records were not linked properly to an O.R. record on save
To test, simply ping the existing API with requests that contain the above features.
> [PD-2529] Updates to Conversion API

- gulp/src/nonuseroutreach/actions/process-outreach-actions.js
- gulp/src/nonuseroutreach/components/ProcessRecordPage.jsx
- gulp/src/nonuseroutreach/reducers/process-outreach-reducer.js
- gulp/src/nonuseroutreach/spec/process-outreach-reducer-spec.js
Consolidate form and item selection state into the `record` property. See the docstring in `process-outreach-reducer.js` for details.
Behavior shouldn't change. Forms should display. The happy path of select partner, select contact, record form, submit should still work.
> Consolidate State

- dk2/dockerdev.sh
Not currently used but this thing has to exist before we can test it.
> Add Mongo Docker stuff [PD-2556]

- gulp/src/nonuseroutreach/components/SearchDrop.jsx
- static/custom.css
Fix styling on overflow drop downs.  Should display as much of the name as visible, ending with an ellipsis if it extends off screen.
> Fixed overflow styling on partner/contact drop downs

- gulp/package.json
Created a "tests" script under "scripts" in the packgage.json file in the gulp directory.  To run this command from the terminal, cd to the gulp directory and type: "npm run tests".  This command will "watch" the JavaScript Unit tests as you develop.
The purpose of this task is to replace Docker with NPM when running JavaScript unit tests, NPM is a native JavaScript Node module and as such, plays "nicer" with other JavaScript stuff.
> [PD-2570] Added run tests script to package.json

- mypartners/models.py
As discussed, remove `blank=True` from `ContactRecord.date_time`.
> Remove blank=True from ContactRecord model.

- gulp/src/nonuseroutreach/api.js
- gulp/src/nonuseroutreach/components/ProcessRecordPage.jsx
- gulp/src/nonuseroutreach/components/SearchDrop.jsx
- mypartners/tests/test_api.py
- mypartners/views.py
1. Select a contact on the initial screen.
2. Observe the contact and partner selected in the minicards area.
3. Refresh.
4. Select a partner and contact separately.
5. Hopefully note the lack of any regressions.
Also note some ugly CSS. Maybe @huy-nguyen-colorado can fix that on another ticket?
> [PD-2578] Make initial contact select work right

- static/custom.css
Test:
1.  From Beta tab in top nav, click "Non-User Outreach".
2. Click "Outreach Records" in right nav.
3. Click "Review" button in the data table.
4. Type "a", or any character you wish, in the "Contact Search" input box.
5. Observe that text no longer overlap for long names, hopefully :-)
> [PD-2579] fix overlapping text

- gulp/src/common/ui/CheckBox.jsx
- gulp/src/common/ui/DateField.jsx
- gulp/src/common/ui/RemoteFormField.jsx
- gulp/src/common/ui/TextField.jsx
- gulp/src/common/ui/Textarea.jsx
- gulp/src/nonuseroutreach/actions/process-outreach-actions.js
- gulp/src/nonuseroutreach/components/OutreachCardContainer.jsx
- gulp/src/nonuseroutreach/components/ProcessRecordPage.jsx
- gulp/src/nonuseroutreach/forms.js
- gulp/src/nonuseroutreach/reducers/process-outreach-reducer.js
- gulp/src/nonuseroutreach/spec/process-outreach-actions-spec.js
- gulp/src/nonuseroutreach/spec/process-outreach-reducer-spec.js
Show a special append notes only form when clicking an existing contact mini card.
1. Select an existing partner and contact. You should be at the communication record form.
2. Click on the contact's mini-card.
3. See the new append-notes-only form.
> [PD-2573] append only contact form

- gulp/src/common/spec/diff-equal.js
- gulp/src/nonuseroutreach/actions/process-outreach-actions.js
- gulp/src/nonuseroutreach/spec/process-outreach-actions-spec.js
Before this it was possible to submit an empty city or state in a contact, which was being recorded as '{}'. That was bad.
1. Select Partner
2. Create a new contact.
3. Click 'add contact'.
4. Click the contact mini card.
5. See the errors on city/state.
6. Click 'add contact' again.
7. Click the contact mini card again.
8. See the errors on city/state are still there.
> [PD-2577] More reliable form validation.

- gulp/src/nonuseroutreach/components/NonUserOutreachApp.jsx
To test:
In NUO > Outreach Records > Review button > "Partner Data" form, click on the browser's back button and our modal will pop up with the text "All of your information will be lost if you navigate away from this page.", click OK to leave or Cancel to stay on view.
> [PD - 2589] Browser back button confirm pop up 

- mypartners/models.py
- mypartners/tests/test_api.py
- mypartners/views.py
This fixes a number of bugs regarding writing records to the database.
1. Pick a partner and contact.
2. Add an additional contact.
3. Add tags to the communication record. Set a date that is recent.
3. Go to PRM and verify that 2 communication records have been created and all tags are present on all records.
> [PD-2611] Multiple Communication Records

- gulp/src/nonuseroutreach/actions/process-outreach-actions.js
- gulp/src/nonuseroutreach/components/NonUserOutreachApp.jsx
- gulp/src/nonuseroutreach/reducers/process-outreach-reducer.js
- gulp/src/nonuseroutreach/spec/process-outreach-reducer-spec.js
Submitting the forms successfully was causing a _very_ confusing modal warning us that we would lose work. This adds dirty tracking to the process reducer so we do the right thing.
1. Start the workflow.
2. Hit back immediately.
3. Should not get a warning.
4. Start the workflow.
5. Choose a partner.
6. Should get a warning.
7. Complete the workflow.
8. Submit without errors.
9. Should not get a warning.
> Prevent history change only when we should.

- gulp/src/nonuseroutreach/actions/process-outreach-actions.js
- gulp/src/nonuseroutreach/api.js
- gulp/src/nonuseroutreach/components/ProcessRecordPage.jsx
- gulp/src/nonuseroutreach/reducers/process-outreach-reducer.js
- mypartners/tests/test_api.py
- mypartners/views.py
This populates the `outreach_record` form from the beginning to avoid error messages or missing form erros.
> Fix for PD-2622

- mypartners/tests/test_api.py
- mypartners/views.py
New partners weren't linked to the user's company and weren't showing up in PRM. This fixes that. Also, @tdphillips found that some new tag attachment code was redundant. That is fixed in this PR.
1. Create a new partner in NUO. Look for it in PRM.
2. In NUO create a new communication record with an existing tag and a new tag and attached to multiple contacts. (got all that?) Verify in PRM that the new and existing tags are on both communication records.
> [PD-2616] See New Partners in PRM

- mypartners/views.py
This removes the staff restriction on NUO.
To remove the staff attribute on your user:
$ dkm shell
In [.]: from myjobs.models import User
In [.]: me = User.objects.get(email__contains='$YOURUSER@apps')
In [.]: me.is_staff
Out[.]: True
In [.]: me.is_staff = False
In [.]: me.save()
Use NUO. As a company admin you should be able to use all of it.
To restore your staff attribute do the procedure above but set `me.is_staff = True`
> [PD-2623] Remove staff restriction.

- mypartners/views.py
We weren't setting `created_by` on new records. Now we are.
1. Create new records in NUO.
2. Find records in PRM.
3. See that your user created those records.
> [PD-2611] Set created_by on new records.

- gulp/src/nonuseroutreach/actions/process-outreach-actions.js
- gulp/src/nonuseroutreach/components/ProcessRecordPage.jsx
To test:
In NUO > Communication Record, in the "Communication Type *" drop down, if you leave that drop down option to the default option of "------" and click on the "Add Record" button, the browser should return to the top of the page to show the end user where the error is.
> [PD-2620], scroll to the top of form if there is an error in the form

- tasks.py
timeout send search digest
Also fixed a mistake from `requeue_failures` that came about because of changes to imports.
> Timeout send search digest.

- dk2/dev/Dockerfile
Sooner or later you will need this if you are working on microsites.
To incorporate it:
`dk rebuildev`
It will take several minutes due to downloading a lot of stuff via apt.
> Fix libgeos

- mysearches/helpers.py
- mysearches/templatetags/email_tags.py
- redirect/middleware.py
- redirect/models.py
- redirect/templatetags/redirect_urls.py
- redirect/tests/test_middleware.py
- redirect/tests/test_views.py
- seo/tests/test_integration.py
- seo/views/search_views.py
- templates/job_detail.html
- templates/myblocks/blocks/applylink.html
- templates/redirect/email/job_exists.html
- templates/redirect/opengraph.html
- templates/terms.html
To assist with tracking the refer(r)er values within analytics, we need to cause links to redirect to be sent via HTTPS.
This PR covers logic to force HTTPS on apply links on microsites, as well as overwriting some hardcoded values
To test the apply links, simply load the branch and view the target of the links
To test the hardcoded values, navigate to a view containing them.
This represents my current best stab at tracking down links to http://my.jobs. Any input toward other places to look would be appreciated.
> [PD-2610] Replace HTTP with HTTPS for Redirect Links

- seo/tests/test_views.py
- seo/urls/settings_urls.py
- seo/views/settings_views.py
PD-2519 has a requirement that we do stuff with view sources. As we don't want to add db connection info there, we're doing an endpoint that we can hit.
Requirements:
* Username and password of a staff user
Testing:
* Add some view sources if you don't have any
* `curl -H "Content-Type: application/json" -d '{"un": "<user email>", "pw": "<user password>"}' <link_to_microsite>/settings/view_sources`
> Add endpoint for grabbing all view sources

- gulp/webpack.config.js
- gulp/webpack.dev.config.js
- templates/base-react.html
- templates/postajob/form.html
- templates/postajob/job_form.html
For microsites we need to be able to use sass and generate a css bundle independent of `custom.css`.
1. Unset `WEBPACK_DEV_SERVER_BASE_URL` in `dev_settings.py`
2. Delete `static/custom.css`
3. Run `gulp` with no parameters or `dkgg` if you can run gulp with the docker aliases. This generates production bundles.
4. Verify that the following look ok: a react app, such as reporting or NUO, postajob product edit form, postajob job form. (All used `custom.css`)
Assuming you are configured for postajob, these urls worked for me:
* NUO https://secure.my.jobs/prm/view/nonuseroutreach/
* postajob product edit form http://directemployers.jobs/posting/product/purchase/add/1/
* postajob job form http://directemployers.jobs/posting/job/add/
* `webpack.dev.config.js` is improved to inherit it's …
> Tweak config and move custom.css.

- seo/forms/admin_forms.py
Verified with Xerox.
- Using Manage Users, create roles and users. Include unicode wherever you want.
- Go to the Django admin for that company
- Verify that you didn't receive a 500
> Allow unicode in the list of users for a given company [ST-3034]

- seo/helpers.py
- seo/search_backend.py
- seo/views/search_views.py
- templates/job_detail.html
In the slug field for titles, certain characters are automatically trimmed. A few examples are '?', '.' and ','
If a title is erroneously created to contain ONLY those special characters, the job title slug will be saved as blank. This PR covers modifying the code slightly to handle blank titles
This also fixes a small bug that happens when you try to load job search results when there are no jobs in solr.
The easiest way to load a job into the system with erroneous characters is to create one via postajob. If you have postajob set up on your system, simply create a job with a title such as "..." and view that job. It should work fine. On QC branch, it will raise a 500.
PostAJob docs
http://directemployers.github.io/MyJobs/developers/postajob/index.html
> [PD-2551] correct erroneous titles

- mypartners/forms.py
- mypartners/tests/test_api.py
- universal/forms.py
- Go to the "Add Partner" page
- Enter stuff containing multiple spaces
- In the notes textarea, include newlines in your input
- Save
- Verify that newlines were preserved
> Preserve newlines in NormalizedModelForm [PD-2602]

- static/images/dotJobsLogo.svg
- templates/seo_base_bootstrap3.html
Replacing the PNG logo with the SVG version in the static files and base template.
You can test by pulling down the V2 homepage template in Admin, seeing the logo and inspecting element. Or you can see the change in the code files as well which are the Static/Images/dotJobsLogo.svg and the Seo_base_bootstrap3.html file with the dotJobsLogo.svg image in it
> [2664] Replacing the PNG logo with the SVG version

- tasks.py
Or why unexpected keyword arguments should raise an error.
> Typo in task definition.

- gulp/src/sass/seo_base_styles.scss
- templates/seo_base_bootstrap3.html
- templates/v2/includes/search_box_vets_widget.html
Adding the re-branding styling to the sites that utilize the MOC Searchbox for 3 search boxes at the top of the screen.
Test:
To Test this task, change over to veterans.jobs or another domain inside of admin that utilizes the MOC search box. Make sure to switch over the homepage template to be home_page_listing_bootstrap3.html along with switching the version over to version 2. You should see the new design style along with a 3rd search box that's for the military title or code next to the original search boxes you would see on my.jobs.
> [PD-2679] Adding in the MOC Searchbox for veteran pages

- requirements.txt
1.5.1 removes instances of document.write.
> Updates django-ajax-selects to 1.5.1 [PD-2659]

- gulp/src/sass/seo_base_styles.scss
- myjobs/templatetags/common_tags.py
- static/topbar_v2.js
- templates/includes/topbar_v2.html
Purpose of this PR is to add the "Companies" sub menu to the "Employers" sub menu when in mobile browser mode (tablets, iOS phones up to 6 Plus, Samsung Galaxy S5).
To test:
1. Please enabled "Companies" in dev environment, in the dkm shell, if you haven't already.
2. Please switch to v2 template and home_page_listing_bootstrap3.html home page template in admin.
3. In mobile browser simulator of choice, please switch to mobile view.  Note: Once branch is merged with QC, more in-depth testing will be done in the actual mobile devices.
4. Please click on "Employers" in the bottom mobile nav, ensure that there is a "DirectEmployers Association" mobile link in bold font, and under that, there should be an additional sub menu with 2 testing companies mobile links named: "DirectEmployers …
> [PD-2675] Added 'Companies' sub menu to the 'Employers' mobile sub menu

- gulp/src/sass/seo_base_styles.scss
- templates/seo_base_bootstrap3.html
- templates/v2/includes/search_box_widget.html
Purpose of this PR is to gracefully transition from desktop view to iPhone 5 sized devices view.  End users will get the "full Monty" at screen size 992px and greater.  Between 991px and 769px, end users get a larger tablet view with smaller versions of the top bar and smaller footer.  At 768px and below, end users will get the full mobile web interface.
To test:
1.  Please switch to v2 template.
2. Navigate in desktop view, not much change here.
3. Decrease browser size to less than 991px but greater than 768px, please ensure that there is a "Filter Search Criteria" button, please click on it, this will toggle the visibility of the filter facets.  Please ensure search functionality still works.
4. Decrease browser size to less than 768px or use Chrome's mobile device simulator tools for …
> [PD-2673] changed mobile breakpoint to 768px, added tablet view

- myjobs/templatetags/common_tags.py
- templates/includes/topbar_v2.html
Purpose of PR is to lay the groundwork for the scrolling sub-sub menu in Mobile view in PD-2675, I created 3 new DOM ID's for mobile nav and I appended -mobile to a pre-existing ID call: id="{{ menu.id }}, the reason for this last one is because the Desktop view already has an ID call "employer".  I'm creating this PR separate from PD-2675 because there are other areas in the UI that can benefit from this PR.  This PR doesn't change anything visually in the browser, only changes in the DOM structure itself.
To test:
1. Please switch to v2 template and browser mobile simulator view.
2. Please inspect the DOM and ensure that these ID's exists: mobile-messages, mobile-beta, mobile-profile, mobile-employer-apps, and employers-mobile.
> [PD-2692] added DOM id's for mobile bottom navigation bar

- gulp/src/sass/seo_base_styles.scss
Purpose of PR is to change desktop top nav last tab sub menu from right-aligned to left-aligned for better UX, got approval from Jason Sole for this last week.
To test:
2. In desktop view, please hover over the last tab on the top nav and ensure that it's left-aligned.
> [PD-2693] Desktop top nav last tab sub menu 

- gulp/src/sass/seo_base_styles.scss
- static/topbar_v2.js
Purpose of PR is to add a listing of expandable/collapsible companies as a sub menu under the Employers tab in mobile view to match the desktop view.
To test:
1. Please switch to v2 template in admin and switch to mobile device view in browser.
2. Please switch to Super User and "modify" your roles so that you have as many companies as possible under the Employers tab.  Important for testing scrolling later.
3. Please click on Employers tab in bottom nav, the name of 1 company should appear in bold font with a "down caret" icon to the left of it, under Manage Users. By default the sub sub menu should be in collapsed state.  Please click on the "down caret" icon or name of company to expand/collapse.
4. When companies list is expanded, please test the scrolling of the list (I have 6 …
> [PD-2675] Added companies to Employers sub menu in mobile view

- myjobs/tests/test_views.py
- mysearches/models.py
- mysearches/tests/test_models.py
- requirements.txt
Some criteria need to be met for this to occur:
* You're creating a partner saved search that should be sent today (today is Thursday, Oct 20 and your search matches one of the following: daily, weekly on Thrusday, monthly on the 20th)
* It's after 10:00 AM
If both of those are true, the search will be queued immediately for sending.
Testing:
* If it's before 10:00 AM, wait until that is no longer the case
* Create a partner saved search scheduled for today
* ???
* Profit!
> Improve the initial sending of partner saved searches [PD-2682]

- gulp/src/sass/seo_base_styles.scss
- static/seo-base-scripts.js
Editing the logo so it is centered with longer names and doesn't wrap.
Test:
You will have to pick a name in the admin panel that is a long .jobs name. I was using PhiladelphiaEngineering.jobs and also PhiladelphiaMedicalAssistant.jobs. When you configure inside of admin, make sure it's Version 2 as well as using the home_page_listing_bootstrap3.html template. Will have to check with Jason Sole to make sure this is somewhat of how they want it for the logo instead of having it wrap it will be dynamically centered depending on the length of the text.
> [PD-2690] my.jobs - new templates - logo alignment can't handle long names

- gulp/src/sass/seo_base_styles.scss
- static/seo-base-scripts.js
Editing the logo alignment in mobile and desktop view.
To Test:
In the admin panel, switch to any .jobs domain. Make sure you are on V2 templates and also that you are using the home_page_listing_bootstrap3.html template. Also it should be set to HTML5. Specifically domains with longer names should be used and check the logo and text in mobile and desktop view. Should be somewhat centered for most of the time. Essentially it is a quick fix for the problem as we take time to explore possible other options to handle longer and shorter names together.
> [PD-2690] Editing the mobile solution for the logo alignment

- gulp/src/sass/seo_base_styles.scss
Purpose of PR:  hide the gap in mobile view when the Employers tab is triggered and the Companies list is in collapsed state.  This is the look that Jason Sole and I had agreed upon.
To test:
1.  Please switch to v2 template and mobile view.
2. Please enable "companies" role.
3. Please ensure that when the Employers tab is triggered and the Companies list is in expanded state, and when the Companies list is in collapsed state, the background from the end of the list to the top of Nav bar should be white.
Before:
After:
> [PD-2702] re-style mobile Employers tab company list

- gulp/src/sass/seo_base_styles.scss
- templates/includes/topbar_v2.html
- templates/v2/includes/search_box_vets_widget.html
Purpose of PR:  Reduce the size of the dot jobs logo in smaller screen sizes to make room for jobs related elements in v2.  Also restyled MOC v2 template because the search elements was difficult to use in smaller screen sizes.
Before:
After:
Before (missing nav in tablet view):
After (fixed):
Before (MOC place holder and button text hard to read):
After (fixed):
To test: 
1. Please switch to v2.
2.  Shrink screen size to see dot jobs logo getting smaller.  If all is well on the client side, the screen should look like the "after" pics.
> [PD-2717] Made dot jobs logo smaller in smaller screens

- gulp/src/sass/seo_base_styles.scss
- static/seo-base-scripts-181-27.js
Purpose of PR:  To address J. Sole user testing feedback. I made the autocomplete drop down list the same size as the input box for all screen size.
To test:
2. Please try the autocomplete functionality in various screen sizes, the drop down list should  match the width of the input boxes that they are triggered from.
Before Fix (size not matching):
After (input and drop down match regardless of screen size):
> [ST-3226] Made auto-complete drop down list same size always

- gulp/src/sass/seo_base_styles.scss
- templates/v2/job_listing.html
Purpose of PR:  Remove reference to v1 JavaScript file and v1 CSS file in v2 template called "job_listing.html" in templates > v2, this template is extending the "seo_base_bootstrap3.html", and as such inherits the "seo-base-scripts-181-27.js" file which has the exact same methods as the old v1 JavaScript file.
I also fixed a small UI bug for the "Save Search" DOM element in desktop view, screen shots below.
Before: 
After:
To test:
2. In desktop view, please go to www.my.jobs and/or veterans.jobs, ensure list of jobs renders.  Please type a job title in the jobs input box and click Search, please ensure jobs list shows up, unless it's a really odd job like underwater basket weaver, which should trigger the default "0 Jobs Found" view with "Clear All" …
> [PD-2724] Removed reference to v1 Javascript file and CSS, not needed

- import_jobs/mongo.py
As part of the import process, for each job in a zipfile, lowercase the job guid before upserting it into mongo.
> [PD-2701] Lowercase Job In Mongo

- seo/filters.py
Purpose of PR: remove the "Filter by" verbiage in the facets.
To test:
2. In desktop and mobile views for my.jobs and veterans.jobs (MOC), please ensure that the facet header does not contain the words "Filter by", it should only have words like: City, State, Title, Country, Military Titles, Bacon (just kidding, not bacon).
> [PD-2729] remove the 'Filter by' text in the facets per J. Sole's request

- gulp/src/sass/seo_base_styles.scss
Purpose of PR:  To fix UI bug in the Filter section.  The background and border was lost, I restored it by moving the style from the small screen scope to the root scope so it can be inherited in all screen sizes.
To test:
1. Please switch to the v2 template for www.my.jobs.
2. In the desktop and mobile views, please ensure that the Filter section has the light gray background and border like in the "After" screen shot.
Before: no background nor border
After:
> [PD-2728] Filter box UI bug fixed

- import_jobs/__init__.py
The old directory was trying to point at `/home/web/data` via a bunch of indirection, and `/home/web/data` was actually a symlink to `/tmp/data` anyway.  Just point at `/tmp/data` and cut the complexity.
> Fix data directory

- gulp/src/sass/seo_base_styles.scss
- seo/filters.py
Purpose:  Convert the Show More/Show Less into buttons.  Left align Show More Jobs buttons.
To test:
1.  Switch to v2 template.
2. In desktop and mobile view, please ensure the Show More / Show Less links are now buttons and hopefully working as buttons.
3. Show More Jobs buttons should now be left aligned.
> PD-2736, made 'show more' and 'show less' look like buttons

- gulp/src/sass/seo_base_styles.scss
Purpose:  Fix broken styles for the Saved Search element.
To test: 
2. Please search for a job without location nor MOC, to trigger the rendering of the Save Search "box".
3. If things goes correctly, the Saved Search box should no longer look like a naked poodle.  Please compare with before and after pics.
Before:
After:
> PD-2735, moved global saved search style properties to the root scope

- templates/mysearches/saved_search_widget_bootstrap3.html
Purpose: change Save Search email placeholder verbiage to something more intuitive.  Also removed commented out html codes that probably shouldn't be in production.
To test:
2. Please save a job title search, please ensure that the email placeholder text says "Please type your email address here".
Before:
After:
> PD-2747, changed save search email placeholder text

- templates/home_page/home_page_listing_bootstrap3.html
- templates/seo_base_bootstrap3.html
- templates/v2/job_listing.html
The "Filter Search Criteria" button was displaying on job detail views. This was a symptom of the element being part of seo_base, rather than the homepage/job_listing templates.
I moved the button div to the proper templates
Ensure that the above button appears on the homepage/job_listing pages (or anywhere else relevant) but not on the job_detail page.
> [PD-2741] Hide "Filter Search Criteria" Button in job_detail view

- seo/filters.py
To test:
In v1 template the text "Filter by" should precede filter name.
> ST-3339, hot fix for filter by verbiage

- seo/filters.py
Purpose:  Remove the "Filter by" verbiage only within the v2 conditional statement.  Leave v1 alone man!
To test:
1. In v1 template, please ensure that the verbiage "Filter by" precede filter criterias.
2. In v2 template, please ensure that the verbiage "Filter by" is not  preceding the filter criterias.
> PD-2748, remove the 'Filter by' text within the v2 conditional statement

- gulp/src/sass/seo_base_styles.scss
- static/seo-base-scripts-181-27.js
- templates/home_page/home_page_listing_bootstrap3.html
- templates/seo_base_bootstrap3.html
- templates/v2/job_detail.html
- templates/v2/job_listing.html
Purpose:  Render 1 filter list for both desktop and mobile through responsive design, rather than 2 filter lists for the exact same code like it is currently.
1.  Please switch to v2 template.
2.  In the desktop and mobile views, please use web developer tool to inspect the DOM and ensure that the direct_disambiguationDiv element only appears once.  Everything else should look exactly the same.
Before fix, notice 2 filter DOM elements performing the exact same work:
After, 1 filter element for desktop and mobile:
> PD-2733, refactored v2 seo base templates to prevent double filters

- gulp/src/sass/seo_base_styles.scss
- gulp/src/v2/seo-base-scripts.js
- gulp/webpack.config.js
- templates/seo_base_bootstrap3.html
Purpose:  Relocate the seo-base-scripts.js file from the static directory to the gulp directory in order to utilize the goodness of WebPack and es6.  Seems like a simple thing but this PR actually lays the foundation for using es6 project wide in the v2, in the future.  I also removed the "defer" attribute on the script tags which I added a couple of months ago.  I removed the defer because it was conflicting with the webpack-dev-server version 1.14.1 (known webpack issue).  Unexpectedly, page load times are faster with es6 and WebPack without the defer attribute than the old version with the defer attribute.  I emptied cache and hard reload 10 times in each version, the median load times for the new version is faster, also, in production the webpack-dev-server and websocket will not be …
> PD-2757, moved seo-base-scripts.js to gulp directory

- gulp/src/sass/seo_base_styles.scss
- templates/v2/includes/search_box_vets_widget.html
- templates/v2/includes/search_box_widget.html
Purpose:  Change the placeholder text in the "job title" input box to make more sense and a little easier to read, especially in MOC where there are 3 input boxes.
To Test: 
2. Please ensure the "what" placeholder text in www.my.jobs and MOC sites says: "job title, keyword, company"
> PD-2771, change placeholder verbiage to make for sense

- gulp/gulpfile.js
- gulp/webpack.config.js
- templates/analytics/analytics_main.html
- templates/manageusers/index.html
- templates/myprofile/react_edit.html
- templates/myreports/dynamicreports.html
- templates/nonuseroutreach/nuo_main.html
- templates/seo_base_bootstrap3.html
Purpose:  Remove the vendor.js file and all references to it because it was no longer being used, furthermore, it was adding 830K of extra weight to the load time.
To Test:
1.  Please switch to the v2 template.
2. In the dev tool network tab, please ensure that the seo_base_scripts.js file isn't 800k or more in size.  In the actual QC env, this file might be call 4bb123434566.js.
3. Please also do a functionality check of NUO, the profile page, dynamic reports, and  analytics.
> PD-2776, remove vendor.js file and references to it

- analytics/api.py
- analytics/tests/test_api.py
- analytics/urls.py
- myjobs/tests/setup.py
- myreports/migrations/0015_analyticsreports.py
This creates a starting point api for analytics.
* There are unit tests for the happy path
* I use `ApiValidator` for handling errors in a consistent way. It's also consistent with reporting.
* There are unit tests for the error cases.
* I use `value` to represent keys and ids that we want returned to us. I use `display` to represent things shown to the user. (We should convert the other analytics api call to follow that.)
* I'm still _not_ dealing with the fact that this api assumes that we are interested in analytics. We can add a parameter to `api/available-reports` when we are ready.
* If you have a working postman interface you can hit the api:
* `https://secure.my.jobs/analytics/api/available-reports`
* `https://secure.my.jobs/analytics/api/report-info?analytics_report_id=job-locatio …
> [PD-2762] analytics start api

- version.py
OSX may or may not have a binary called "python2" because why would it. Change the shebang to point to `python` and make the file as a whole version-agnostic.
> Make version.py work with Python 3 and systems with no binary named "python2"

- analytics_logpipe.py
- requirements.txt
Adds the file from MyJobs-Analytics that allows shipping Apache log files to kinesis/mongo. 
There were 4 real options for how I could have accomplished this:
1. Add the file to pymongo-env. It doesn't make sense there, but it would've been a convenient place for it. This would've caused issues with the analytics server, given the fact that the Apache config is pointing to a very specific location for this file that would change if installed via a package. Since that project auto-deploys I would've been jumping through hoops to get that deployment done without taking anything down, and I don't really didn't want to find out the penalties of taking down that server. 
2. Create a new repository. See 1.
3. Add this to the deployment repository. I actually kind of liked that idea, because …
> [PD-2763] Allow redirects to send logfiles to kinesis/mongo.

- middleware.py
This is one of those "that never should have worked" situations. Best guess is it never did work, and it's just that no one noticed until now. 
In QC we explicitly bypass the WildcardMiddleware, which is why it works there: https://github.com/DirectEmployers/MyJobs/blob/ba78d748fce0f82974cbf6979aad9d1e6c8eb6d0/deploy/settings_dseo_qc.py#L68
It doesn't work locally using the suggested setup, but I believe no one ran into it when it was written because we were likely using it via http://127.0.0.1:8000?domain=micrositeyouwanttoaccess.jobs, and WildcardMiddleware ignores requests going to an IP address directly: https://github.com/DirectEmployers/MyJobs/blob/ba78d748fce0f82974cbf6979aad9d1e6c8eb6d0/wildcard/middleware.py#L46-L48
> [PD-2782] Prevent WildcardMiddleware from redirecting when using domain switching

- gulp/src/v2/seo-base-scripts.js
- static/topbar_v2-183-9.js
- templates/includes/topbar_v2.html
- templates/seo_base_bootstrap3.html
Purpose:  I would like to prevent the possibility of adversely affecting the v1 templates with any changes to the v2 templates that might share static files with the former.  To that end, I copied the functions in the utils.181-20.js file and pasted them in the topbar_v2-183-9.js file because the topbar_v2 js file is the only file that needs utils.181-20.js, as far as the v2 base template is concerned.  I also removed the call to utils.181.20.js in the v2 seo_base_bootstrap3.html template, because it's no longer necessary. 
To test:  
1.  In Django Admin, please switch to v2 template and select home_page_listing_bootstrap3.html in the "home page template" dropdown.
2. Please test the functionality of topbar in desktop and mobile views, for example: log in/out, hyperlinks, companies, etc.
> [PD-2781], copied the functions in utils.181-20.js and pasted it in topbar_v2-183-9.js 

- requirements.txt
This specific version of pymongo-env has a testing mixin that forces switching to the mongo testing servers: https://github.com/DirectEmployers/pymongo-env/pull/2
> Upgrade to version of pymongo-env that has testing mixin.

- gulp/src/v2/seo-base-scripts.js
- templates/seo_base_bootstrap3.html
Purpose:  In my continuing effort to isolate the v1 and v2 templates, I copied the JavaScript functions in secure-block.181-20.js and pasted them in seo-base-scripts.js, and removed the called to secure-block.181-20.js in the seo_base_bootstrap3.html template.  
To Test:
1.  In Django Admin, please switch to v2 template and select home_page_listing_bootstrap3.html in the "home page template" dropdown, please click on the "Use secure blocks" checkbox and save.
2. Please go to www.my.jobs, use the browser's web dev tool to ensure there are no errors in the console because the base template checks for secure block immediately upon page load.  If things goes wrong, you will see an error like "load_secure_blocks is undefined".
3. With the "Use secure blocks" checkbox still checked in Django …
> [PD-2789] Copied secure blocks JS and pasted them in seo-base-scripts

- gulp/src/v2/seo-base-scripts.js
- templates/seo_base_bootstrap3.html
Purpose:  Remove the pager.164.21.js file call from the v2 seo_base_bootstrap3.html template that is being shared with the v1 template in order to avoid complications.  I added codes to the seo-base-scripts.js file to make the "Show More" / "Show Less" buttons work in the Facets, which was missing from my previously closed PR.  I also took this opportunity to fix some low hanging fruit eslint error, I didn't fix all of them, that will be for another task.
To test: 
1.  In Django Admin, please switch to v2 template and select home_page_listing_bootstrap3.html in the "home page template" dropdown.
2.  Please open browser's dev tool > Network tab and **ensure** (there goes that word again), that the pager.164-21.js file is not in the call stack.  
3. Please test the "Show More +" and "Show …
> [PD- 2797] remove pager.164-21.js call from seo_base_bootstrap3 template

- deploy/settings.myjobs_qc.py
- deploy/settings.myjobs_staging.py
- deploy/settings.redirect_staging.py
- deploy/settings_dseo_qc.py
- deploy/settings_dseo_staging.py
For safety purposes the goal should be to stop setting MONGO_HOST, MONGO_DBNAME and MONGO_SSL in the secrets file all together and always require the settings file to either set it or choose which one it should be set to.
> Since we're pulling stuff from secrets in pymongo-env, update secrets rather than settings.

- gulp/src/sass/seo_base_styles.scss
- templates/v2/job_detail.html
**Purpose**:   Add a second "Apply Now" button to the top of the Job Details view, I placed the second button at the top based on the projected use case scenarios.  I also changed the color of these call-to-action buttons to the industry standard green, and made the font easier to read.  Also removed Django internationalization tags and added future todo items.
**To test**:
1.  In Django Admin, please switch to v2 template and select home_page_listing_bootstrap3.html in the "home page template" dropdown menu.
2.  Please click on a job, ensure that there is an "Apply Now" button below the job title and location verbiage, as well as another "Apply Now" button at the bottom of the job info text.  Please click on the these buttons, if the job is not expired, then it should take you away from …
> [PD-2801], added second 'Apply Now' button

- gulp/src/sass/seo_base_styles.scss
**Purpose**:  Fix width mis-match with the "Company" facet in desktop view.  Please see after pic below.
Before: 
After:
**To Test:**
1.  In Django Admin, please switch to v2 template and select home_page_listing_bootstrap3.html in the "home page template" dropdown list.
2.  In desktop mode, please click on a company name in the "Company" facet, which will render a facet matching the width of the other facets like in the "after" pic above.
> [PD-2812] Fix Company Facet width discrepancy

- gulp/src/analytics/actions/calendar-actions.js
- gulp/src/analytics/actions/page-loading-actions.js
- gulp/src/analytics/actions/sidebar-actions.js
- gulp/src/analytics/actions/table-filter-actions.js
- gulp/src/analytics/api.js
- gulp/src/analytics/components/AnalyticsApp.jsx
- gulp/src/analytics/components/Calendar/BootstrapCalendar.js
- gulp/src/analytics/components/Calendar/Calendar.js
- gulp/src/analytics/components/Calendar/RangeSelection.js
- gulp/src/analytics/components/Header/Header.js
- gulp/src/analytics/components/SideBar/SideBar.js
- gulp/src/analytics/components/SideBar/SideBarDimensionList.js
- gulp/src/analytics/reducers/analytics-reducer.js
- gulp/src/sass/analytics.scss
This task was to replace the bootstrap daterangpicker with one that we currently have.
To Test:
Pull down the repository. You can click on the button with the Date in the header and see the calendar come down. The first part is the quick range selections which will trigger an API call and you can see the correct data going into the table in terms of filtering. You can also see the response coming back in the network Tab. If you click custom range inside of the dropdown it will pop out the calendar which has NOT been linked as of yet. This is be a different PR to set it with two calendars as a date range selection.
> [PD 2809] replacing calendar

- doc/source/developers/deployment/checklist.rst
**Purpose**:  Until I can add a testing framework that can inject a DOM to work with our Jasmine, I'm adding 2 more steps to our Deployment checklist.
To "**Test**":
1.  In MyJobs > doc > source > developers > deployment > checklist.rst, 
My Modifications are as follows, hopefully it will appear in the Deployment Checklist:
A.  Under the "Search" section, " - The second keystroke should show the autocomplete drop down list"
B.  Under the "Navigation" section, "- "Show More" and "Show Less" buttons should work like they're supposed to"
> [PD-2798] added 2 additional steps to the Deployment Checklist

- gulp/src/analytics/actions/calendar-actions.js
- gulp/src/analytics/actions/page-loading-actions.js
- gulp/src/analytics/actions/sidebar-actions.js
- gulp/src/analytics/actions/table-filter-actions.js
- gulp/src/analytics/api.js
- gulp/src/analytics/components/AnalyticsApp.jsx
- gulp/src/analytics/reducers/analytics-reducer.js
Task was to update the dates when filtering was done for sending off to the API.
To Test:
Pull down the repository. The best way to test this to make sure the correct request is being sent off is to check the Network Tab. You should see a fetch request sent to DYNAMIC api when the app loads for the start date and end date being 30 days. When you filter the table, you can check it again and it should still be for 30 days. You can also change the date with the quick selections from the calendar for any tab and re-filter and see it is saving the date and sending the correct request off to the API depending on which tab you filtered on and what date was selected. If you change the date in one tab and filter in that tab, the next tab will have that selected date that you changed to.
> [PD 2814] date changing on table filter request

- gulp/src/analytics/actions/calendar-actions.js
- gulp/src/analytics/actions/page-loading-actions.js
- gulp/src/analytics/api.js
- gulp/src/analytics/components/AnalyticsApp.jsx
- gulp/src/analytics/components/Calendar/Calendar.js
- gulp/src/analytics/components/Calendar/RangeSelection.js
- gulp/src/analytics/reducers/analytics-reducer.js
- gulp/src/sass/analytics.scss
Task was to create a date range selection with two calendars from the header.
To Test:
Pull down the repository. You can click on the date in the header and bring up the dropdown for quick selections. When you click custom range you will see two calendars appear. One being the start date and one being the end date. You can select that range and click apply and it will apply the filters to the data with those dates being sent to the API. You can also check the Network tab and see the request sent to Dynamic and make sure the headers are sending off the custom range that you selected with start_date and end_date in the request.
> [PD 2816] creating custom range selection for calendar

- default_settings.py
- middleware.py
- myjobs/helpers.py
- myjobs/tests/test_middleware.py
- static/utils.183-21.js
- templates/base-react-analytics.html
- templates/base-react.html
- templates/base.html
- templates/redirect/base.html
- templates/seo_base.html
This sets a cookie in middleware that should expire the same time as their session.
On the javascript side, we look for this cookie. If we can't find it, refresh the page, which should redirect them to the login page.
This isn't the cleanest approach, but I'm struggling to come up with a better alternative. 
Because we use `SESSION_SAVE_EVERY_REQUEST` the session is renewed every request, so I needed to use a method for checking whether or not the session has expired that did not involve making another request to the app (and therefore perpetually renewing the session).
> [PD-2423] Detect that a user has been logged out and refresh the page so they end up on the login page.

- gulp/src/analytics/components/Charts/Bar/BarChart.js
- gulp/src/analytics/components/Charts/Bar/RotatedXAxisTick.js
In this pull request:
* Currently the tooltip text is truncated. This prevents the job title in the tool tip from being truncated, even when the label on the graph is truncated.
* Currently, when the screen is resized, some of the labels containing the job titles are dropped. This prevents the job titles from being dropped, and angles the job titles so they display nicely on any screen type.
> [PD-2828] Analytics bar graph label and tooltip display improvements.

- gulp/src/nonuseroutreach/actions/process-outreach-actions.js
- gulp/src/nonuseroutreach/api.js
- gulp/src/nonuseroutreach/forms.js
- gulp/src/nonuseroutreach/spec/process-outreach-actions-spec.js
- mypartners/forms.py
**Purpose:** 
In NUO > Outreach Records > Communication Record > Tags, the tags that end users has assigned a color to shows up grayed out.  This PR attempts to fix this bug.
Before:
After:
**To test:** 
1.  Get to the "Communication Record" form like you normally do.  I get there via: NUO link in topbar > Outreach Records button in right nav > click on Review button > type letter 'a' in Contact Search input box, select AJ Selvey > Communication Record form now renders, click in the Tags input box, color tags should be included in the drop down.  The gray tags that have not been changed by end users will stay gray.
2.  Optionally, you could select a random tag to re-color with Tag Management and then go back to the Communication Record form > Tags, to ascertain that the tag have changed …
> PD-2614, fix the grayed out tags bug in NUO Communication Record form

- templates/myreports/includes/report_overview.html
**Purpose:** 
Add end-of-life warning text to Classic Reporting.
**To Test:**
1.  Please switch to Classic Reporting and ensure the sentence "Starting on March 6th, 2017, reports generated in the old reporting structure will be deleted, and the old reporting will no longer be available." is in the paragraph.
> [PD-2884] added end-of-life warning text for classic reporting

- seo/templatetags/job_setup.py
- seo/templatetags/seo_extras.py
- seo/tests/test_templatetags.py
- templates/job_result.html
- templates/listing_search_items.html
- templates/myblocks/blocks/searchresult.html
- templates/v2/job_results.html
Ensure that parameters used by analytics are passed along to the job view page from the job listing pages. 
The modifications themselves are pretty simple, although it took some searching to confirm that the request was being passed along as context to everything that ended up using `joblist_url()`. In case anyone else is wondering how things end up getting to `joblist_url()`:
The templates highlighted in red are unused as far as I can tell. I made the changes there too, but they should be non-impacting. I'd be interested if someone knew otherwise, as I'd like to test manually as well. 
The unused templates are:
* search_results.html
* v2/search_results.html
* v2/job_results.html
* listing_search_item.html
> [PD-2867] Ensure parameters are passed along to the URL on the job view page.

- analytics/api.py
- gulp/src/analytics/components/Charts/Bar/BarChart.js
- gulp/src/analytics/components/Charts/Map/USAMap.js
- gulp/src/analytics/components/Charts/Map/WorldMap.js
This ticket aims to fix the clickable charts from attempting to continue to apply filters when no further group_by types remain.
In addition to prevent the UI from sending these requests, this PR modifies the API code to prevent that type of request from sending 500 errors.
Click through a report and see that the chart becomes unclickable once are available filters are applied.
> [PD 2881] disable chart clicking last dimension

- gulp/src/analytics/reducers/analytics-reducer.js
To test:
Pull down the repository. You can add tabs by filtering. Then you can delete a couple of tabs or one if you like. Once you go back to the second or first tab in line and re-filter, it should remove all the tabs before it and start filtering again. Prior, it would just duplicate the very last tab instead of deleting it.
> [PD 2889] Fixing the deleting and refiltering of tabs

- mypartners/helpers.py
- mysearches/models.py
- mysearches/templatetags/email_tags.py
- mysearches/tests/test_models.py
Adds three tags used in DE analytics to partner saved search emails:
`de_n=PRM+Saved+Search`
`de_m=email`
`de_c={{partner_name}}`
> Add campaign tags to partner saved search emails [PD-2873]

- analytics/api.py
- analytics/tests/test_api.py
- deploy/settings.myjobs_qc.py
- deploy/settings.myjobs_staging.py
- deploy/settings.redirect_qc.py
- deploy/settings.redirect_staging.py
- deploy/settings_dseo_qc.py
- deploy/settings_dseo_staging.py
- myreports/migrations/0016_guid_to_reqid.py
- myreports/models.py
If you just want to switch guid to reqid, the only thing actually required is the migration. That's pretty awesome.
Since reqid might have a false-y/none-y value (which wasn't the case for guid), the way we do searches and display information to the user had to be updated. 
The value we display to the user is stored in `MISSING_VALUE`. Currently I have is as `"None"`. This could cause some problems if someone did something like had a job title of "None".
The grouping portion of this solution isn't really compatible with server-side pagination. After talking with @darrint and @koonsies it sounds like the best solution to that specific issue is to solve that problem when we get there.
I'm a little concerned about some of my logic in `group_rows()` not being generalized enough or …
> [PD-2864] Switch guid to reqid in analytics.
