mypartners/tests/test_views.py
Without this, all PR branches will fail.
=> Fixed time format.

templates/postajob/dseo/job_form.html
Bug fix that got missed when templates diverged for postajob.
=> [PD-874] Copied another change from myjobs template to dseo template."

registration/tests/test_models.py, templates/registration/invitation_email.html
=> Invitation user experience [PD-847]

postajob/views.py, templates/postajob/dseo/dseo_navigation.html
Posting Access and Product Access
Posting Access False
Posting Access and Product Access False
=> added permissions on dseo topbar [PD-901]

postajob/forms.py, static/postajob.160-2.js, templates/postajob/dseo/admin_overview.html, templates/postajob/dseo/request/purchasedjob.html, templates/postajob/myjobs/admin_overview.html, templates/postajob/myjobs/purchasedproduct.html, templates/postajob/myjobs/request/purchasedjob.html
Without this, the product form product count is broken.
=> Fix broken product form

dseo_urls.py, myjobs/views.py, static/dseo_account_settings.css, templates/dseo/delete-account-confirmation.html, templates/dseo/disable-account-confirmation.html, templates/dseo/edit-account.html
=> Account settings page

registration/templatetags/password_reset_tags.py, registration/tests/test_views.py, templates/postajob/request_email.html, templates/registration/activation_email.html, templates/registration/password_reset_email.html, templates/registration/password_reset_subject.txt, universal/helpers.py
Fixed the fact that my templates were being overridden.
Password Reset:
Activation:
=> Updated registration email templates.

seo/views/search_views.py
Does what it says. All tests pass.
=> Fixed a home reverse url

postajob/forms.py, postajob/tests/test_views.py, postajob/views.py, templates/postajob/includes/offlinepurchase_rows.html
=> Prevent the deletion of already redeemed offline purchases via form [PD-911]

templates/postajob/includes/offlinepurchase_rows.html
=> Fixed bad template

mypartners/tests/test_views.py, mypartners/views.py, templates/mypartners/email/email_response.html
=> Prevent creation of contact record and instead send error email when user is company user for multiple companies [PD-848]

mypartners/views.py, seo/admin.py, seo/migrations/0008_auto__del_field_company_prm_saved_search_sites.py, seo/migrations/0009_add_default_prm_saved_search_sites.py, seo/models.py, templates/mypartners/partner_edit_search.html, universal/helpers.py
=> Created datamigration and new field for displaying saved search domain lists [PD-904]

seo/filters.py, seo/helpers.py, seo/search_backend.py, seo/tests/test_filters.py, seo/tests/test_helpers.py, seo/views/search_views.py
90% of changes are for pep8 or readability. The two major changes were allowing custom facets to use a different offset than all of the other widgets  and forcing custom facets to respect always_show.
=> Facet counts off [PD-854][ST-844]

mysearches/admin.py, registration/models.py
I don't know how I missed this.
Tests pass.
=> Fix sendgrid header [PD-931]

myjobs/models.py, myjobs/tests/test_views.py
=> [PD-785, PD-788, PD-789] Opt-out notifications now display properly

postajob/tests/test_views.py
Updated some unit tests to manually pass HTTP_HOST.
=> Fixed a couple of unit tests.

templates/includes/topbar.html
Added redirect/reload when changing company in topbar.
Removed some things that weren't needed now that the page will reload.
=> topbar - reload when a user changes companies [PD-935]

seo/breadbox.py
=> Switched header text

myjobs/tests/test_views.py, myjobs/views.py
I ran tests yesterday. The only failing tests were due to Authorize.net's downtime.
Now that Authorize.net is up, they all pass.
=> Log request body to New Relic on error [PD-950]

seo/helpers.py, seo/search_indexes.py, seo/tests/solr_settings.py, seo/tests/test_views.py, seo/urls/search_urls.py, seo/views/search_views.py, transform.py
Reverts DirectEmployers/MyJobs#1168
=> Revert "Ajax jobs by location [PD-924]"

seo/helpers.py, seo/views/search_views.py
=> Facet blurb always there

seo/breadbox.py
=> Switched to a less rstripy method for removing jobs from the end of a string

seo/breadbox.py, seo/filters.py
=> Found another place where I was doing rstrip [now with more PD-986]

myjobs/decorators.py, myjobs/tests/test_views.py, universal/decorators.py
=> [PD-810] Preserve query parameters when redirecting with a next url

seo/helpers.py, seo/search_indexes.py, seo/tests/solr_settings.py, seo/tests/test_views.py, seo/urls/search_urls.py, seo/views/search_views.py, tasks.py, transform.py
Reverts DirectEmployers/MyJobs#1175
=> Revert "Revert "Ajax jobs by location [PD-924]""

myjobs/models.py, myjobs/tests/test_views.py, mysearches/views.py, templates/mysearches/email_opt_out.html, templates/mysearches/email_opt_out_message.html
* Changed the wording slightly
* added the notifications when a user clicks unsubscribe (all) in an email
* updated opt out unit test
* wrote unsubscribe unit test
* send_opt_out_notifications is parameterized now (as well as pluralized)
=> [PD-949] Unsubscribe notifications for unsubscribing by email

postajob/decorators.py, postajob/urls.py, universal/decorators.py
This code (and more) was recently merged into @galitskyd's reports branch and was reviewed by @tdphillips. As that will eventually be a feature branch, I wanted to backport this hotfix as it impacts users with access to postajob now.
=> [PD-985] Backport fixes implemented in pd-961 branch

templates/mysearches/email_base.html, templates/mysearches/email_single.html
* Made sure block content was actually inside the block
* The unsubscribe link was missing from the single emails, so I added it
=> [PD-993] Made sure links are inside the block so they aren't duplicated. Added unsubscribe link to single saved search emails.

seo/filters.py, seo/tests/test_filters.py
Probably broken down a bit further than I absolutely had to go, but in general it's better for inheritance than it was. Mostly just massive amounts of moving code.
=> Filters to individual functions

mysearches/forms.py, templates/includes/error-highlight.html
=> Disable the saved search recipient after it's already been set

middleware.py, seo/breadbox.py, seo/cache.py, seo/filters.py, seo/helpers.py, seo/models.py, seo/tests/test_breadbox.py, seo/tests/test_filters.py, seo/tests/test_helpers.py, seo/views/search_views.py
Remaining steps for feature branch: Javascript.
Allows multiple facets to show up on the right hand column thing.
=> A widget for facets

seo/views/search_views.py
Small change requested by Hal.
=> Force order to be buid, count, lat, lng

postajob/tests/test_views.py, postajob/urls.py, universal/decorators.py
More fixes to my decorator...this makes it so that you aren't redirected to login on /posting/list
=> [PD-1000] Stop the postajob listing page from redirecting on login

myreports/urls.py, myreports/views.py, static/reporting.160-26.js, templates/myreports/includes/prm/contacts.html, templates/myreports/includes/prm/partners.html, templates/myreports/includes/report-sidebar.html, templates/myreports/prm/page2.html, templates/myreports/reports.html
Just up for preview at the moment.
=> Myreports - Front-end Report creation, management, send

postajob/admin.py
All tests pass. Both forms work.
=> Wrong model admin type, given the form [ST-866]

middleware.py, mysearches/tests/local/careers.html, mysearches/tests/local/jobs.html, seo/admin.py, seo/breadbox.py, seo/cache.py, seo/filters.py, seo/forms/admin_forms.py, seo/helpers.py, seo/migrations/0010_auto__add_field_seositefacet_facet_group__add_field_configuration_brow.py, seo/models.py, seo/tests/test_breadbox.py, seo/tests/test_filters.py, seo/tests/test_helpers.py, seo/views/search_views.py, static/filter_carousel.js, static/pager.160-29.js, templates/seo_base.html
I don't think david's last attempt got all the changes from master synced.
=> Sync FEATURE-myreports with master

deploy/settings.dseo_prod_admin.py, deploy/settings.dseo_prod_web.py, deploy/settings.dseo_prod_worker.py
Reverts DirectEmployers/MyJobs#1220
=> Revert "Master"

deploy/settings.dseo_prod_admin.py, deploy/settings.dseo_prod_web.py, deploy/settings.dseo_prod_worker.py
Reverts DirectEmployers/MyJobs#1201
=> Revert "Updated settings files to use the new solr URL."

mypartners/models.py, myreports/tests/test_views.py, myreports/views.py, seo/management/commands/test_logos.py
- removed custom sort_by method as it caused values/values_list to act funny
- added order_by parameter to be passed to query set
- added count parameter to be used to pass in columns that should be counted
- updated unit tests to reflect and test the above changes
- cache isn't as aggressive
=> [PD-970, PD-977] Implement sorting and counting for referral records and user stats

seo/monitoring.py, seo/tests/test_import_jobs.py
=> Celery Camera to monitor all events and report if no etl_tasks have been executed.

mysearches/tests/local/careers.html, mysearches/tests/local/jobs.html, static/search-ac.161-4.js, templates/seo_base.html
=> [PD-916] Removed code that was generating invalid html

deploy/settings.dseo_prod_admin.py, deploy/settings.dseo_prod_worker.py, seo/views/search_views.py
Just keeping the feature branch up-to-date to save headaches later...
=> Sync feature myreports

seo/helpers.py, seo/views/search_views.py
=> Return all the facets

templates/includes/group_perm_handler.js
I technically only changed the first line. The others are showing as changed because I removed a level of indentation.
=> [ST-862] Sites now populate when choosing a group

myjobs/tests/test_views.py, templates/includes/topbar.html
=> Add count to non-mobile topbar [PD-956]

myjobs/tests/test_views.py, static/my.jobs.161-10.css
I didn't bump the css version number because it's not yet on production and qc should still be loading files locally. Is that okay with everyone?
All spaces at the end of lines seem to have been removed when I saved the file in vim. Not complaining, just didn't expect it.
Hopefully this is one of my last changes.
=> Add margin between message count and envelope icon [PD-956]

mypartners/helpers.py, mypartners/models.py, mypartners/tests/test_helpers.py, mypartners/tests/test_views.py, myreports/tests/test_views.py
- updated partner library as well as reporting filters for state and city filters
- Wrote unit test for that particular case.
~~I still need to figure out why that particular test is failing remotely, but works locally~~ Tests pass.
=> [PD-1055] Use Regex for state and city filters

mypartners/helpers.py, mypartners/models.py, mypartners/tests/test_helpers.py, mypartners/tests/test_views.py, myreports/tests/test_views.py
Reverts DirectEmployers/MyJobs#1268 
This didn't fix anything remotely, so no sense in complicating the code base with an unworkable solution.
=> Revert "[PD-1055] Use Regex for state and city filters"

seo/helpers.py, seo/search_backend.py, seo/tests/test_views.py
Open so @JLMcLaugh  can take a look, but really all tests pass so other than continuing to manually test I'm not sure what else I want to do.
=> List of fields used [PD-498]

default_settings.py, deploy/settings.myjobs_prod.py, myjobs/tests/test_views.py, myjobs/views.py, tasks.py
I think I got it all.
Requires `SENDGRID_BATCH_POST_USER` and `SENDGRID_BATCH_POST_PASSWORD` in secrets.py. Both are strings. I don't really care what you make the strings.
=> Sendgrid to celery [PD-1009]

moc_coding/tests/factories.py, myblocks/tests/factories.py, mydashboard/tests/factories.py, mydashboard/tests/test_views.py, myemails/tests/factories.py, myjobs/tests/factories.py, myjobs/tests/test_api.py, myjobs/tests/test_models.py, myjobs/tests/test_views.py, mymessages/tests/factories.py, mypartners/tests/factories.py, myprofile/tests/factories.py, myreports/tests/test_views.py, mysearches/tests/factories.py, mysearches/tests/test_forms.py, mysearches/tests/test_models.py, mysignon/tests/factories.py, registration/tests/factories.py, seo/tests/factories.py, seo/tests/test_local_cache.py, seo/tests/test_views.py, social_links/tests/factories.py
`FACTORY_FOR = Model` -> `model = 'app.Model'`
This also takes advantage of the extended `TestClient` features that I added while working on the reporting app's backend.
=> [PD-1087] Update Factories to use new API

static/my.jobs.161-18.css, templates/mypartners/overview.html
=> [PD-1094] Set a z-index for piehole.

mypartners/views.py
Tests take forever to run as-is, do we really want to generate 500+ contact records just to test this, or is it fine as is?
=> Replaced bleach with strip_tags.

universal/forms.py
Forgot to take care of the case when items aren't strings, which was discarding those results (eg. new tags)
=> [PD-1055] Fix Regression exhibited when using m2m fields

mypartners/migrations/0008_normalize_location_data.py
=> Added "orm." to model usage

tasks.py
Involves setting the ADMINS variable in the secrets file.
=> [PD-1057] Send emails on individual etl_to_solr failure.

myjobs/tests/test_tasks.py, tasks.py
Massive indentation. Suddenly everything works as intended.
=> Stop saving when nothing exists to save [PD-856]

myjobs/tests/setup.py, seo/admin.py, seo/migrations/0013_auto__add_field_configuration_moc_label__add_field_configuration_what_.py, seo/models.py, seo/tests/test_views.py, templates/search_box.html, templates/search_box_vets.html
=> Custom search box text [PD-712]

jsondata/usa_regions.json, jsondata/usa_regions.jsonp, mypartners/tests/test_views.py
Yeah...we also need to upload the files to cloudfront
=> Add wyoming

mypartners/helpers.py, mypartners/models.py, static/record_overview.161-25.js, templates/mypartners/includes/partner_sidebar.html, templates/mypartners/main_records.html, templates/mypartners/partner_searches.html
- added keyword search which checks against contact name, email, phone, notes job id, and subject
- added tag search
- updated placeholder text for existing tag and keyword searches in prm
Screenie:
=> [PD-702] Added keyword and tag search to communication records.

mypartners/forms.py
=> [PD-1022] Removed Country selection from PRM and changed state input to drop down.

seo/helpers.py, seo/search_backend.py, seo/views/search_views.py
=> Decreased the number of solr queries per page

seo/tests/setup.py, seo/tests/solr_settings.py, seo/tests/test_helpers.py, seo/tests/test_solr.py, seo/views/search_views.py
=> Solr tests

static/my.jobs.162-6.css, static/topbar.162-6.css, templates/base.html, templates/includes/topbar.html
=> Update css and links for inbox in topbar [PD-1111]

mypartners/forms.py, mypartners/helpers.py, mypartners/models.py, static/prm.162-5.js, templates/mypartners/edit_item.html, templates/mypartners/edit_location.html, templates/mypartners/includes/partner_card.html, templates/mypartners/partner_details.html, templates/mypartners/partner_library.html, templates/mypartners/prm.html
* state on all prm forms is now a drop down list
* when importing from partner library, if state isn't legit, we ask user to select a legit state
* modified format of import text some
* now possible to see if a partner library record has a valid location (which at this point is really just a valid state)
=> [PD-1083][PD-1135][PD-1122] Add state dropdowns and validation to PRM

mypartners/forms.py, mypartners/tests/test_views.py
Backporting contact-library-hot-fix to staging
=> Removed library from new partner form

seo/migrations/0014_unicode_configurations.py
- renamed migration so it wasn't a conflict
- added guard for sqlite so that we don't have to fake during tests or local development
=> Fixed utf-8 migration.

mypartners/tests/test_views.py, mypartners/views.py, requirements.txt
=> Stop creating contact records for invalid email addresses [PD-1150]

mysearches/tests/test_models.py, templates/mysearches/email_initial.html
=> Change view link to point to search.url instead of the view page on secure [PD-989]

seo/helpers.py, templates/job_listing.html
=> Fall back to solr query and title casing for locations so that we can add the breadbox to the no jobs page [PD-1141]

mypartners/forms.py, static/prm.162-16.js, templates/mypartners/edit_item.html, templates/mypartners/edit_location.html, templates/mypartners/partner_details.html, templates/mypartners/partner_library.html, templates/mypartners/prm.html
pushing this to staging per @fezick's request. This gets rid of the state drop-down in the partner library modal and adds a "Select a State" option to state drop-downs across PRM. The other changed files are just static filename updates. 
Screenshots in original ticket for the curious.
=> Changed how states are added in PRM.

mypartners/forms.py, mypartners/models.py, mypartners/tests/test_views.py, templates/mypartners/edit_item.html
=> Segment new partner form [PD-1163]

static/record_overview.162-25.js, templates/mypartners/main_records.html, templates/mypartners/partner_searches.html
- Activity status wasn't being cleared before being added
=> [PD-1190] Fixed bug that caused sort-by to break on contact-record

myjobs/models.py, mypartners/models.py, myreports/helpers.py, myreports/views.py, static/reporting.162-26.js
- I refactored the humanize helper function so that it doesn't have to do any more database queries than what the original report generation did. 
- I also made the Contact list show ContactRecord.contact_name instead. See the associated ticket for more information and screenshots.
=> [PD-1193] Better Exports and Contacts

seo/admin.py, seo/forms/admin_forms.py
Made text area's wider for select fields. See ticket for screenshots.
=> [ST-1099] Wider textareas

mymessages/migrations/0005_auto__add_index_message_expire_at.py, mymessages/models.py
See [here](https://rpm.newrelic.com/accounts/69231/applications/1995882/databases?tw[end]=1427983250&tw[start]=1427979650#id=479412914&app_trace_id=3750073274) if you're wondering why.
=> Indexed expire_at since it's used in message creation

myreports/tests/test_views.py, myreports/views.py, templates/includes/topbar.html
Reporting should now be available to anyone with PRM access.
=> [PD-1220] Reporting no longer restricted to staff (Staging)

myreports/tests/test_views.py, myreports/views.py, templates/includes/topbar.html
Reporting should now be available to anyone with PRM access.
=>  [PD-1220] Reporting no longer restricted to staff #1389 (Quality Control)

mypartners/views.py, templates/mypartners/edit_item.html
See ticket for screenshots. This makes entering new partners and contacts slightly more dummy-proof.
=> [PD-1082] Partner and Contact now display modal when duplicates found.

templates/myreports/report_overview.html
Removing as @fezick mentioned in chat. @aspidites appears to have enough on his hands for now.
Merges into the navigation branch.
=> Remove two unused html elements

myreports/views.py, static/my.jobs.162-26.css, static/reporting.162-26.js, templates/base.html, templates/myreports/report-archive.html, templates/myreports/report_overview.html, templates/myreports/reports.html, templates/static_page.html
Navigation and archive changes.
=> Myreports beta hotfixes

mypartners/helpers.py, mypartners/models.py, myreports/helpers.py, myreports/migrations/0003_auto__add_field_report_values.py, myreports/models.py, myreports/views.py, static/reporting.162-26.js
Added my changes which allows for values, corrects contact list, and adds beta sticker.
=> Contact List and beta sticker

templates/myreports/report_overview.html, templates/myreports/reports.html
Added beta tag to title and page header.
=> Reports beta tag

myreports/helpers.py
Like the title says. Will also reduce size of report generated.
=> [PD-1234] HTML properly stripped from columns now.

templates/mypartners/edit_item.html
Disabled forms when partner name or contact name is empty or a duplicate. Also made sure check was case insensitive.
=> Case insensative checks for partner and contact

mypartners/models.py
Contact list is broken in quality control. Staging is fine.
=> Fixed contact filtering

myreports/helpers.py
yeah....just reverted my changes since it isn't performing as expected.
=> Reverted merging of code as conditional branches weren't being fired

myreports/helpers.py, templates/myreports/report_overview.html, templates/myreports/reports.html
=> Reporting hotfixes

mypartners/models.py, myreports/views.py, static/reporting.163-3.js, static/reporting.163-8.js, templates/myreports/reports.html
- take contact types into consideration when filtering the contact list
- always pass contact type via report data
- added all checkbox
- prevent certain fields from being added to data as they are visual elements only
=> [PD-1205] Contact Type Improvements

myreports/views.py
- firefox doesn't like spaces in filenames
- replaced said spaces with underscores
- firefox is now happy
=> [PD-1246] Fixed filetype recognition on firefox

static/my.jobs.163-10.css, templates/base.html
Was (screenshot of a screenshot):
Now:
=> [PD-1248] edit communication record with attachments alignment skewed

static/prm.163-8.js, templates/mypartners/edit_item.html, templates/mypartners/edit_location.html, templates/mypartners/partner_details.html, templates/mypartners/partner_library.html, templates/mypartners/prm.html
Renamed the save button for editing a contact and updated event handlers.
=> [PD-1082] Made sure the edit contact button isn't disabled

static/def.ui.dotjobs.153-26.js, static/reporting.163-8.js
Because you know, I've not been programming for years in languages where array-like structures are 0-indexed...
=> [PD-1205] Fixed off by one on readable data

static/my.jobs.163-13.css, templates/base.html
AJ found that mobile was broken. Oops!
Fix:
=> [PD-1248] updated mobile for attachments fix

mysearches/tests/test_views.py, mysearches/views.py
Per @fezick, any staff should be allowed to initiate this.
=> Update saved search sending from qc [ST-1047]

static/prm-forms.163-8.js, static/prm.163-8.js, templates/includes/topbar.html, templates/mypartners/edit_item.html
- used an on focus event for all inputs except for name
- hijacked button press for validation
- no longer disable save button
I also went ahead and fixed the broken topbar which resulted from refactoring urls.
Net result - navigation buttons work, but we still check for duplicates.
=> [PD-1082] Partner/Contact Form Validation Improvements

static/prm-forms.163-8.js, templates/includes/topbar.html, templates/mypartners/edit_item.html
Was able to back port changes in pd-1082 by simply checking out those files instead of cherry-picking.
=> backported files from pd-1082 to staging

static/prm-forms.163-8.js
TextArea's aren't inputs, so the check wasn't being ran.
=> Added textarea selector

seo/tests/factories.py, seo/tests/setup.py, seo/tests/test_views.py, seo/tests/test_xmlparse.py
Kyle made changes to the seoxml document that impact tests. This updates our tests to reflect the changes.
=> Your tests will not pass without these changes.

mypartners/models.py, mypartners/views.py
Per request. Should be able to filter on the tag model using the new api now.
=> Added for_company to custom manager.

cdn_files/src-nlx-org/robots.txt, static/robots.txt, templates/robots.txt
Once approved, this need to be deployed to staging for review. Once verified, we need to deploy to production. I will review it immediately after staging is deployed.
=> Hotfix robots.txt on staging. PD-1276.

myblocks/models.py, mydashboard/admin.py, seo/models.py, templates/seo_base.html
This prevents any Select/Select.Multiples for Company from doing 30,000 queries.
I feel like this is a good place to complain about the lack of documentation for django_extensions.
=> Made __unicode__ function not make queries [ST-1181]

myblocks/models.py, mydashboard/admin.py, seo/models.py, templates/seo_base.html
=> SeoSite timeout

static/reporting.163-20.js
Fixed checkbox events for filtered lists.
=> Fixed events for filtered lists.

myreports/helpers.py, myreports/models.py, myreports/tests/test_views.py, myreports/views.py, static/reporting.163-14.js
- added tests for new myreports views
- removed the `count(s)` option, since that was causing slow downs
- updated documentation for views, helpers, and models
=> [PD-1280] Updated documentation for MyReports

templates/about.html
Updates copy per marketing's comments and suggestions.
=> About page marketing update [PD-1272]

static/prm-forms.163-28.js, templates/mypartners/edit_item.html
=> Array.prototype.trim() to $.trim() for IE8 compatibilities -- Staging

static/prm-forms.163-28.js, templates/mypartners/edit_item.html
=> Array.prototype.trim() to $.trim() for IE8 compatibilities -- QC

myjobs/models.py, mypartners/tests/test_views.py, mysearches/forms.py, mysearches/models.py, mysearches/tests/test_models.py
I've still got some issues with seo tests, but everything else passed. Let's see what Jenkins says.
=> Make deactivation of saved searches and deletion of the recipient set unsubscriber and send notifications [ST-1047][PD-560]

myreports/tests/test_views.py, myreports/views.py
Occurred to me that there is an api to access the stored file, so it shouldn't be so dangerous "deleting files" so long as I am using that API. As such, I went ahead and wrote a unit test for report regeneration.
=> Wrote unit test for report regeneration.

mypartners/models.py
Like the title says. The two hotfixes to master were ported from quality control, which is why they don't appear here...
=> Can now filtere contact records by city and state (QC)

static/prm.163-29.js, static/record_overview.163-29.js, templates/base.html, templates/mypartners/edit_item.html, templates/mypartners/edit_location.html, templates/mypartners/main_records.html, templates/mypartners/partner_details.html, templates/mypartners/partner_library.html, templates/mypartners/partner_searches.html, templates/mypartners/prm.html, templates/myreports/reports.html
Until we drop support of IE8 es5-shims will polyfill most of the missing functions introduced in ES5.
=> [PD-1322] Polyfill missing ECMAScript 5 functions

myjobs/tests/test_api.py, myjobs/tests/test_views.py, registration/forms.py, registration/tests/test_views.py, registration/views.py, templates/registration/password_reset_email.html, templates/registration/password_reset_subject.txt, universal/helpers.py
Exactly what it says on the tin.
All tests pass. Let's see if Jenkins agrees.
=> Include lowercase domain in password emails [PD-1268]

mypartners/models.py, mypartners/tests/test_views.py, myreports/helpers.py, static/reporting.163-27.js
- Changed to AND's for tags instead of OR's. 
- for Partner filtered list, check for contactrecord tags instead of partner tags
- ignore tags for contact list
Waiting on #1477 , which will simplify the diff for this one.
=> [PD-1317] Tags Improvements for Reporting

.gitignore
Resolve merge conflicts between master and QC.
=> Master to qc

mypartners/models.py, static/reporting.164-04.js
=> Primary contact natural key

templates/includes/topbar.html
=> Remove candidates from nav [PD-1320]

myjobs/models.py, mypartners/models.py, seo/models.py
=> natural_key = __unicode__

mypartners/models.py
We want "foo, bar", not "foo for company, bar for company"
=> Reverted change for tag natural key.

mypartners/models.py, mypartners/views.py
PEP 8 + fix parameter parsing.
=> [PD-1368] Fixed tags not being queried properly for tag management.

mypartners/models.py, mypartners/views.py
=> [PD-1368] Fixed tags long being queried properly for tag management.

mypartners/views.py, templates/mypartners/view_record.html
Made sure all query parameters are being passed to the edit view.
=> [PD-1372] Passed remaining query parameters to edit view.

default_settings.py, seo/models.py
=> [PD-1403] Email subjects now support unicode

seo/migrations/0017__chg_field_site_domain_length.py
This is numbered so it doesn't interfere with my other pull request (https://github.com/DirectEmployers/MyJobs/pull/1545)
=> Added migration to increase the length of the domain field on sites [ST-1271]

mypartners/forms.py
excluded archived_on from NewPartnerForm
=> [PD-1406] prm - archived on field being displayed in forms

mypartners/forms.py
excluded archived_on from NewPartnerForm
=> [PD-1406] prm - archived on field being displayed in forms - staging

mypartners/forms.py
excluded archived_on from NewPartnerForm
=> [PD-1406] prm - archived on field being displayed in forms - master

static/font-awesome.css
=> [PD-1407] fixed dumb mistake

templates/myreports/includes/report-archive.html
added data needed to parent row for archive view to work properly.
=> [PD-1408] reporting - Report Archive View fix - QC

templates/myreports/includes/report-archive.html
Hotfix for staging
added model information to parent div for view all reports
=> [PD-1408] reporting - Report Archive View fix - Staging

templates/myreports/includes/report-archive.html
Hotfix for master
added model information to parent div for view all reports
=> [PD-1408] reporting - Report Archive View fix - Master

myreports/views.py, static/my.jobs.165-04.css, static/reporting.165-04.js, templates/base.html, templates/myreports/includes/report-archive.html, templates/myreports/includes/report-sidebar.html, templates/myreports/reports.html
=> [PD-1413] reporting - visually show results are needed to view partner and contact reports - QC

myreports/models.py, myreports/tests/test_views.py
=> PD-1415 for Staging

myreports/models.py, myreports/tests/test_views.py
=> PD-1415 for QC

myjobs/tests/test_views.py, myjobs/views.py, templates/includes/topbar.html
Check that there is a valid session before showing options for authenticated users.
=> [PD-1402] Properly display session state

seo/forms/admin_forms.py
Sorry
@tdphillips and I discussed this a bit, and determined this would be the best way to do it. Some undetermined validator is throwing the error, and it really shouldn't be.
=> Allow larger domain submission

mysearches/tests/test_models.py, universal/helpers.py
Changed what's passed to urlencode to prevent errors.
=> [PD-1403] Parse query params as unicode instead of ascii.

mypartners/models.py, mypartners/tests/test_models.py
=> [PD-1433] Fixed locations in partner card.

myjobs/tests/test_views.py, tasks.py
Not really more to say. The original ticket asked us to increase from 30 days to 180, but as @tdphillips  already noted, it was 90 days before, not 30. As I don't actually have to touch any other file, I went ahead and proceeded with the change. Going back is trivial.
=> [PD-1224] Increased the delay from auto-unsubscribe from 90 days to 180

static/my.jobs.165-11.css, templates/base.html
See ticket for more details. It's now possible to zoom all the way out without fields wrapping awkwardly.
=> [PD-1247] Reduced margin to fix zooming issues.

mypartners/migrations/0016_auto__chg_field_partner_owner__chg_field_contact_partner__chg_field_co.py, mypartners/models.py
Not sure what the hotfix status on this should be, but I'm pointing toward QC so we can at least test before promoting to hotfix.
=> [PD-1450] Added SET_NULL to a few more relationships.

seo/tests/test_views.py, universal/helpers.py
Tested this against the test cases in the ticket, @almathew's regression test, and the tests for pd-1403.
Will hot fix against staging/master (whichever is determined we need) once tested on the QC server b y someone other than me.
=> [PD-1449] More Unicode, More Problems

solr/signals.py, solr/tests/test_solr.py, tasks.py
=> Prevent saved searches with no recipient from being inserted in solr <PD-1465>

myblocks/context_tools.py, seo/helpers.py, seo/tests/test_views.py, seo/views/search_views.py
Re-adds an improvement I wrote and then had to quickly un-write because it didn't work properly. Added a test for syndication feed because that's where we saw all the problems.
=> Re-added fl params

templates/includes/topbar.html
Probably only noticeable when doing development, but annoying none-the-less. JS, so no tests.
=> [PD-1467] Set company to first company if company_id wrong in cookie.

seo/models.py, seo/route53.py
I'm currently running through all sites using a form of this and it appears to be working.
As such, it's probably quicker to wait for Jenkins to run tests than to wait for my process to finish so I can.
=> A few improvements to mx records <PD-608>

requirements.txt, seo/models.py, seo/route53.py, universal/helpers.py
Just up for review. Don't merge until we can confirm `make_mx_record()` is working
=> Mx record checks

myjobs/tests/test_views.py, templates/includes/topbar.html
Fixed the bug and created the best test I could think of without selenium.
=> [PD-1505] topbar - company switching always defaults to first company in list

myreports/tests/test_views.py, static/reporting.166-1.js, templates/myreports/reports.html
~~Extending a unit test, then done.~~ Test written. Basically, this removes the stringent requirements for tag auto-complete.
=> [PD-1504] Tags should now work.

seo/tests/solr_settings.py, seo/tests/test_views.py, seo/views/search_views.py
Bug is fixed, but I'm still trying to wrap my head around enough of how seo + solr + tests work in order to properly write a regression test for this. As far as I can tell, the Apply view isn't tested at all.
=> [PD-1476] Stopped appending view source to job link if it's a mailto.

dseo_urls.py, seo/tests/test_views.py
Exactly what it says on the tin. If you wish to verify, modify the line in dseo_urls to what it was previously and run the added test.
=> Fix url name <PD-1513>

import_jobs.py, seo/management/commands/check_tasks.py, transform.py, xmlparse.py
start indexing the date_added field (already part of the production schema). 
Management command to check if tasks are backing up, but not making it to Solr.  (Dependent on the date_added field).
=> PD-1501 date_added field for solr, and mgmt command for checking tasks

static/reporting.166-06.js, static/reporting.166-08.js, templates/myreports/reports.html
This PR should be merged **AFTER** #1625 as reporting.js has been touched in both PRs.
While creating reporting.js I learned *a lot* about how Javascript uses objects and prototypes(!). So there were some choices made, like using six parameters to create a new FilteredList, that weren't the best which hurt maintainability/readability. With this PR I'm hoping to improve the maintainability and readability of this code.
* Prototype methods are created in a single object as oppose to being created separately and modifying the prototype object.
* Prototype methods are more clearly grouped together.
* Makes folding the code useful and shows what inherited methods are overwritten immediately apparent.
* ![screen shot 2015-07-08 at 1 56 50 pm …
=> Reporting Javascript Improvements

mysearches/models.py, mysearches/tests/test_models.py
~~Not sure if I'm done yet. Can't run locally since some of our code base uses SOLR 3 and 4, and I've only set up SOLR 5.~~
=> [PD-1509] Contact Record Tags from Partner Saved Search

states.py
This file is both in the local repo and on s3, adding pointless network time which can fail.
=> Use local states json file

deploy/settings.redirect_prod.py, deploy/settings.redirect_staging.py, redirect_settings.py, solr/helpers.py
=> More fixes

redirect/helpers.py, seo/tests/test_views.py
=> Parse guid as a guid <PD-1535>

seo/tests/test_views.py, seo/views/search_views.py
=> Add subject and body to mailto links <PD-1494>

static/reporting.166-29.js, templates/mypartners/edit_location.html, templates/myreports/reports.html
fixed typos, one in reporting graphs and one in edit location form.
=> [PD-1563] prm - overview report - spelling error

postajob/management/commands/test_posting.py
Found while debugging an actual issue with our db but it needs fixing anyway.
Tests pass.
=> Ensure we clean up the database if bad things happen <PD-1520>

myjobs/models.py, mypartners/tests/test_views.py, mypartners/views.py
Tests pass. I'm interested to see what people think. It's a slight perversion of get_email_owner.
=> Ensure we only check verified secondary emails <PD-1534>

myjobs/templatetags/common_tags.py, myprofile/models.py, myprofile/views.py, mysearches/tests/test_models.py, registration/tests/test_views.py, templates/done.html, templates/dseo/edit-account.html, templates/includes/account-page-2.html, templates/includes/topbar.html, templates/includes/widget-completion-email.html, templates/index.html, templates/mydashboard/candidate_information.html, templates/myjobs/edit-account.html, templates/myprofile/edit_profile.html, templates/myprofile/suggestions.html, templates/mysearches/email_base.html, templates/privacy-policy.html, templates/registration/myjobs/activate.html, templates/registration/myjobs/merge_request.html, templates/registration/myjobs/resend_activation.html, templates/registration/registration_complete.html, templates/registration/resend_activation.html, templates/static_page.html, templates/terms.html
A quick grep shows several more instances of "resume" but those are in job descriptions in microsite test feeds.
Tests pass.
=> Rename instances of resume to profile <PD-1495>

mypartners/models.py, myreports/tests/test_views.py, static/reporting.166-30.js, templates/mypartners/edit_record.html, templates/mypartners/main_records.html, templates/mypartners/view_record.html, templates/myreports/reports.html
=> Rename Contact->Communication in UI <PD-1523>

default_settings.py, mypartners/forms.py, mypartners/helpers.py, myreports/tests/test_views.py, static/partner-reports.167-3.js, static/reporting.167-3.js, templates/mypartners/edit_record.html, templates/mypartners/edit_tag.html, templates/mypartners/overview.html, templates/mypartners/partner_reports.html, templates/mypartners/printer_friendly.html, templates/myreports/reports.html
I may have missed a few...
Tests pass.
=> Oops <PD-1523>

templates/privacy-policy.html
This is a hotfix for master. Once it passes muster, I will open PRs for staging and QC as well.
=> Update copy of privacy document. HOTFIX. PD-1580

myreports/helpers.py, myreports/tests/test_views.py, myreports/views.py
Fix provided by @aspidites with some modification. Objection?
Tests pass.
=> Contact->Communication on report download <PD-1523>

static/record_overview.167-10.js, templates/mypartners/main_records.html, templates/mypartners/partner_searches.html
=> More contact->communication kerfuffles <PD-1523>

universal/states.py
=> This should be relative to the project root

templates/robots.txt
=> [PD-1595] Added disallow feeds to templates/robots.txt

static/my.jobs.166-12.css, templates/base.html
=> [PD-1604] reports - alignment issue with record boxes

redirect/helpers.py, redirect/tests/test_views.py, redirect/views.py
Tests passed locally.
Test coverage is spotty, but I'm slowly increasing it.
=> Allow CC for ad-hoc compliance emails <PD-1603>

seo/migrations/0020_auto__add_field_seosite_parent_site.py, seo/models.py
=> Add site parent fk <pd-1607>

myreports/views.py, static/reporting.167-20.js, templates/myreports/reports.html
=> Fixed javascript for field parsing in reports.

myjobs/tests/test_forms.py
Turns out I had already done most of this already. The only real thing that remains would be to pass the path and data into the constructor, but the tests are running, so I'm not inclined to change them.
=> [PD-1090] Removed unused import.

seo/admin.py
Somehow I failed to merge the addition of the parent site to the admin view for SeoSites.. 
Yay.
=> admin.py entry not added for <pd-1607>

seo/views/search_views.py
=> [PD-1698] feed - rss feeds with company filters not working - STAGING BACKPORT

mypartners/forms.py, mypartners/tests/test_forms.py
Local test run:
The first run, as you can see, is without my changes, the second, is with my changes. I also tested the form locally.
=>  [PD-1702] Made sure label was passed when creating a location from the contact form

mypartners/forms.py, mypartners/helpers.py, mypartners/tests/test_forms.py, seo/views/search_views.py
This contains the code from PD-1702 and PD-1701 combined to reduce deployments. Once those have been reviewed or merged, this will be ready to go to QC.
Will remove DO NOT MERGE when those others have been reviewed.
Will also duplicate this branch for staging and master after tested on QC.
=> Combined Hotfix

mypartners/forms.py, mypartners/helpers.py, mypartners/tests/test_forms.py
=> Hot fix staging

mypartners/forms.py, mypartners/helpers.py, mypartners/tests/test_forms.py
#1709, applied to master.
Will remove "DO NOT MERGE" once both tickets pass QC.
=> Hot fix master

static/reporting.167-25.js, templates/myreports/reports.html
Despite recalling doing some checks agains the clone functionality during the reporting refactor, AJ discovered that it wasn't working properly. I got it working again in addition to commenting the functionality, as some of the code may not seem necessary on first glance.
@galitskyd  can you take a look at this?
=> [PD-1710] Fixed clone report.

seo/search_backend.py, seo/search_indexes.py, templates/search_configuration/solr.xml
This isolates some changes from the previous api-merge branch to make build_solr_schema output the exact same schema as what is in deployment/search/.
So far the only testing is to make sure the output matches.
**Commentary Requested**: Can anyone think of a reason not to merge this? Will there be any odd side effects from these changes?
=> Fix build_solr_schema to match production. [PD-1703]

mypartners/forms.py, mypartners/helpers.py, mypartners/models.py, mypartners/tests/factories.py, mypartners/tests/test_helpers.py, mypartners/tests/test_models.py, mypartners/tests/test_views.py, mypartners/widgets.py, postajob/tests/test_views.py
This should bring the branches in line for the merging of quality control to staging.
=> [PD-1704] Hotfix of #1719 to staging

seo/cache.py, seo/context_processors.py, seo/models.py, templates/seo_base.html
Not exactly sure how I should bother testing this. I think that there is already a test for the context manager which is used to conditionally include the javascript. As such, a new test wouldn't do anything unless we were actually testing the javascript.
=> [PD-1618] CORS detection via OPTIONS call

seo/search_transformer.py
remove mutable defaults from the search_transformer.py
=> [PD-1758] added immutable defaults for search_transformer.py

mypartners/migrations/0019_auto__add_field_contactlogentry_successful__chg_field_contactrecord_cr.py, mypartners/models.py
To keep QC in sync with staging, merge the same code there.
=> [PD-1766] Auto Now Add.. merge with QC

seo/helpers.py
Hotfix to staging.. Remove call to transform_search and replace with previous functionality.
=> remove search_transformer step, replace old functionality -- Staging

seo/helpers.py
Hotfix to staging.. Remove call to transform_search and replace with previous functionality.
=> remove search_transformer step, replace old functionality -- Master

seo/helpers.py
Merge change to QC as well (to prevent accidentally reintroducing bug to staging)
=> remove search_transformer step, replace old functionality -- QC 

myreports/migrations/0008_auto__add_configuration__add_reporttype__add_columnformat__add_datatyp.py, myreports/models.py
This ticket essentially attempts to convert @haliscooper's [ERD diagram](https://directemployersfoundation.atlassian.net/browse/PD-1380) into Django models. At this point, I'm more concerned with getting the relationships correct. As such, while I'm more than willing to take suggestions on naming, I'd prefer to kee pthe bike shedding to a minimum. You will also notice that I am merging this into a feature branch. The intent there is that once we are sure things are faithfully represented and addressed any and all concerns (including any shedding of bikes which needs to occur), we can merge this into QC.
I created 11 new models
- Column
- ColumnFormat
- Configuration
- ConfigurationColumn
- DataType
- InterfaceElementType
- PresentationType
- ReportPresentation
- ReportType
- ReportingType …
=> [PD-1554] First go at reproducing Hal's ERD as Django models.

seo/helpers.py, seo/tests/test_views.py, seo/views/search_views.py
=> [PD-1780] Fix company logic -- Staging

seo/helpers.py, seo/tests/test_views.py, seo/views/search_views.py
Merge to master for company fix
=> [PD-1780] Fix company logic -- Master

seo/helpers.py, seo/search_transformer.py, seo/tests/test_search_transformer.py
* Improper handling of single quotes
* Added single quotes to list of characters to be considered part of their connected term
* Improper handling of field declarations with quotes or parentheses
* Added handling to identify field:"value value" format and field:("value value") format.
Test cases added for these examples. 
* use ./manage.py testfast
* from shell: 
* from seo.search_transformer import transform_search
* transform_search("your string here")
* runserver and try some searches!
* add a print line
* at seo -> helpers.py line 1012-1013
* print title
* or use ipdb...
* or cross your fingers and click Merge!
=> [PD-1779] Fix Search Transformer Asst. Bugs

mypartners/migrations/0024_auto__add_field_partner_archived_on__add_field_contactrecord_archived_.py
We have duplicate migrations. This fixes the one I made to resolve this.
=> Fix migrations

postajob/tests/factories.py, postajob/tests/test_payment.py, postajob/tests/test_views.py
Randomized more values to reduce the probability of duplicate transactions.
=> Attempt to fix authorize.net tests.

myblocks/migrations/0012_auto__add_field_page_doc_type__add_field_page_language_code.py, myblocks/models.py, seo/models.py, templates/myblocks/myblocks_base.html, universal/accessibility.py
The PR that added these fields to Configuration doesn't include tests and I'm not sure what value writing tests for this one would have.
Not specifying doctype or language code on a Page results in the one from the underlying Configuration to be used.
=> Add doctype and language code to myblocks.Page [PD-1736]

mypartners/models.py, mypartners/tests/test_models.py
Just a simple change that readds a bit of code that was errantly deleted.
=> Clear primary contact on archival of said contact [PD-1857]

mypartners/tests/test_views.py, mypartners/views.py
I successfully used this new code to delete the errant record linked in the ticket.
=> Allow communication records whose contacts have been deleted to be archived [PD-1844]

mysearches/tests/test_models.py, tasks.py
Awaiting responses on the ticket. In the meantime, the new task can be examined.
=> Allow requeuing of all unsent saved searches [PD-1811]

mypartners/migrations/0028_last_action_time_rename_in_models.py
Modify last_change_date migration to remove duplicates.
=> Migration fix

deploy/settings.redirect_staging.py
This is already live on staging so it's not really a hotfix.
=> Update ALLOWED_HOSTS to reference new staging server

myreports/views.py
=> Properly wrapped my decorator with @method_decorator.

redirect/tests/test_views.py, redirect_settings.py
=> Stop using seo/secure middleware for redirect (Staging) [PD-1560]

redirect/tests/test_views.py, redirect_settings.py
=> Stop using seo/secure middleware for redirect (master) [PD-1560]

mypartners/helpers.py
https://directemployersfoundation.atlassian.net/browse/PD-1910
Modifying contacts in a contact record was causing a serializer error. This is due to changes to foreign key relationships (under the current model) list the entire related model in the delta object. Code would change this relationship to a more readable format (<classname>: pk: <pk> desc: <ob. unicode>).
Feel free to critique the string format or any other issues with this change.
=> [PD-1910] Address issues with JSON parser in PRM

myemails/models.py
I was able to syncdb with this.
=> Re-add try/catch [PD-1939]

seo/views/import_views.py
which will correspond with task times.
=> Setup the check_solr_count and import_dashboard to use the current timezone

myjobs/views.py
User.all() loops are no bueno.
Updated that.
=> (PD-POYNTY) Fix for user loops

myjobs/migrations/0009_correct_activity_descriptions.py
```
In [4]: Activity.objects.filter(pk__in=[7, 8, 13])
Out[4]: [<Activity: update partner (Edit existing contacts.)>, <Activity: delete partner (Remove existing contacts.)>, <Activity: create partner saved search (Add new patner saved searches.)>]
In [7]: Activity.objects.filter(pk__in=[7, 8, 13])
Out[7]: [<Activity: update partner (Edit existing partners.)>, <Activity: delete partner (Remove existing partners.)>, <Activity: create partner saved search (Add new partner saved searches.)>]
```
=> Fixed errors in activity descriptions.

import_jobs.py, seo/tests/test_import_jobs.py, seo/tests/test_transform.py
Because creating the tests on the hotfix branch causes merge conflicts, I'm going to do them as separate PRs.  The actual code change can go out as a hotfix, but the tests go out the normal way.  Do not merge until #1906 is merged.
=> Tests for ST-2033

myjobs/decorators.py, myjobs/models.py, myjobs/templatetags/common_tags.py, myjobs/tests/setup.py, myjobs/tests/test_activities.py, myjobs/tests/test_decorators.py, myjobs/tests/test_models.py, myjobs/tests/test_views.py, mypartners/tests/test_activities.py, myreports/tests/setup.py, myreports/tests/test_activities.py, seo/models.py, seo/tests/test_models.py, templates/includes/topbar-new.html, templates/includes/topbar.html
No annotations as these were already annotated when this was merged into qc. This is hotfixed into staging as it didn't make the staging deployment.
=> Fix topbar

README.rst, doc/source/developers/styleguides/javascript.rst, doc/source/faq.rst
This is an example of how updating documentation would work if we used Sphinx hosted on gh-pages. 
Benefits over a wiki
- Updating documentation is an active process. You can be assured that at least one person looked at your documentation changes before it became final
- Allows for outside contribution: If someone else wants to update our documentation, they need simply fork quality control (I'm using sphinx here as my changes haven't been merged yet) and make their changes. 
I should note that as github allows files to be edited inline, one could easily make a PR with just as little effort as updating the wiki:
=>  Updated the FAQ and JavaScript Guide

myjobs/views.py
[This](https://github.com/DirectEmployers/MyJobs/pull/1933), but pointing toward QC.
=> PEP-8 For User Management

myjobs/views.py
I apparently broke stuff. leaving it to the author to fix PEP-8.
=> Revert "PEP-8 For User Management"

gulp/package.json, myjobs/views.py
http://stackoverflow.com/questions/34128823/warning-history-pushstate-is-deprecated-use-push-instead
=> fix history, a dependency of react-router

templates/manageusers/index.html, templates/myreports/dynamicreports.html, templates/nonuseroutreach/nuo_main.html
Is this everywhere we refer to the compiled files from gulp?
=> Use django-compressor for gulp files.

doc/source/conf.py, doc/source/developers/index.rst, doc/source/developers/seo/index.rst, doc/source/developers/styleguides/documentation.rst, doc/source/developers/styleguides/index.rst, doc/source/developers/styleguides/javascript.rst, doc/source/developers/testing/index.rst, doc/source/index.rst
- started writing a styleguide for documentation
- increased depth of tables of contents
- added an internal table of contents to the javascript styleguide with backlinks
=> Meta-Documentation

doc/source/faq.rst
Adding more faqs. At some point some of this information will be converted into a guide, but I'd rather all the pieces line up before I waste time doing that.
=> Apparently we still can't assign admins from a UI.

.gitignore, dk2/dev/Dockerfile, dk2/dockerdev.sh, dk2/env.sh, dk2/mysqldata/Dockerfile, dk2/nginx-proxy/.dockerignore, dk2/nginx-proxy/Dockerfile, dk2/nginx-proxy/LICENSE, dk2/nginx-proxy/Procfile, dk2/nginx-proxy/README.md, dk2/nginx-proxy/docker-entrypoint.sh, dk2/nginx-proxy/nginx.tmpl, dk2/solr/Dockerfile, dk2/solrdata/Dockerfile, dk2/squiddata/Dockerfile, doc/source/developers/docker/index.rst, doc/source/developers/docker/use.rst, doc/source/developers/index.rst
These are the docker scripts I wrote for myself. This system has proven useful even with it's flaws.
Future improvements might include:
* Remove darrint-isms from dockerdev.sh. (tag names, etc)
* Make background and backgroundstop commands more "symmetric".
* Separate build and start of background containers.
* Deploy some kind of local infrastructure in office so we don't have to repeatedly download and build the same images on everyone's workstation. (That would bring new system setup time down to under 20 minutes, easy)
=> [PD-2036]  docker scripts

doc/source/developers/docker/use.rst
@lemniscate613 did a run without me looking over his shoulder. Here are a few details that didn't make the merge which happened while I was out sick.
=> Tweak docker docs.

myjobs/cross_site_verify.py, seo/cache.py, seo/context_processors.py, templates/seo_base.html
Another tweak to see if I can get QC to behave properly. Reinstated qc/staging prefix modifications along with https/http resolution logic.
=> Modification to Saved Search, Tweak for QC/Staging Communication

templates/seo_base.html
I forgot a period.. I added that period (well, I had to change a bit about how the whole statement was structured.. but I really just added a period)
My url contained no period
I added a period
See if the URL has a period
=> Hopefully the last PR for Cross Site

seo/tests/test_views.py, templates/job_detail.html, templates/myblocks/blocks/searchresult.html
Adding commas to location string in job detail templates, and tests to verify that they're being rendered appropriately.
=> [PD-1919] Adding comma to locations.

gulp/package.json
Moving this from a manual installation to being auto-installed with everything else.
=> Add less and graceful-fs to requirements

postajob/tests/test_models.py
Curious what I could fix in 15 minutes.
=> Fix pep errors in postajob tests

gulp/src/manageusers/main.jsx, gulp/src/nonuseroutreach/components/Container.jsx, templates/base-react.html, templates/manageusers/index.html, templates/nonuseroutreach/nuo_main.html
Testing the simplest way to convey the company name from Django to React, for use in the NUO component's title area.
=> Testing concept to handle company names dynamically

default_settings.py, import_jobs/tests/data/hr_xml.xml, import_jobs/tests/test_ETL_imports.py, transform.py, xmlparse.py
This PR puts tests around the transform step in loading jobs from ETL.  It takes an XML document, loads it and runs it through our parser, and then asserts that the timezone data from the XML document is included in the data passed passed from it.
=> [PD-1969] Test for timezone support on ETL imports.

templates/wide_footer.html
QCing this amounts to ensuring that the links I've added match up with the links in the subtask [here](https://directemployersfoundation.atlassian.net/browse/PD-2064) and that there are no typos in the text I added. 
You can check locally by changing settings.PROJECT to "dseo" and visiting http://localhost:8000/?domain=www.my.jobs (change the port number if need be. This wont work by changing your hosts file, as one of the urls points to www.my.jobs.
=> [PD-2061] Updated links in template for states.

seo/cache.py, tasks.py
Ready for merge, imo.  See my second comment asking if anyone else can think of a reason why that would need to be delayed.
=> [PD-1901] job count cache

deploy/settings.dseo_prod_admin.py, deploy/settings.dseo_prod_web.py, deploy/settings.dseo_prod_worker.py
directory, not being able to find their dependencies.
=> Fix issue with settings files, once they're copied to the root of the

seo/tests/test_views.py, templates/job_detail.html, templates/job_result.html
Since testing trivial things is optional, these screenshots should suffice.
Job search:
Job view
=> Add comma between city/country [PD-2083]

gulp/src/manageusers/HelpText.jsx, gulp/src/manageusers/Role.jsx, gulp/src/manageusers/RolesMultiselect.jsx, gulp/src/manageusers/User.jsx, gulp/src/manageusers/UsersMultiselect.jsx, gulp/src/manageusers/main.jsx, static/custom.css, static/topbar.myjobs.165-10.css
Minor tweaks to layout and styling, per ticket PD-2004.
The visual changes should be different than the attached, noted, version, and changes should be noted in both Users-> Edit, as well as Roles -> Edit.
=> PD-2004 cleaned layout of User and Role edit views

seo/templatetags/admin_order.py
Added more common links to the django admin interface:
=> [PD-1941] Added more common links

gulp/src/manageusers/HelpText.jsx, gulp/src/manageusers/Status.jsx, gulp/src/manageusers/main.jsx, myjobs/models.py, myjobs/tests/test_manage_users.py, myjobs/views.py, static/custom.css
This PR is mostly about integrating invitations into user management, but it should solve PD-2003 too.
These work locally, and I'd like to test them on QC:
* Add User (not in system, in system but not assigned roles, in system but assigned different roles)
* Edit User (in system)
Run Django tests:
`dkm test myjobs.tests.test_manage_users.ManageUsersTests`
Run JS tests:
`dkgg build`
Create disposable email addresses: https://www.guerrillamail.com
Update roles and users manually: https://secure.my.jobs/manage-users/
=> [PD-2003] User management - invite user

myjobs/tests/test_manage_users.py, myjobs/views.py
Simply tests that the /manage-users/api/users/ API includes a `lastInvitation` field.
Requires this code to be merged first: https://github.com/DirectEmployers/MyJobs/pull/2034
This is the only code change: https://github.com/DirectEmployers/MyJobs/commit/910d67233840d5872b6b0a95fb050c1e62bbe80c
=> Test for last invitation

myjobs/models.py
Different behavior on local and QC. Saving user with multiple roles was causing error in send_invite() helper function.
=> User management box fix mulitple users

default_settings.py
=> Set ROLES_ENABLED to True.

myjobs/templatetags/common_tags.py
Basically, if you belong to at least one company with a role you should see the Employer menu.
=> [PD-2104] Check for group by simply seeing if you are associated with any company

import_jobs/__init__.py
Updated relative path to data directory.
=> Went up a directory.

myjobs/views.py, templates/includes/topbar-new.html
User Management is in production and should not be restricted to staff any longer.
This is based off master.
=> [PD-2125] Hotfix remove restrict to staff for user management

myjobs/tests/setup.py, myjobs/views.py, registration/tests/test_views.py
Exactly what it says on the tin.
=> Make password do unsecret things on the activation page [PD-2124]

deploy/settings.redirect_prod.py, redirect/models.py
Tested in environments resembling qc and production. Both function. Not sure if we want to start writing tests specific to static files.
=> Update redirect to use cloudfront [PD-1988]

static/custom.css, templates/base-react.html
=> Added padding declaration to UL to fix menu alignment

seo/admin.py, seo/forms/admin_forms.py
If you compare this to QC, you'll notice that when saving a company who has invited an admin in QC an error occurs. That error does not occur here.
=> [PD-2135] Initial Invitations

templates/registration/invitation_email.html
=>  paragraph inside a paragraph is not what we want. #2085 

myjobs/models.py, mysearches/models.py, templates/registration/invitation_email.html
When I first wrote this, I was in a hurry as it was meant to be a hotfix, so I deliberately mixed presentation with logic. This corrects that.
=> moved presentation to template.

doc/source/developers/deployment/checklist.rst
=> Post deployment checklist. PD-2255

redirect_settings.py
=> Disable excessive session saving on redirect

.gitignore, default_settings.py, myjobs/admin.py, mypartners/admin.py, requirements.txt, seo/admin.py, seo/forms/admin_forms.py, seo/lookups.py, seo/models.py
QC is showing some possible performance issues. I'd like to revert this for now since it's low priority and @aspidites probably won't be able to look at it this week.
Reverts DirectEmployers/MyJobs#2107
=> Revert "[PD-2167] Replace Django Extensions with Ajax Select"

gulp/src/manageusers/HelpAndTutorials.jsx, gulp/src/manageusers/main.jsx, static/custom.css, templates/base-react.html
Creates another page with helpful PDF and video documentation.
PDFs included in static files. Video embed responsive.
=> [PD-2168] user management - help page

gulp/src/manageusers/HelpAndTutorials.jsx
Updated design of this PR: https://github.com/DirectEmployers/MyJobs/pull/2116
=> [PD-2168] change design

myreports/datasources/base.py, myreports/datasources/comm_records.py, myreports/datasources/contacts.py, myreports/datasources/jsondriver.py, myreports/datasources/partners.py, myreports/datasources/rowstream.py, myreports/datasources/sql.py, myreports/datasources/util.py, myreports/models.py, myreports/tests/setup.py, myreports/tests/test_comm_records_datasource.py, myreports/tests/test_contacts_datasource.py, myreports/tests/test_datasource_rowstreams.py, myreports/tests/test_datasource_utils.py, myreports/tests/test_models.py, myreports/tests/test_partners_datasource.py, myreports/tests/test_views.py, requirements.txt
To test run manage.py reset_dynamic_data.
Go to https://secure.my.jobs/reports/view/dynamicoverview/#
Pick partners, then pick Number of Communication Records...
=> [PD-2120]  Count communications records per month.

gulp/src/manageusers/Role.jsx, myjobs/models.py, myjobs/tests/test_manage_users.py, myjobs/views.py
Since the front end only knows about Activity.display_name, that's what it sends to the view. Therefore, the view needs to look up the Activity by `display_name` and not `name`.
=> [PD-2165] User management - update activity display name

static/account-creation.158-6.js
Fixes broken stuff:
And keeps old stuff as it was:
=> Fix account creation JS [PD-2179]

static/custom.css, templates/postajob/dseo/form.html
As made famous in ticket PD-1956.
Changes to the template to use BS3 language, custom styles, and minor cleanup.
I've added a screenshot of the updated appearance, to the ticket.  Your site will need to have product access in order to view this change.  From the shell, I did this:
from seo.models import *
company = Company.objects.get(name='DirectEmployers Association')
//This needs to be the name of the company who owns the microsite you're using
company.posting_access
company.product_access
//should return true, but if either is false, update:
company.product_access = True
company.save()
If you still encounter a 404, you may need to add a Site Package in the admin.
The URL to test is your microsite version of this:
http://californiahotel.jobs/posting/admin/product/add/
=> Updated template for new product.

postajob/forms.py, static/postajob.173-18.js
This is a slight change to an already merged PR, to change the radio selects to a select input.
There may be a better way to make this element render as a select, but I wasn't able to figure it out and wanted to get this finished by EOD.
=> Changed Radio logic to select logic and adjusted JS to match.

registration/admin.py, registration/forms.py, registration/tests/test_models.py
> Showing  3 changed files  with 1 addition and 147 deletions.
There's not really anything that needs much scrutiny here. Removed a set of admin pages. Removed tests for said pages. Removed a form that was only used in said tests.
=> Remove Invitation model from admin [ST-2301]

myblocks/models.py, myblocks/views.py, mydashboard/helpers.py, mydashboard/views.py, myjobs/views.py, mymessages/views.py, mypartners/helpers.py, mypartners/views.py, myprofile/views.py, mysearches/views.py, mysignon/views.py, postajob/views.py, redirect/helpers.py, registration/views.py, seo/admin.py, seo/views/settings_views.py, universal/decorators.py, universal/helpers.py, universal/views.py
I left some of the messages alone as, while they don't include method names, they are fairly descriptive and should be unique if searching the codebase.
Testing example: /candidates/view/details/ should now contain a vaguely helpful error message.
I'm open to further suggestions.
=> Add messages, do PEP 8 [PD-2213]

static/custom.css, templates/myjobs/request_company_access.html
=> Make auth code stand out on company access request form [PD-2223]

doc/source/developers/docker/use.rst
Forgot to add this an earlier PR which fixed QC.
=> Add setting needed for context handler to doc.

gulp/src/common/ui/Select.jsx, gulp/src/myprofile/main.jsx
Controlled vs. Uncontrolled is in the sense of React form controls. Controlled is turning out to be what we want. I'm updating just the select control at this time.
=> [pd-2279] Make select component api export a controlled API.

myjobs/migrations/0016_nuo_app_activities.py, myjobs/tests/setup.py, mypartners/tests/test_activities.py, mypartners/tests/test_api.py, mypartners/views.py
=> [PD-1975] Added activities for NUO.

seo/admin.py, seo/forms/admin_forms.py, seo/tests/test_admin.py
Displays company user data on the company admin page with a new TableWidget.
I also made the prm saved search field lazy load to match the behavior of the Job Source ID and Featured On fields.
=> Add company roles to Pd 2236

static/topbar.js
Company selection is currently broken for IE 8, due to event.preventDefault() not being a thing. This corrects that (by relying on jquery, which I think just proxies to event.returnValue or something).
=> [PD-2298] fixed topbar for ie 8

gulp/src/manageusers/main.jsx, gulp/src/nonuseroutreach/components/Container.jsx, gulp/src/reporting/DynamicReportApp.jsx, gulp/src/reporting/main.js, myreports/views.py, templates/base-react.html, templates/manageusers/index.html, templates/myreports/dynamicreports.html
Before, we only showed the company name on user management and nonuser outreach. It's now on those, new reporting, and any future react app that derives from react base. If no company is passed into the template before rendering, the row is not displayed. I also made it so that the company name has the correct weight.
=> [PD-2147] Company name now properly displays on all react apps

dk2/nginx-proxy/.dockerignore, dk2/nginx-proxy/.travis.yml, dk2/nginx-proxy/Dockerfile, dk2/nginx-proxy/Makefile, dk2/nginx-proxy/README.md, dk2/nginx-proxy/circle.yml, dk2/nginx-proxy/nginx.tmpl
@lemniscate613 bumped into this.
I upgraded and repatched our version of nginx proxy as this was fixed upstream.
=> Update to newer nginx-proxy.

gulp/src/common/ui/Select.jsx
Fixes Select component bug in IE8.
1. Follow VM instructions: http://directemployers.github.io/MyJobs/developers/docker/use.html#set-up-docker-with-vm-of-windows
2. In IE8 in your VM, visit: Visit https://secure.my.jobs/profile/view/
3. Find the module ID of a Education module (hover over its Edit button).
4. Replace MODULEID in this URL and visit: https://secure.my.jobs/profile/view/module/#/MODULEID?module=Education
5. Confirm select drop downs work
Known issue with creating a new module. This issue is resolved in PR https://github.com/DirectEmployers/MyJobs/pull/2266.
=> [PD-2327] Fix Select component bug in IE8

static/custom.css
Not much to say, here.  I changed a couple styles, and put things back in alignment. 
_I accept cash donations._
=> PD-2308 - Aligned fieldset to other form fields.

myreports/views.py
I basically just made sure that values were constricted by company where they made sense. I looked through the data sources as well, but those seemed to be checking for company already. I didn't end up restricting by user as theoretically, as long as you have access to reports, you would want to see all reports, not just those you created.
=> Updated views that needed to be checking for company and user access.

myreports/column_formats.py, myreports/tests/setup.py, myreports/tests/test_models.py
Magic.
Shows up as something like this: `04/07/2016 06:32:00 PM`
=> Add times to two dates [PD-2359]

gulp/src/reporting/SetUpReport.jsx
I added a loop to scroll over 250ms so the user sees they're being taken back to the top, and not to a new page.
=> PD-2382 - Added function to scroll report to top, when a report is run.

mypartners/tests/test_views.py, mypartners/views.py
=> [PD-2381] Fixed contact form (hot fix to master)

gulp/src/common/ui/DateField.jsx, gulp/src/common/ui/TextField.jsx
This PR uses a technique @darrint used in Reporting to make popups a little more intelligent. Previously you could get two popup calendars at once (though this was hard to reproduce).
An added benefit of this PR is clickout should be working as intended on IE8, finally.
=> [PD-1971] Fix IE8 Bug

gulp/src/common/ui/SearchInput.js
Changes to searchinput component to fix issues with keyboard navigation in the menu and a situation where, if you've made a choice already, you could not clear the field back to empty again, as the previous choice would repopulate.
=> PD-2385 - Fixes to the behavior of SearchInput

gulp/src/common/ui/SearchInput.js, gulp/src/reporting/ExportReport.jsx, gulp/src/reporting/SetUpReport.jsx, gulp/src/reporting/SortableList.jsx, static/custom.css
Fixed autofocus error introduced into QA
Added button highlight capability (global)
Changed the SearchInput (partner report > URL, Source) to use the dropdown class
Fixed broken proptype in Sortable List
Made heading text smaller in preview table
Added report name to export report page
Added Export instructions
=> PD-2384 Some UI updates per the ticket notes

gulp/src/reporting/ExportReport.jsx, gulp/src/reporting/SortableList.jsx
* The UI was not updating when switching between export screens from the export screen.
* Fixed a missing key warning.
=> Fix export history

templates/mypartners/includes/date_widget.html
This class had no associated styles, but was picking up styles from the new date range component.
=> PD-2376 - Removed unnecessary class from date widget

gulp/npm-shrinkwrap.json, gulp/package.json
This allows react-native-listener to install.
=> Fix shrinkwrap

static/custom.css
=> Relative svg url

gulp/src/common/ui/PopMenu.jsx, gulp/src/reporting/ReportList.jsx, myreports/views.py, static/custom.css
This PR simply adds a refresh spinner to the ReportList when a report is refreshed
* Do the dev-server/gulp shuffle.
* Head to dynamic reporting
* Click an existing report in the sidebar
* Click "refresh"
_NOTE: Locally, refresh happens very quickly for me. Adding a sleep to myreports->views->refresh_report helps to see the spinner_
=> [PD-2387] Add refresh indicator for reports

gulp/src/reporting/MultiSelectFilter.jsx, gulp/src/reporting/SetUpReport.jsx, gulp/src/reporting/reportEngine.js, gulp/src/reporting/spec/reportEngineSpec.js, gulp/src/reporting/wizard/WizardFilterDateRange.jsx, myreports/datasources/base.py, myreports/datasources/comm_records.py, myreports/datasources/contacts.py, myreports/datasources/jsondriver.py, myreports/datasources/partners.py, myreports/tests/test_comm_records_datasource.py, myreports/tests/test_contacts_datasource.py, myreports/tests/test_datasource_utils.py, myreports/tests/test_partners_datasource.py, myreports/tests/test_views.py, myreports/views.py
* Start a new report. Defaults should match old system.
* Set date ranges in reports. See that partners/contacts live filter.
* Run reports. See that data is filtered.
* Clone reports. Date ranges should be preserved.
* History should work with date ranges.
=> Fix date ranges

gulp/npm-shrinkwrap.json, gulp/package.json, gulp/src/reporting/SetUpReport.jsx
> I'm suspicious that the real problem here is we don't actually need those form tags. At least the author of that article sometimes wanted to submit a form. We never want to do that. (Still merging though.)
I'd appreciate if you gave me a chance to respond to a concern next time, thanks.
`preventDefault` and `stopPropagation` will continue to be a problem, but this at least takes care of the run report button (except on IE 8, naturally).
=> Just converted form to div instead.

myreports/tests/test_views.py
The cookie is set client side, which we don't test.
=> Removed tests.

static/custom.css, static/my.jobs.css, templates/about.html, templates/privacy-policy.html
"Showing  4 changed files  with 0 additions and 39 deletions."
:tada:
=> Remove TRUSTe stuff [PD-2338]

templates/privacy-policy.html
Per the ticket, we also need to update the effective date of our privacy policy.
=> Update effective date [PD-2338]

gulp/src/reporting/DynamicReportApp.jsx, myreports/views.py
Two problems were preventing Reporting from working.
* IE11 was broken due to setting a property twice.
* We never removed the staff restriction from the APIs.
=> [PD-2431] IE 11 reporting break

mypartners/views.py
There's already a settings called PRM_EMAIL. While I wasn't technically shadowing that variable, the fact that I used the name is very confusing.
=> Used slightly less confusing name.

templates/home_page/home_page_dns_settings.html
=> [PD-2471] Updated DNS page

templates/flatpages/default.html, templates/flatpages/default_with_search_and_social.html
Adds the search page script to `flatpages/default_with_search_and_social.html`. Adds the static pages script to `flatpages/default.html`
=> [PD-2440] Added script to flatpages.

gulp/src/nonuseroutreach/reducers/navigation-reducer.js
Without a space somewhere, we render "to which you willhave your employees"
=> Add a space

gulp/src/common/ui/HelpText.jsx, gulp/src/nonuseroutreach/components/Inbox.jsx, gulp/src/reporting/actions/compound-actions.js, gulp/src/reporting/actions/report-state-actions.js, gulp/src/reporting/components/SetUpReport.jsx, gulp/src/reporting/reducers/report-state-reducer.js, gulp/src/reporting/spec/report-state-reducer-spec.js
=> [PD-2311] Empty partner/contact filter now disables run button.

gulp/src/common/ui/CalendarPanel.jsx, gulp/src/common/ui/DateField.jsx, gulp/src/myprofile/main.jsx
- reduced date range to 10 years.
- rather than range being from 2016-2006, it is now 2011-2020
=> [PD-1694] Changed date range to allow for future dates.

myprofile/templatetags/selection_boxes.py
Handy in the event of a total network outage. Runserver doesn't work otherwise.
=> Prefer local data files if they exist

gulp/src/manageusers/User.jsx, gulp/src/manageusers/main.jsx, myjobs/tests/test_manage_users.py, myjobs/urls.py, myjobs/views.py
Undoes work in https://directemployersfoundation.atlassian.net/browse/PD-2420
Fire up user management and edit some users: http://secure.my.jobs/manage-users/#/users
=> Revert 2420

default_settings.py, import_jobs/mongo.py, requirements.txt, seo/views/import_views.py, tasks.py
Tasks for adding job data to mongo when we run imports on a company.  
@fezick, @JLMcLaugh, @haliscooper How should we plan to QC this?
=> [PD-2464] Add job data to Mongo

default_settings.py
So we can turn them on and off individually.
=> Change the routing keys for mongo to point to a separate queue

requirements.txt
=> Pin html5lib in requirements.txt

gulp/src/common/ui/tags/TagSelect.jsx
What it says on the tin. If you filter results then choose "select all", only the filtered results will be added.
=> Select All only adds what's been filtered down to now

templates/flatpages/default.html, templates/flatpages/default_with_search_and_social.html, templates/home_page/home_page_billboard.html, templates/home_page/home_page_listing.html, templates/home_page/home_page_my_jobs.html, templates/home_page/home_page_static.html, templates/home_page/home_page_static_header_footer.html, templates/job_detail.html, templates/job_listing.html
Adds ",6" to the end of all the tracking URLS modified by #2395 and #2387.
=> [PD-2510] Added argument for engagement tracking

automation/source_codes.py, automation/tests/csv/bad/bad_header.csv, automation/tests/csv/bad/no_manipulations.csv, automation/tests/csv/good/different_types.csv, automation/tests/csv/good/indiana.csv, automation/tests/csv/good/one_row.csv, myjobs/tests/test_admin.py, redirect/admin.py
=> Update source code csv upload

gulp/src/nonuseroutreach/components/OutreachRecordTable.jsx, mypartners/views.py
Add handling for a button to load review outreach form.
Early merge to incorporate with @darrint's work.
=> [PD-2511.5] Add button for review

redirect/log_to_mongo.py
We're not in a Django environment when running this script; don't act like it is.
=> Import secrets from secrets

doc/source/developers/docker/use.rst
Docker be differentin'.
Docs be changin'.
=> [PD-2524] update to dockerdocs

mypartners/migrations/0035_auto__add_field_outreachrecord_subject.py, mypartners/models.py, mypartners/views.py
=> Add subject column to OutreachRecord [PD-2530]

gulp/src/common/ui/RemoteFormField.jsx, gulp/src/nonuseroutreach/actions/navigation-actions.js, gulp/src/nonuseroutreach/actions/process-email-actions.js, gulp/src/nonuseroutreach/api.js, gulp/src/nonuseroutreach/components/Email.jsx, gulp/src/nonuseroutreach/components/NonUserOutreachApp.jsx, gulp/src/nonuseroutreach/components/NonUserOutreachRouter.jsx, gulp/src/nonuseroutreach/components/ProcessRecordPage.jsx, gulp/src/nonuseroutreach/components/SearchDrop.jsx, gulp/src/nonuseroutreach/main.jsx, gulp/src/nonuseroutreach/reducers/navigation-reducer.js, gulp/src/nonuseroutreach/reducers/process-email-reducer.js, gulp/src/nonuseroutreach/spec/navigation-reducer-spec.js, gulp/src/nonuseroutreach/spec/process-email-actions-spec.js, gulp/src/nonuseroutreach/spec/process-email-reducer-spec.js, mypartners/forms.py, mypartners/tests/test_api.py, mypartners/urls.py, mypartners/views.py
This PR adds enough infrastructure to reach and show an add partner form.
Please look at the code for handling the form get. I haven't implemented posting but I will have a similar question then.
=> [PD-2516] Show Partner Form

gulp/src/nonuseroutreach/api.js, gulp/src/nonuseroutreach/components/SearchDrop.jsx, gulp/webpack.config.js, mypartners/views.py, static/custom.css
=> PD-2531 Add right aligned contact counts to the drop down.

gulp/src/nonuseroutreach/actions/search-or-add-actions.js, gulp/src/nonuseroutreach/api.js, gulp/src/nonuseroutreach/components/ProcessRecordPage.jsx, gulp/src/nonuseroutreach/components/SearchDrop.jsx, gulp/src/nonuseroutreach/spec/search-or-add-actions-spec.js
This enables the contact search in NUO.
=> [PD-2528] expose contact api

mypartners/migrations/0036_change_workflow_state_names.py, mypartners/views.py
It's all in the subject. Simple data migration to capitalize/slightly reword state names.
Run the migration
=> [PD-2522] Add Migration to Rename Workflow State Names

mypartners/tests/test_api.py, mypartners/views.py
=> Add dry run logic to conversion API

gulp/src/nonuseroutreach/actions/process-outreach-actions.js, gulp/src/nonuseroutreach/api.js, gulp/src/nonuseroutreach/components/Form.jsx, gulp/src/nonuseroutreach/components/OutreachCard.jsx, gulp/src/nonuseroutreach/components/OutreachCardContainer.jsx, gulp/src/nonuseroutreach/components/ProcessRecordPage.jsx, gulp/src/nonuseroutreach/main.jsx, gulp/src/nonuseroutreach/reducers/process-outreach-reducer.js, gulp/src/nonuseroutreach/spec/process-outreach-actions-spec.js, gulp/src/nonuseroutreach/spec/process-outreach-reducer-spec.js
This provides some rudimentary validation.
Submit an obviously bad record. Click around the minicards to see the errors.
=> Pd 2536  validation

redirect/log_to_mongo.py, redirect/views.py, requirements.txt
- Parse things into their proper types
- Add ip to analytics header
- Change where analytics header is constructed
See https://github.com/DirectEmployers/MyJobs-Analytics/pull/6
=> Analytics improvements [PD-2521]

default_settings.py, seo/views/import_views.py, tasks.py
rather than on each bad count.
=> Notify on 15 failures since 5pm last night

gulp/src/nonuseroutreach/components/SearchDrop.jsx
Would we do something like this in-line or define a variable prior to the return?
=> Remove contact count from NUO contact dropdown [PD-2564]

gulp/src/nonuseroutreach/actions/process-outreach-actions.js, gulp/src/nonuseroutreach/components/OutreachCardContainer.jsx, gulp/src/nonuseroutreach/components/ProcessRecordPage.jsx, gulp/src/nonuseroutreach/reducers/process-outreach-reducer.js, gulp/src/nonuseroutreach/spec/process-outreach-actions-spec.js, gulp/src/nonuseroutreach/spec/process-outreach-reducer-spec.js
This adds a workflow state form to the end of the workflow.
=> [PD-2566] workflow state form

gulp/src/nonuseroutreach/components/ProcessRecordPage.jsx, static/custom.css
Added return to records list button as part of ProcessRecordPage.render.
Added styles for nuo-buttons to match the mockup.
Updated classes on the "Form Ready for Submission" page to use new styles.
=> Add return to table button

dk2/dockerdev.sh
I don't know what happened but this appears to be the only thing we lost.
=> Redo Mongo container

gulp/src/nonuseroutreach/components/ProcessRecordPage.jsx, gulp/src/nonuseroutreach/components/SearchDrop.jsx
Add more contacts to the record using the provided cards on Communication Record and Workflow Status cards.
=> [PD-2580] Show and reset search cards when needed.

mypartners/forms.py
This fixes the immediate problem. I just want to get some feedback on if this is how we want to solve it.
=> Make contact required [PD-2568]

gulp/src/nonuseroutreach/actions/inbox-actions.js, gulp/src/nonuseroutreach/components/Inbox.jsx, gulp/src/nonuseroutreach/components/InboxManagementPage.jsx, gulp/src/nonuseroutreach/components/NonUserOutreachApp.jsx, gulp/src/nonuseroutreach/main.jsx
* Fixed a typo in a comment
* Added confirmation function and tied it to delete button on Inbox component.
* Added confirmation box to InboxManagementPage component.
* Added the necessary reducers to `nonuseroutreach/main.jsx`
=> Display the `common/ui/Confirm.jsx` dialog when the delete button is pressed

gulp/npm-shrinkwrap.json, gulp/package.json, gulp/src/sass/_media_queries.scss, gulp/src/sass/_variables.scss, gulp/src/sass/custom.scss
The purpose of this PR is to demonstrate and lay the foundation for the usage of sass (css preprocessor) in our project. 
Within the: gulp > src  directory, I created a directory call "sass", this is where our .scss files will live (in reality, it can live anywhere, I picked this location for convenience).  In the sass directory, I created a file called "custom.scss" which is the sass version of the pre-existing "custom.css" file that lives in the static directory. I also created a "_media_queries.scss" file and a "_variables.scss" file in the sass folder to demonstrate sass's ability to use variables, mixin functions, and imports.
In the package.json file's "dependencies" section, I added the "node-sass" module to allow NPM to compile sass to css, and the "onchange" module to allow NPM …
=> [PD-2581] - sass-demo

gulp/src/nonuseroutreach/actions/process-outreach-actions.js, gulp/src/nonuseroutreach/components/OutreachDetails.jsx, gulp/src/nonuseroutreach/spec/process-outreach-actions-spec.js, mypartners/migrations/0037_auto__add_field_outreachrecord_to_emails__add_field_outreachrecord_cc_.py, mypartners/models.py, mypartners/tests/test_views.py, mypartners/views.py
Also adds this new info to the ui.
=> Create outreach records regardless of contact/partner presence [PD-2596]

gulp/npm-shrinkwrap.json, gulp/package.json, gulp/src/common/ui/tags/Tag.jsx, gulp/src/sass/_media_queries.scss, gulp/src/sass/_variables.scss, gulp/src/sass/custom.scss, static/custom.css
In Reports > Tags > Filter by Tags, when you select a gray colored tag buttons and then when you hover on it, the background disappears and doesn't render the "X" icon to delete the tag, also the common "hand" icon doesn't appear on hover for available tags.  This PR is meant to correct this. :-)
=> [PD-2600] gray buttons disappears onhover

gulp/src/common/ui/DateTimePicker.jsx, gulp/src/sass/custom.scss
Edited the DateTimePicker Widget Styling for NUO Forms.
=> [pd-2617] DateTimePicker Widget Styling for the select dropdowns

gulp/src/nonuseroutreach/components/ProcessRecordPage.jsx, gulp/src/nonuseroutreach/forms.js, gulp/src/nonuseroutreach/spec/forms-spec.js
This matches the dynamic behavior of PRM's communication record form in NUO.
1. Look at the communication record form.
2. Change the contact type.
3. See how the form changes.
=> [PD-2621] Prune communication record form.

redirect/views.py
=> [PD-2586] Massive PR

dk2/dockerdev.sh
=> add restart redirect to dk commands

myreports/migrations/0014_hide_columns_from_output.py, myreports/views.py
Fixes bug described in ticket. It also suppresses some location fields which were showing up blank in reports. Those fields were never supposed to appear.
=> [ST-2975] Mark some columns as filter only and use that.

templates/wide_footer.html
=> [PD-2641] Fix Military Crosswalk link in footer.

gulp/src/sass/seo_base_styles.scss, gulp/webpack.config.js, mysearches/tests/test_views.py, mysearches/views.py, static/seo-base-scripts.js, templates/ga.html, templates/home_page/home_page_static_header_footer.bootstrap3.html, templates/includes/job_list_bootstrap3.html, templates/includes/topbar.html, templates/job_listing.html, templates/mysearches/saved_search_widget_bootstrap3.html, templates/search_box_bootstrap3.html, templates/seo_base_bootstrap3.html, templates/wide_header_bootstrap3.html
Consolidated as much javascript and css as allowable, removed 'stuff' that was not needed in the SEO base template. Added the 'defer' attribute to JavaScript file calls to speed up loading time.
=> [PD-2632] - Preliminary SEO base template

gulp/src/sass/seo_base_styles.scss, myjobs/templatetags/common_tags.py, myjobs/views.py, static/seo-base-scripts.js, templates/includes/topbar_v2.html, templates/seo_base_bootstrap3.html
"New" v2 topbar to match mock up.  v2 topbar uses  seo_base_styles.scss and bootstrap.min.css for styles, it still calls topbar.js for for mobile, however this will change once I'm done with PD-2630.  I changed myjobs > templatetags > common_tags.py file because the mock-up does not use the envelope icon anymore, instead it uses the text "Inbox".  I added conditional statement to myjobs > views.py to render the v2 topbar when v2 is requested, also added v2=1 to jsonp ajax call in seo-base-script.js
To test:
1. Change "admin" page to "My.jobs - Flexible flat Network (Texas Copy)...", and select: "home_page_static_header_footer_bootstrap3.html".
2. In the browser, navigate to www.my.jobs, please ensure that the "Employers / Post Jobs"
and "Create Account / Log In" is there and works when …
=> [PD-2631] Created v2 top bar

seo/helpers.py
I missed this logic path when first doing my bug fix.
Fixed where the fix needed fixing.
=> [PD-2551] Fixin' a Whoopsie

doc/source/developers/docker/use.rst, templates/myprofile/edit_profile.html
=> Add space to profile page title [PD-2663]

gulp/src/sass/seo_base_styles.scss, static/topbar_v2.js, templates/includes/topbar_v2.html
The  "Companies" sub-menu under "Employers" in topbar nav was not visible when I built out the new topbar. Changed my Company permission in the dkm shell so I can see this in my local topbar, then fixed the problem.  Added v2 version of topbar.js because of companies in the topbar nav, removed mobile JS that are not needed for this PR or maybe ever.  Removed un-used legacy topbar styles.
To test:
1. Please ensure you have access to the "Companies" submenu under Employers in tob bar nav.
2. Please ensure  that the "DirectEmployer Association" option is in the sub-menu and that this option also contain its own sub-menu.
=> [PD-2631] fixed discrepencies from Jason Sole's QC

gulp/src/sass/seo_base_styles.scss, myjobs/templatetags/common_tags.py, static/topbar_v2.js, templates/includes/topbar_v2.html
New mobile layout with improved responsiveness and mobile navigation.  The bottom nav submenu isn't complete yet, but the functionality should be there, knock on proverbial wood.
To test:
1. Either on a mobile web browser simulator of choice or, in a Jedi way, configure your phone to work with your dev environment, switch to v2 and navigate to www.my.jobs in mobile view (iPhone 5, 6, 6 plus, iPad.
2. Please start with "log out" state and ensure that there is an "Employers" and a "Log In" icon and text. Please click on both icons.
3. Please log in as admin user and test all links in bottom nav, it's fugly, but it should go where it's supposed to.
4. Please log in as "James" persona and test links, and ensure that there are only "Envelope" and "Profile" icons, and ensure that the submenu …
=> [PD-2630] started new mobile layout

mysearches/helpers.py, mysearches/tests/test_models.py, tasks.py
This is a first attempt at the partner saved search issue.  In it, I'm actually trying to get more explicit failures, so that in future we can diagnose this more easily.
=> Partner saved search bug

redirect/views.py
=> [PD-2667] Add time field for redirects

gulp/src/sass/seo_base_styles.scss
Purpose of PR is to fix vertical alignment of sub menu in mobile view for James Jobseeker.
1. Please switch to v2 template and to browser's mobile simulator.
2. Please log in as James the job seeker, feel free to use my James account: huy+james@app.directemployers.org / Bacon__1 (that's 2 under scores after the word Bacon).
3. Please click on the Envelope icon, there should be 2 working links in the sub menu.  Please click on the Profile icon, there should be 5 working links, the bottom-most link should be "Log Out"
=> [PD-2694] fixed vertical alignment of submenu for James persona

myjobs/tests/test_views.py, mypartners/tests/test_views.py, mysearches/tests/test_models.py, mysearches/tests/test_unsubscribing.py, mysearches/tests/test_views.py
@darrint, was this what you were imagining during our discussion?
=> Just call me Mr. Freeze

gulp/src/sass/seo_base_styles.scss
To test:
1. In v2 template, please switch to mobile simulator in browser.
2. Please click on the Beta tab in the bottom mobile nav bar.  Please ensure the sub menu is not covering up the bottom nav bar icons.  Thank you.
=> [PD-2697] styled new Analytics sub menu for mobile view

seo/helpers.py
This is an update to the existing URL redirect logic we use for DSEO search results. I added an additional conditional that checks if the company_slug filter has any capitals, and if it does, redirect to the proper, lower-case company name.
Go here (or another company, but make a few letters capital)
http://www.my.jobs/USA/jobs/bridgestone-AMericas-inc/careers/
Notice how it corrects the URL error.
Wooooooooooo.
=> [ST-3219] Another huge PR

templates/job_result.html
Fixing the V1 templates job results headers back to normal
=> Hot Fix For Job Results Headers

templates/home_page/home_page_listing_bootstrap3.html, templates/seo_base_bootstrap3.html, templates/v2/job_detail.html, templates/v2/job_listing.html
I'll talk to Huy personally to explain this one.
=> A PR for Huy's PR.

templates/home_page/home_page_listing_bootstrap3.html, templates/seo_base_bootstrap3.html
Purpose: Add Google SERP, JIRA task PD-2739
To test:
1.  Switch to v2.
2. Go to www.my.jobs and/or veterans.jobs, open browser web developer tool, please ensure this code is in the head section: 
Should look like this:
=> PD-2739, added Google Search Engine Result Pages (SERP) json-ld

templates/base-react-analytics.html
Quick Demo Fix for the css layout
=> quick demo fix

gulp/src/common/ui/Select.jsx, gulp/src/reporting/components/DataTypeSelectBar.jsx, gulp/src/reporting/components/SetUpReport.jsx, myreports/views.py
This creates a reporting type entry in new reporting for analytics. Picking it sends you to analytics.
It only shows up if the user has access to view analytics and the company has analytics access.
=> [PD-2714] Rough hack to get analytics link working.

analytics/api.py, import_jobs/mongo.py, redirect/log_to_mongo.py, requirements.txt
This allows for improved consistency between MyJobs and MyJobs-Analytics and also allows for MyJobs to connect to Mongo Atlas. 
It requires a few settings:
MONGO_SSL (new setting, a boolean for whether or not a secure connection is required)
MONGO_DBNAME (new setting)
MONGO_HOST or MONGO_CN (MONGO_CN is a new setting, and is the same as MONGO_HOST except pointing to a cluster instead)
=> [PD-2766] Switch to using the same interface to MongoDB that MyJobs-Analytics uses.

seo/models.py, seo/tests/test_models.py
Only works for requests that go through `get_template` but those are the only ones that matter anyway.
=> [PD-2468] Log the template version used for a request in New Relic.

doc/source/developers/styleguides/javascript.rst
I realized today that we have made some decisions over that last several months but haven't written any of it down.
Criticism welcome.
=> Update JavaScript standard based on more recent practice.

redirect/tests/setup.py
@mklauber:
When upgrading to 1.9, override_settings was moved to django.test
=> Change how we override settings

gulp/src/manageusers/components/ManageUsersApp.jsx, gulp/src/manageusers/reducers/company-reducer.js
This ensures that changes made on the Users page are reflected on the Roles page.
=> [ST-3428] Refresh Role data on new page load.

gulp/src/manageusers/components/Role.jsx
**Pros**: It works.
**Cons**: The code was pretty and now it's not.
I'm fully expecting there is a better way to do this.
=> [ST-3479] Correctly check for the user that is being removed from the list.

gulp/src/analytics/actions/tab-actions.js, gulp/src/analytics/components/Table/Table.js, gulp/src/analytics/components/Tabs/Tab.js, gulp/src/sass/analytics.scss
Task was to fix the closing of the tabs and active tabs
To test:
Pull down repository and filter the tabs to create new tabs. You can exit out of tabs and close tabs according to the X inside of the tab itself. They should close and if you close the active tab it should switch to another one being active.
=> [PD 2823] closing current tab leaves blank screen

mysearches/models.py
The `PartnerSavedSearch.save` function was unable to send a saved search because of an issue pickling some data on the instance. This is because we store the request object (which is unpicklable) on the instance so we can accesses it in the save function.
To reproduce this issue:
1. Make sure it's after 10, or update the `after_ten` value in `mysearches.models.PartnerSavedSearch.save` to reflect the current time.
2. Ensure that `CELERY_ALWAYS_EAGER = False` in your settings.
3. Try to create a new partner saved search that would be scheduled to send today (so Daily is sure to trigger this issue).
Before this fix there's an error because there is an attempt to pickle the module.
After this fix, there's no more error, because we're no longer trying to pickle the module. If you don't have …
=> [ST-3491] Don't attempt to pickle the request when sending a saved search.

gulp/src/analytics/components/AnalyticsApp.jsx, gulp/src/analytics/components/Calendar/Calendar.js, gulp/src/analytics/components/Charts/Bar/BarChart.js, gulp/src/analytics/components/Charts/ChartContainer.js, gulp/src/analytics/components/Header/Header.js, gulp/src/analytics/components/SideBar/SideBar.js, gulp/src/analytics/components/Tabs/Tab.js, gulp/src/analytics/components/Tabs/TabsContainer.js, gulp/src/analytics/components/Tabs/TabsPanel.js, gulp/src/sass/analytics.scss
Task was to edit the main menu display on mobile.
To Test:
Pull Down the repository. You can resize your screen and use the arrow button to show the main menu. Also did more css fixes for responsiveness which might have to get changed later but for now it all works and it's all responsive.
=> [PD 2822] primary menu wont display

deploy/settings.redirect_qc.py
Basically a copy of the prod settings but using QC databases, etc.
=> Add redirect qc settings file [PD-2636]

static/utils.184-4.js, templates/base-react.html, templates/base.html, templates/redirect/base.html, templates/seo_base.html
What do we think? Any edge cases I'm not thinking of?
=> Only do logout timer shenanigans if a user is logged in [PD-2841]

gulp/src/analytics/components/BreadCrumbs.js, gulp/src/analytics/components/Table/Table.js, gulp/src/analytics/components/Tabs/TabsContainer.js, gulp/src/sass/analytics.scss
Task was to add breadcrumbs to analytics. These are static breadcrumbs. I am breaking the task into 2 parts so this is just for the design and placement of the tabs. The data is not dynamic right now as the functionality part will be a bigger PR so I wanted to break the design and functionality into separate task.
To Test:
Pull down the repository. You will see the breadcrumbs at the top of the screen and how they will be implemented at the top going forward.
=> [PD 2848] add bread crumbs

analytics/api.py, gulp/src/analytics/components/Charts/Bar/BarChart.js, gulp/src/analytics/components/Table/PageSize.js, gulp/src/analytics/components/Table/Pagination.js, gulp/src/analytics/components/Table/Table.js, gulp/src/analytics/components/Table/TableContainer.js, gulp/src/analytics/components/Table/TableRows.js, gulp/src/sass/analytics.scss
Task was to add pagination to the table with all of the data inside
To Test:
Pull down the repository. The best way to test this with the most data would be switching the main dimension on the left to job titles and looking at the table. You will see the pagination for the table at the bottom.
Per Jason this morning. The breadcrumbs have been hidden for right now until the functionality is done for them.
=> [PD 2854] enable paging

analytics/api.py, analytics/tests/test_api.py
View analytics.
Visitors column isn't there.
:clinking_glasses:
=> [PD-2865] remove visitors column

gulp/src/manageusers/components/Activities.jsx, myjobs/models.py
Look at the activity list in user management. Ensure that both columns are populated and don't say the same thing.
=> Re-add descriptions to user management activity list [PD-2886]

deploy/settings.myjobs_qc.py, deploy/settings.myjobs_staging.py, deploy/settings.redirect_qc.py, deploy/settings.redirect_staging.py, deploy/settings_dseo_qc.py, deploy/settings_dseo_staging.py
This is the hack I've been using to "fix" QC.
As per the discussion this morning, hopefully not a long-term fix.
=> Do change_db after updating settings.
